
FFLAGS= $(FCOPTS)

OFILES= cey.o ghdwcs.o header.o info.o pix2ra.o \
	hotspot.o ra2pix.o show.o skymap.o skyview.o finding_chart.o \
	fra2pix.o fpix2ra.o offset.o

compile: ${OFILES}

LIB:	$(OFILES)
	if test "$(XIMADEV)" = "YES";\
	then liball_dev $(XANBIN)/lib/libximage.a;\
	else liball $(XANBIN)/lib/libximage.a;\
	fi

.f.o :
	xfor $*
