HD_COMPONENT_NAME	= suzaku

HD_COMPONENT_VERS	= 

HD_LIBRARY_ROOT		= xrrt

HD_LIB_STYLE		= ${HD_LIB_STYLE_F77}

HD_LIBRARY_SRC_cc	= \
xrrtatomicdata.cc xrrtatomscatfactor.cc \
xrrtbetamodel.cc xrrtcollimator.cc \
xrrtexternal.cc xrrtflatmodel.cc \
xrrtgroundmodel.cc xrrtmirror.cc xrrtmolecule.cc \
xrrtobstruction.cc xrrtoptical.cc xrrtphoton.cc \
xrrtphotonmodel.cc xrrtpolygon.cc \
xrrtraytrace.cc xrrtreflection.cc \
xrrtreflectivity.cc xrrtremapname.cc \
xrrtscatter.cc xrrtskymodel.cc xrrtstat.cc \
xrrtstructure.cc xrrttable.cc xrrtvector.cc \
xrrtquadrant.cc

HD_CXXFLAGS		= ${HD_STD_CXXFLAGS}

HD_INSTALL_LIBRARIES	= ${HD_LIBRARY_ROOT}

HD_SHLIB_LIBS		= ${HD_LFLAGS} -l${CFITSIO}

include ${HD_STD_MAKEFILE}
