HD_COMPONENT_NAME	= attitude

HD_COMPONENT_VERS	= 

HD_CTASK		= attdump

HD_CTASK_SRC_c		= attdump.c param.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -lcoordfits -lcoord -lparam_wrappers ${HD_STD_LIBS} ${SYSLIBS}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= attdump.par

HD_INSTALL_HEADERS	=

HD_INSTALL_HELP		= attdump.html

include ${HD_STD_MAKEFILE}
