#!/usr/local/bin/perl

opendir(OFILES,'./');
@allfiles = readdir OFILES;
closedir OFILES;
@ffiles = grep(/^.*\.f$/,@allfiles);
@machFiles = grep(/^.*\.f_.*$/,@allfiles);
%machNames = ('_alpha_OSF1', 'alpha',
	      '_mips', 'decmips',  
	      '_sun4', 'sun',	
	      '_sun4_Solaris', 'sol');


$OUTFILE = 'ofiles';
unlink $OUTFILE;
open(OUTFILE,">$OUTFILE");

$count = 0;
push( @printit,"OFILES = ");		   
for ($i = 0;$i<=$#ffiles;$i++) {
    $ffiles[$i] =~ s/\.f/\.o/;
    push( @printit,"$ffiles[$i] ");
    $count++;
    if ($count == 6) {
	$count = 0;
	push (@printit,"\\\n\t");
    }
}				
#foreach $ffile (@machFiles) {
#    $ffile =~ /^(.*\.f)(_.*)/;
#    $gotMachs{$2} = 1;
#    $machBase{$1} = 1;
#    if ( $2 eq '_sun4') {
#	push(@printit,"\t$1\\\n");
#    }
#}			       


print OUTFILE @printit;

close OUTFILE;

