HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= uvotgrblc

HD_TEST_PERL_SCRIPTS	= ut-uvotgrblc

HD_INSTALL_PFILES	= uvotgrblc.par

HD_TEST_PFILES		= ut-uvotgrblc.par

HD_INSTALL_HELP		= uvotgrblc.html

include ${HD_STD_MAKEFILE}
