HD_COMPONENT_NAME	= hitomi

HD_COMPONENT_VERS	= 

HD_INC_SUBDIR		= ahmission

HD_INSTALL_HEADERS	= ahmission.h caldb.h camstoffset.h delay.h hxiteldef.h keyword.h camsteldef.h camsio.h timfile.h spline.h

include ${HD_STD_MAKEFILE}
