HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= fimgdmp

HD_CTASK_SRC_c		= hfimgdmp.c

HD_CTASK_SRC_f		= fimgdmp.f

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -lfimage${FT_VERS} \
			  ${HD_STD_LIBS} ${SYSLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= fimgdmp.par

HD_INSTALL_HELP		= fimgdmp.hlp fimgdmp.txt

include ${HD_STD_MAKEFILE}
