HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= batphasimerr

HD_TEST_PERL_SCRIPTS	= ut_batphasimerr

HD_INSTALL_PFILES	= batphasimerr.par

HD_TEST_PFILES		= ut_batphasimerr.par

HD_INSTALL_HELP		= batphasimerr.html

include ${HD_STD_MAKEFILE}
