#!/usr/bin/perl
# $Source: /headas/headas/swift/uvot/tasks/uvotmag/ut-uvotmag,v $
# $Revision: 1.11 $
# $Date: 2006/05/24 21:24:58 $
#
#	ut-uvotdetect
#
#
# $Log: ut-uvotmag,v $
# Revision 1.11  2006/05/24 21:24:58  rwiegand
# Switched to using reltol instead of tolerance.
#
# Revision 1.10  2005/11/02 15:19:32  rwiegand
# Updated external command invocations to use Task::shell.
#
# Revision 1.9  2005/09/20 19:22:01  rwiegand
# Ensure the local copy of the test data is writable.
#
# Revision 1.8  2004/10/14 21:32:03  rwiegand
# Added CALDB mode to unit test.
#
# Revision 1.7  2004/07/09 16:19:01  rwiegand
# Implemented CALDB support.
#
# Revision 1.6  2004/05/12 16:41:59  rwiegand
# Intra-tool parameter consistency renaming effort.
#
# Revision 1.5  2004/04/19 14:58:06  rwiegand
# Added parameters for names of source rate/error columns.
#
# Revision 1.4  2003/11/24 22:57:35  rwiegand
# Corrected source list hash key.
#
# Revision 1.3  2003/09/30 14:01:51  rwiegand
# Support processing of multiple image/source list pairs.  The MAG column
# of the uvotdetect source list table is updated.
#
# Revision 1.1  2003/09/08 21:29:37  rwiegand
# Added infrastructure (unit test, help file, Makefile).
#

use strict;

package Test::MagFlux;
use base qw(Task::HEAdas);
use Task qw(:codes);

use FileHandle;


# main
{
	my $tool = Test::MagFlux->new;

	$tool->unitTest;

	exit($tool->{code});
}


sub execute
{
	my ($self) = @_;

	$self->pilOptions(
			options => [
				qw(input=string output=string caldb=boolean chatter=int)
			],
			get => 1,
			);

	$self->validate
		if $self->isValid;

	$self->runUvotmag
		if $self->isValid;
}


sub validate
{
	my ($self) = @_;

	# validate environment
	$self->validateEnvironment;

	# validate input/output directories
	foreach my $key (qw(input output)) {
		my $arg = $self->args->{$key};
		if (not -d $arg) {
			$self->fatal(BAD_INPUT,
				"invalid $key directory: $arg");
		}
	}
}


sub runUvotmag
{
	my ($self) = @_;

	my $args = $self->args;

	my $input = $args->{input};
	my $output = $args->{output};
	my $caldb = $args->{caldbFlag};

	# note: make a working copy of the source list (without magnitudes)
	# since it will be updated
	$self->shell("cp -f $input/nomag.fits $output/sources.fits");
	$self->shell("chmod +w $output/sources.fits");
	return if not $self->isValid;

	my @args = (
		infile    => "$output/sources.fits",
		zerofile  => $caldb ? 'CALDB' : "$input/swucolor.fits",
		coinfile  => $caldb ? 'CALDB' : "$input/swucoincorr.fits",

		filter    => 'default',
		ratecol   => 'RATE',
		errcol    => 'RATE_ERR',

		# cleanup   => 'no',
		chatter	  => 5,
	);

	# validate required files
	my %args = @args;
	$args{template} = "$input/template.fits";
	foreach my $key (qw(infile zerofile coinfile template)) {
		if ($args{$key} eq 'CALDB') {
		}
		elsif (not -f $args{$key}) {
			$self->fatal(BAD_INPUT,
				"invalid $key file: $args{$key}");
		}
	}

	{
		my $command = $self->buildCommand('uvotmag', @args);
		$self->shell($command);
	}

	if ($self->isValid) {
		my $command = $self->buildCommand('ftverify',
			infile => $args{infile},
			outfile => 'STDOUT',
			);
		$self->shell($command);
	}

	if ($self->isValid) {
		my $command = $self->buildCommand('ftdiff',
			infile1 => $args{template},
			infile2 => $args{infile},
			reltol => 1e-3,
			exclude => 'CREATOR,DATE,DATASUM',
			);
		$self->shell($command);
	}
}

