#!/usr/bin/perl
#
# $Source: /headas/headas/swift/uvot/tasks/uvotmag/uvotmag,v $
# $Revision: 1.38 $
# $Date: 2007/05/31 17:35:32 $
#
print <<EOM;
uvotmag is obsolete.

Perform coincidence loss correction using uvotcoincidence.
Convert rates to magnitudes and fluxes using uvotflux.
EOM

exit(1)
