HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

HD_INSTALL_PERL_LIBS	= bayes.pm config.pm dpi.pm env.pm fixup.pm gti.pm \
			  image_params.pm image.pm imageutils.pm lc.pm log.pm \
			  maskwt.pm pcode.pm posrefine.pm qmap.pm spectra.pm \
			  tdrss_lc.pm tdrss.pm

HD_PERL_SUBDIR		= BAT

include ${HD_STD_MAKEFILE}
