#!/usr/bin/perl
#
#  ut_nuscreen_fpmb
#
#
#
# Changes:
#      0.1.0 : NS 24/10/2011 - First Release
#      0.1.1 : NS 16/02/2012 - Added 'hkfile' input parameter
#      0.1.2 - NS 17/04/2012 - Added 'cleancols' input parameter
#      0.1.3 - NS 25/07/2012 - Dataset changed
#      0.1.4 - NS 24/10/2012 - Added 'depthcut' input parameter
#
#

use strict;
use ut_nustar;



# main
{
# Object Istances
    my $ut = ut_nustar->new(
			    name    => "nuscreen",
			    utname  => "ut_nuscreen_fpmb",
			    version => "0.1.4",
			    );
    
# Set Parameter
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
    
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_nuscreen";
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/nu00015011001B_uf.evt",
		   "$input/$ArchDir/nu00015011001B_fpm.hk.gz",
                   "$input/$ArchDir/nu00015011001B.mkf",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_nuscreen_fpmb01_cl.evt",
		    "$input/$ArchDir/ut_nuscreen_fpmb01_gti.fits",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("nuscreen","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;

# Task Files Check
    my %par_task = (
		    infile         =>  "$input/$ArchDir/nu00015011001B_uf.evt",
		    gtiscreen      =>  "yes",
		    evtscreen      =>  "yes",
		    gtiexpr        =>  "DEFAULT",
		    gradeexpr      =>  "DEFAULT",
		    statusexpr     =>  "DEFAULT",
		    createattgti   =>  "yes",
		    createinstrgti =>  "yes",
		    outdir         =>  $output,
		    obsmode        =>  "SCIENCE",
		    hkfile         =>  "$input/$ArchDir/nu00015011001B_fpm.hk.gz",
		    mkffile        =>  "$input/$ArchDir/nu00015011001B.mkf",
		    usrgtifile     =>  "NONE",
		    hkrangefile    =>  "CALDB",
		    evtrangefile   =>  "CALDB",
		    depthcut       =>  "NOMINAL",
		    timecol        =>  "TIME",
		    gtiext         =>  "GTI",
		    gtifile        =>  "DEFAULT",
 		    outfile        =>  "DEFAULT",   
		    cleancols      =>  "yes",
		    cleanup        =>  "yes",
		    chatter        =>  $chat,
		    clobber        =>  "$clobber",
		    history        =>  "yes"
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/nu00015011001B01_cl.evt");
	$ut->fverify("$output/nu00015011001B01_gti.fits");
	
	
# ftdiff
	$ut->ftdiff("$output/nu00015011001B01_cl.evt",
		    "$input/$ArchDir/ut_nuscreen_fpmb01_cl.evt");
	$ut->ftdiff("$output/nu00015011001B01_gti.fits",
		    "$input/$ArchDir/ut_nuscreen_fpmb01_gti.fits");
    }    
    
    $ut->delete();
}

