HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	=

HD_SUBDIRS		= src/ascalin src/rddlib src

HD_INSTALL_HEADERS	= include/asca.h include/ascatime.h include/faio.h \
			  include/jcoord.h include/nrutil.h

include ${HD_STD_MAKEFILE}
