HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

HD_INSTALL_PERL_SCRIPTS	= uvotaspcorr

HD_TEST_PERL_SCRIPTS	= ut-uvotaspcorr

HD_INSTALL_PFILES	= uvotaspcorr.par

HD_TEST_PFILES		= ut-uvotaspcorr.par

HD_INSTALL_HELP		= uvotaspcorr.html


include ${HD_STD_MAKEFILE}

