HD_COMPONENT_NAME	= suzaku

HD_COMPONENT_VERS	=

HD_LIB_STYLE		= ${HD_LIB_STYLE_F77}

HD_LIBRARY_ROOT         = ANL

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_INSTALL_LIBRARIES	= ${HD_LIBRARY_ROOT}

HD_INSTALL_HEADERS	=

HD_LIBRARY_SRC_c	= anl_body.c anl_flush.c anl_tool.c anl_task.c anl_msg.c

HD_LIBRARY_SRC_f	= anl_getlun.f dis45_getlun.f

include ${HD_STD_MAKEFILE}
