HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

HD_TEST_PERL_SCRIPTS	= ut-uvotchain

HD_TEST_PFILES		= ut-uvotchain.par

HD_INSTALL_PERL_SCRIPTS	= uvotchain

HD_INSTALL_HELP		= uvotchain.html

HD_INSTALL_PFILES	= uvotchain.par

include ${HD_STD_MAKEFILE}
