HD_COMPONENT_NAME	= attitude

HD_COMPONENT_VERS	=

HD_INSTALL_PERL_SCRIPTS	= aspcorr

HD_TEST_PERL_SCRIPTS    = ut-aspcorr

HD_INSTALL_PFILES	= aspcorr.par

HD_TEST_PFILES      = ut-aspcorr.par

HD_INSTALL_HELP		= aspcorr.html

include ${HD_STD_MAKEFILE}

