HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	=

HD_INSTALL_HELP		= gticolconv.html

HD_INSTALL_PERL_SCRIPTS	= day2time time2day gticolconv.pl

HD_INSTALL_PFILES	= day2time.par time2day.par gticolconv.par

include ${HD_STD_MAKEFILE}
