s/bat-burst-advocate/batgrbproduct/g
/@BEGIN_DOC/,/@END_DOC/ c\
# ======================================================== \
# WARNING: DO NOT EDIT THIS FILE!!! \
#   This script is derived from bat-burst-advocate. \
#   Edit that file instead. \
# ======================================================== \
# 
