HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= sf2pha

HD_CTASK_SRC_c		= hsf2pha.c

HD_CTASK_SRC_f		= cma_detnam.f cshfdmy.f me_detnam.f sf2pha.f \
			  wtxgs1.f wtxme1.f wtxtg1.f

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= sf2pha.par

HD_INSTALL_HELP		= sf2pha.hlp sf2pha.txt

include ${HD_STD_MAKEFILE}
