HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= fesdb2rdf

HD_CTASK_SRC_c		= hfesdb2rdf.c

HD_CTASK_SRC_f		= fesdb2rdf.f

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -lgro${FT_VERS} \
			  ${HD_STD_LIBS} ${SYSLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= fesdb2rdf.par

HD_INSTALL_HELP		= fesdb2rdf.hlp fesdb2rdf.txt

include ${HD_STD_MAKEFILE}
