#!/bin/sh
#
#
(if [ "x$POW" = x ] ; then \
     POW=$FTOOLS; \
     export POW;	
fi; \
POW_LIBRARY=$POW/lib/pow ;\
export POW_LIBRARY ;\
unset TCL_LIBRARY; unset TK_LIBRARY; unset TCLLIBPATH ;\
unset ITCL_LIBRARY; unset ITK_LIBRARY; \
LD_LIBRARY_PATH=$POW/lib:$LD_LIBRARY_PATH ;\
export LD_LIBRARY_PATH ;\
if [ "$POW_DISPLAY" != "" ] ; then \
$POW/bin/tclsh $POW_LIBRARY/POWplotClient.tcl -- $1 $2 $3 $4 $5 $6 $7 $8 $9;  
else 
$POW/bin/wish $POW_LIBRARY/POWplot.tcl -- $1 $2 $3 $4 $5 $6 $7 $8 $9; 
fi; \
exit)
