# SimASTE_XRSRMFsim.make

SimASTE_XRSRMFsim_DIR = $(ASTE_MODULE_DIR)/SimASTE_XRSRMFsim/2.3
SimASTE_XRSRMFsim = SimASTE_XRSRMFsim.o

SimASTE_XRSRMFsim.o: $(SimASTE_XRSRMFsim_DIR)/SimASTE_XRSRMFsim.c
	$(CC) -I$(SimASTE_Root_DIR) $(CFLAGS) $(ANLCFLAGS) -c $(SimASTE_XRSRMFsim_DIR)/SimASTE_XRSRMFsim.c
