HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_SUBDIRS		= sextractor/wcs sextractor/fits sextractor

HD_INSTALL_PERL_SCRIPTS	= uvotdetect

HD_INSTALL_PFILES	= uvotdetect.par

HD_INSTALL_REFDATA	= uvotdetect.*.sex uvotdetect.param uvotdetect.*.conv

HD_INSTALL_HELP		= uvotdetect.html sextractor.html

HD_TEST_PERL_SCRIPTS	= ut-uvotdetect

HD_TEST_PFILES		= ut-uvotdetect.par

include ${HD_STD_MAKEFILE}
