FCOMPL=
FCOPTS=-g
XANLIB=
PGPLOT=
FFLAGS= 
OFILES= pggetlevs.o pgsetlevs.o pg_setcir.o location.o pgfillbg.o \
	isdisplay.o ismouse.o ishardcopy.o ndc2wor.o \
        xpgimag.o xpgsitf.o xgrimg1.o xgrimg2.o xgrimg0.o

all: libpgadd.a

libpgadd.a: ${OFILES}
	liball ${XANBIN}/lib/libpgadd.a

.f.o:
	xfor $*

clean:  
	rm -f *.o

.c.o:
	xfor $*

.SUFFIXES : .f .c

