HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_LIBRARY_ROOT		= pgadd${FT_VERS}

HD_LIB_STYLE		= ${HD_LIB_STYLE_F77}

HD_LIBRARY_SRC_f	= isdisplay.f ishardcopy.f ismouse.f location.f \
			  ndc2wor.f pg_setcir.f pgfillbg.f pggetlevs.f \
			  pgsetlevs.f xgrimg0.f xgrimg1.f xgrimg2.f \
			  xpgimag.f xpgsitf.f

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_INSTALL_LIBRARIES	= ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
