HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

HD_CTASK		= batgse2dph

HD_CTASK_SRC_c		= batgse2dph.c binning.c read_ebins.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -lbatutils ${HD_STD_LIBS} ${SYSLIBS}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= batgse2dph.par

HD_INSTALL_HELP		= batgse2dph.html

include ${HD_STD_MAKEFILE}
