STRING(REGEX REPLACE "\\.cxx" ".obj" OBJECTS "${SOURCES}")
STRING(REGEX REPLACE "\\.c" ".obj" OBJECTS "${SOURCES}")

ADD_LIBRARY(${LIBNAME} SHARED ${SOURCES} ${CMAKE_CURRENT_BINARY_DIR}/${LIBNAME}.def)
#ADD_LIBRARY(${LIBNAME} SHARED ${SOURCES})

INSTALL_TARGETS(/lib RUNTIME_DIRECTORY /bin ${LIBNAME})

INSTALL_FILES(/include${HEADER_SUB} FILES ${HEADER_FILES})

SET_SOURCE_FILES_PROPERTIES(${CMAKE_CURRENT_BINARY_DIR}/${LIBNAME}.def PROPERTIES GENERATED 1)
SET(OUTDIR ${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_CFG_INTDIR})
ADD_CUSTOM_COMMAND(TARGET ${LIBNAME} PRE_LINK 
COMMAND C:/Perl/bin/perl
ARGS ${CMAKE_SOURCE_DIR}/BUILD_DIR/makedef.pl
${CMAKE_CURRENT_BINARY_DIR}/${LIBNAME}.def ${LIBNAME}
${OUTDIR} ${OBJECTS})

