HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= fhisto

HD_CTASK_SRC_c		= hfhisto.c fhisto.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= fhisto.par

HD_INSTALL_HELP		= fhisto.hlp fhisto.txt

include ${HD_STD_MAKEFILE}
