HD_COMPONENT_NAME	= suzaku

HD_COMPONENT_VERS	=

HD_INSTALL_HELP		= bnk.doc evs.doc \
			  manual/asca_anl_contrib.tex \
			  manual/bibliography.tex \
			  manual/bnk.tex \
			  manual/bnkkey-v0.80.eps \
			  manual/bnkkey-v1.00.eps \
			  manual/builtin_modules.tex \
			  manual/call_module-v0.80-flip.eps \
			  manual/call_module-v1.00-flip.eps \
			  manual/call_module-v1.00.eps \
			  manual/cli_com.tex \
			  manual/details_in_C.tex \
			  manual/details_in_Fortran.tex \
			  manual/evs.tex \
			  manual/getting_started.tex \
			  manual/hbook.tex \
			  manual/installation.tex \
			  manual/introduction.tex \
			  manual/mailing_list.tex \
			  manual/manual.tex \
			  manual/on_your_own.tex \
			  manual/reference_for_expert.tex \
			  manual/utility_routines.tex

include ${HD_STD_MAKEFILE}
