#!/usr/bin/perl
#
#  ut_numetrology
#
#
#
# Changes:
#      0.1.0 : NS 25/11/2011 - First Release
#      0.1.1 : NS 12/09/2013 - Added 'psdcal' input parameter
#
#

use strict;
use ut_nustar;



# main
{
# Object Istances
    my $ut = ut_nustar->new(
			    name    => "numetrology",
			    utname  => "ut_numetrology",
			    version => "0.1.1",
			    );
    
# Set Parameter
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
    
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_numetrology";  
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/nu40060001001_met.fits.gz",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_outpsdfile.fits",
		    "$input/$ArchDir/ut_outpsdfilecorr.fits",
		    "$input/$ArchDir/ut_mastaspectfile.fits",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("numetrology","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;

# Task Files Check
    my %par_task = (
		    metflag         => "yes",
		    metrologyfile   => "$input/$ArchDir/nu40060001001_met.fits.gz",
		    metgridfile     => "CALDB",
		    outpsdfile      => "$output/nu40060001001_psd.fits",
		    outpsdfilecor   => "$output/nu40060001001_psdcorr.fits",     
		    inpsdfilecor    => "",
		    alignfile       => "CALDB",
		    mastaspectfile  => "$output/nu40060001001_mast.fits",
		    psdcal          => "yes",
		    chatter         =>  $chat,
		    clobber         =>  "$clobber",
		    history         =>  "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/nu40060001001_psd.fits");
	$ut->fverify("$output/nu40060001001_psdcorr.fits");
	$ut->fverify("$output/nu40060001001_mast.fits");	
	
# ftdiff
	$ut->ftdiff("$output/nu40060001001_psd.fits",
		    "$input/$ArchDir/ut_outpsdfile.fits");

	$ut->ftdiff("$output/nu40060001001_psdcorr.fits",
		    "$input/$ArchDir/ut_outpsdfilecorr.fits");

	$ut->ftdiff("$output/nu40060001001_mast.fits",
		    "$input/$ArchDir/ut_mastaspectfile.fits");

    }
    
    $ut->delete();
}

