HD_COMPONENT_NAME	= attitude

HD_COMPONENT_VERS	= 

HD_LIBRARY_ROOT		= coord

HD_LIBRARY_SRC_c	= coorddef.c euler.c mapxform.c quat.c rolls.c \
			  rotmatrix.c xform2d.c image.c matrix.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_INSTALL_LIBRARIES	= ${HD_LIBRARY_ROOT}

HD_INSTALL_HEADERS	= coorddef.h coord.h euler.h mapxform.h quat.h \
			  rotmatrix.h xform2d.h

include ${HD_STD_MAKEFILE}
