HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= uvotskylss

HD_INSTALL_PFILES	= uvotskylss.par

HD_INSTALL_HELP		= uvotskylss.html

HD_TEST_PERL_SCRIPTS	= ut-uvotskylss

HD_TEST_PFILES		= ut-uvotskylss.par

include ${HD_STD_MAKEFILE}
