HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= fcolpar

HD_CTASK_SRC_c		= hfcolpar.c

HD_CTASK_SRC_f		= fcolpar.f

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= fcolpar.par

HD_INSTALL_HELP		= fcolpar.hlp fcolpar.txt

include ${HD_STD_MAKEFILE}
