#!/usr/bin/perl
#
#  ut_nuproducts_fpma
#
#
#
# Changes:
#      0.1.0 : NS 06/12/2011 - First Release
#      0.1.1 - NS 20/12/2011 - Renamed 'gtifile' input parameter to 'usrgtifile'
#      0.1.2 - NS 02/03/2012 - Added 'runmkarf' input parameter
#                            - Added 'runmkrmf' input parameter
#      0.1.3 - NS 16/05/2012 - Added 'phibin' input parameter
#      0.1.4 - NS 25/07/2012 - Added new input parameters
#      0.1.5 - NS 23/10/2012 - Added 'nulccorr' input parameters
#      0.1.6 - NS 14/12/2012 - Added 'nubkgcorr' and 'runbkgcorr' input parameters
#      0.1.7 - NS 07/06/2013 - Added input parameters needed by new version of nulccorr task
#                            - Dataset changed
#      0.1.8 - NS 10/07/2013 - Added input parameters needed by new version of nulccorr, numkarf and nubackscale tasks
#      0.1.9 - NS 22/11/2013 - Added new input parameters
#      0.2.0 - NS 20/03/2014 - Added 'grppha' input parameters
#      0.2.1 - NS 21/05/2014 - Added new input parameters
#      0.2.2 - NS 18/05/2015 - Updated default input parameters
#
#

use strict;
use ut_nustar;



# main
{
# Object Istances
    my $ut = ut_nustar->new(
			    name    => "nuproducts",
			    utname  => "ut_nuproducts_fpma",
			    version => "0.2.2",
			    );
    
# Set Parameter
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
    
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_nuproducts";  
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/nu00015011001A01_cl.evt.gz",
		   "$input/$ArchDir/nu00015011001A_fpm.hk.gz",
		   "$input/$ArchDir/nu00015011001_mast.fits.gz",
		   "$input/$ArchDir/nu00015011001_att.fits.gz",
		   "$input/$ArchDir/nu00015011001A_det1.fits",
		   "$input/$ArchDir/nu00015011001A_oa.fits.gz",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = (
		    "$input/$ArchDir/ut_nuproducts_fpma_sr.lc",
		    "$input/$ArchDir/ut_nuproducts_fpma_sr.pha",
		    "$input/$ArchDir/ut_nuproducts_fpma_bk.lc",
		    "$input/$ArchDir/ut_nuproducts_fpma_bk.pha",
		    "$input/$ArchDir/ut_nuproducts_fpma_sk.img",
		    "$input/$ArchDir/ut_nuproducts_fpma_sr_grp.pha",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("nuproducts","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;

# Task Files Check
    my %par_task = (
		    indir          => "$input/$ArchDir",
		    instrument     => "FPMA",
		    steminputs     => "nu00015011001",
		    infile         => "$input/$ArchDir/nu00015011001A01_cl.evt.gz",
		    srcregionfile  => "DEFAULT",
		    bkgextract     => "yes",
		    bkgregionfile  => "DEFAULT",
		    mastaspectfile => "$input/$ArchDir/nu00015011001_mast.fits.gz",
		    attfile        => "$input/$ArchDir/nu00015011001_att.fits.gz",
		    det1reffile    => "$input/$ArchDir/nu00015011001A_det1.fits",
		    outdir         => $output,
		    stemout        => "DEFAULT",
		    srcra          => 187.278,
		    srcdec         => 2.05,
		    srcradius      => 20,
		    bkgra          => 187.278,
		    bkgdec         => 2.05,		    
		    bkgradius1     => 70,		    
		    bkgradius2     => 90,
		    binsize        => 5,
		    lcfile         => "DEFAULT",
		    phafile        => "DEFAULT",
		    bkglcfile      => "DEFAULT",
		    bkgphafile     => "DEFAULT",		    
		    imagefile      => "DEFAULT",
		    usrgtifile     => "NONE",
		    plotdevice     => "gif",
		    pilow          => 35,
		    pihigh         => 1909,
		    pixposfile     => "CALDB",
		    alignfile      => "CALDB",
		    teldef         => "CALDB",
		    instrprobmapfile => "CALDB",
		    aberration     => "no",
		    pixbin         => 100,
		    optaxisfile    => "$input/$ArchDir/nu00015011001A_oa.fits.gz",
		    psffile        => "CALDB",
		    vignfile       => "CALDB",
		    extended       => "no",
		    cutmaps        => "yes",
		    percent        => 0.02,
		    barycorr       => "yes",
		    clockfile      => "CALDB",
		    orbitfile      => "$input/$ArchDir/nu00015011001_orb.fits",
		    srcra_barycorr => 187.278,
		    srcdec_barycorr=> 2.05,
		    outfile        => "DEFAULT",
		    usrgtibarycorr => "yes",
		    correctlc      => "yes",
		    hkfile         => "$input/$ArchDir/nu00015011001A_fpm.hk.gz",
		    lcenergy       => 10,
		    lcpsfflag      => "yes",
		    lcexpoflag     => "yes",
		    lcvignflag     => "no",
		    lcsrccorrfile  => "NONE",
		    lcbkgcorrfile  => "NONE",
		    runmkarf       => "no",
		    phibin         => 10,
		    runmkrmf       => "no",
		    runbackscale   => "no",
		    rungrppha      => "yes",
		    grpphafile     => "DEFAULT",
		    grpmincounts   => 30,
		    grppibadhigh   => 1909,
		    grppibadlow    => 35,
		    initseed       => "yes",
		    cleanup        => "yes",
		    chatter        => $chat,
		    clobber        => "$clobber",
		    history        => "yes", 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/nu00015011001A01_sr.lc");
	$ut->fverify("$output/nu00015011001A01_sr.pha");
	$ut->fverify("$output/nu00015011001A01_bk.lc");
	$ut->fverify("$output/nu00015011001A01_bk.pha");
	$ut->fverify("$output/nu00015011001A01_sk.img");
	$ut->fverify("$output/nu00015011001A01_sr_grp.pha");
	
	
# ftdiff
	$ut->ftdiff("$output/nu00015011001A01_sr.lc",
		    "$input/$ArchDir/ut_nuproducts_fpma_sr.lc");

	$ut->ftdiff("$output/nu00015011001A01_sr.pha",
		    "$input/$ArchDir/ut_nuproducts_fpma_sr.pha");

	$ut->ftdiff("$output/nu00015011001A01_bk.lc",
		    "$input/$ArchDir/ut_nuproducts_fpma_bk.lc");

	$ut->ftdiff("$output/nu00015011001A01_bk.pha",
		    "$input/$ArchDir/ut_nuproducts_fpma_bk.pha");

	$ut->ftdiff("$output/nu00015011001A01_sk.img",
		    "$input/$ArchDir/ut_nuproducts_fpma_sk.img");

	$ut->ftdiff("$output/nu00015011001A01_sr_grp.pha",
		    "$input/$ArchDir/ut_nuproducts_fpma_sr_grp.pha");

    }
    
    $ut->delete();
}

