HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_INSTALL_HELP		= clrwhere.txt cmdwhere.txt newmission.txt \
			  ximage.txt ximagestru.txt ximdir.txt \
			  ximage.hlp ximage.shf ximage.sum

include ${HD_STD_MAKEFILE}
