HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= battsplit

HD_TEST_PERL_SCRIPTS	= ut_battsplit

HD_INSTALL_PFILES	= battsplit.par

HD_TEST_PFILES		= ut_battsplit.par

HD_INSTALL_HELP		= battsplit.html

include ${HD_STD_MAKEFILE}
