HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	=

HD_INSTALL_PERL_SCRIPTS	= extpha hiback mk_allevt pcbgdcor pcpicor rosbary \
			  srcdetect

HD_INSTALL_HELP		= extpha.txt hiback.txt mk_allevt.txt pcbgdcor.txt \
			  pcpicor.txt rosbary.txt srcdetect.txt

include ${HD_STD_MAKEFILE}
