#!/usr1/local/bin/perl
#
# script to run bct and abc together
#
# Emily A. Greene    12/2/94
# HEASARC NASA/GSFC/HSTX
#
# from the original c-shell script
# 2/17/95  Documentation moved from rosbary.txt file into script by LE Brown
#
# Basic starting stuff

use Getopt::Std;

#============================================================#
#
# See if there are any flags:
#

getopts('h');			
if (defined $opt_h) {
    print <<EOHELP1;
    ROSBARY: 
        The barycenter correction software  has  been  written  at  MPE  and
        adapted  to  work directly on the FITS file process by the SASS. The
        original  code  consists  in  two  programs,  the   EXSAS   commands 
        CORRECT/ORBIT_DATA  and  CORRECT/BARYCENTER.The first task corrects,
        at the barycenter, the sampling times contained in  the  orbit  data
        file  (obtained every 60 seconds). The second applies the correction
        to the arrival time of the event by interpolating on the  correction
        computed  for  the  orbit  times.   The  programs  name  which  work 
        directly on FITS file are BTC  (corrects  the  times  in  the  orbit
        table  at  the barycenter) and ABC (corrects the arrival time of the
        photons in the events list at the barycenter).  Rosbary is a  script
        which  in  sequence  run  first  program,  BTC which creates a table
        correction, and second program, ABC which creates a new  event  file
        where the column TIME containes times corrected at the barycenter.
        
        
    PARAMETERS
        
        orbitfile [filename]
            Input  orbit  file name. The program accepts the three different
            format for the orbit file  produced  by  the  ROSAT  processing.
            The  new  RDF format file where the orbit data are stored within
            an extension called EXTNAME=EPHEM. The old style US format  file
            where  the orbit data are splitted in several extension within a
            file called EXTNAME=SPORB. The old  German  style  format  where
            the  orbit  data  are  stored  within  one extension. No EXTNAME
            keyword is used in the table in this last case.
        
        out_corr_table [filename]
            The name of the output file in FITS  containing  the  correction
            table.   The  output  file  contains 4 columns, respectively the
            integer  and  the  fractional  part  of  the   uncorrected   and 
            corrected  times  for  the orbit data.  The times are written as
            JD.
        
        ra_src [string]
            The r.a. of  the  source  given  either  in  hh:mm:ss.s  or  deg
            (equinox 2000).
        
        dec_src [string]
            The  dec.  of  the  source  given  either  in  dd:mm:ss.s or deg
            (equinox 2000.0).
    
        eventfile [filename]
            Input event file name.  The  task  accepts  either  the  old  US
            format  event  FITS  file  or the new format RDF event file. The
            German style format needs to be converted into a  RDF  by  using
            the ftools gevt2rdf.
        
        eventoutput [filename]
            Output  file  name  for  the  event  file  containing  the times
            corrected.   Note  that  the  correction  is  applied   to   the 
            extensions containg the events and good time interval extension.
        
        
    SEE ALSO
         bct, abc
EOHELP1
exit;
    }


require "utils.pl";

# now onto the program ...

print " Input orbit filename[ext#]\n";
$orb_fil = <STDIN>;
chop $orb_fil;

print " Output barycenter filename\n";
$bc_fil = <STDIN>;
chop $bc_fil;

print " Input events filename[ext#]\n";
$in_fil = <STDIN>;
chop $in_fil;

print " Output events filename:\n";
$ou_fil = <STDIN>;
chop $ou_fil;

print " RA string (hh mm ss.s or degrees, epoch 2000):\n";
$ra_str = <STDIN>;
chop $ra_str;

print " DEC string (dd mm ss.s or degrees, epoch 2000):\n";
$dec_str = <STDIN>;
chop $dec_str;

@result = &runcom("bct infile=$orb_fil outfile=$bc_fil ra=$ra_str dec=$dec_str");
@result = &runcom("abc infile=$in_fil bcfile=$bc_fil outfile=$ou_fil ra=$ra_str dec=$dec_str");

