HD_COMPONENT_NAME       = hitomi

HD_COMPONENT_VERS       =

HD_INSTALL_PERL_SCRIPTS = ahplot.pl camsplot.pl hxiplot.pl sxiplot.pl sxsplot.pl gtiplot.pl

HD_INSTALL_PFILES       = ahplot.par camsplot.par hxiplot.par sxiplot.par sxsplot.par gtiplot.par

#HD_INSTALL_HELP         = ahplot.html camsplot.html hxiplot.html sxiplot.html sxsplot.html 

HD_INSTALL_PERL_LIBS	= ahplot.pm

include ${HD_STD_MAKEFILE}

