#!perl
# $Source: /headas/headas/swift/uvot/tasks/uvotgrplot/ut-uvotgrplot,v $
# $Revision: 1.1 $
# $Date: 2009/07/26 03:17:37 $
#
#
# $Log: ut-uvotgrplot,v $
# Revision 1.1  2009/07/26 03:17:37  rwiegand
# Implemented unit test.
#

use strict;

package Test::GrismPlot;
use base qw(Task::HEAdas);
use Task qw(:codes);



# main
{
	my $tool = __PACKAGE__->new;

	$tool->unitTest;

	exit($tool->{code});
}


sub execute
{
	my ($self) = @_;

	$self->pilOptions(
			options => [
				qw(input=string output=string chatter=int)
			],
			get => 1,
			);

	$self->validate
		if $self->isValid;

	$self->runUvotgrplot
		if $self->isValid;
}


sub validate
{
	my ($self) = @_;

	# validate environment
	$self->validateEnvironment;

	# validate input/output directories
	foreach my $key (qw(input output)) {
		my $arg = $self->args->{$key};
		if (not -d $arg) {
			$self->fatal(BAD_INPUT,
				"invalid $key directory: $arg");
		}
	}
}


sub runUvotgrplot
{
	my ($self) = @_;

	my $args = $self->args;

	my $input = $args->{input};
	my $output = $args->{output};

	my @args = (
		infile    => "$input/spectrum.pha",
		bkgfile   => "$input/background.pha",
		outfile   => "$output/plot.ps",

		clobber   => 'yes',
		chatter	  => 5,
	);

	# validate required files
	my %args = @args;
	foreach my $key (qw(infile bkgfile)) {
		if (not -f $args{$key}) {
			$self->fatal(BAD_INPUT,
				"invalid $key file: $args{$key}");
		}
	}

	{
		my $command = $self->buildCommand('uvotgrplot', @args);
		$self->shell($command);
	}

	$self->warning("no FITS files to verify- view $args{outfile}");
}

