HD_COMPONENT_NAME	= Xspec

HD_COMPONENT_VERS	= 

HD_CXXTASK		= cxsetup

HD_CXXTASK_SRC_cxx	= cxsetup.cxx MapAndWrappers.cxx ../initpackage/ModelMap.cxx

HD_CXXFLAGS		= ${HD_STD_CXXFLAGS}

HD_CXXLIBS		= ${HD_STD_CXXLIBS}

HD_INSTALL_HEADERS	= MapAndWrappers.h

HD_INSTALL_TASKS	= ${HD_CXXTASK}

include ${HD_STD_MAKEFILE}
