HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= uvotapercorr

HD_TEST_PERL_SCRIPTS	= ut-uvotapercorr

HD_INSTALL_PFILES	= uvotapercorr.par

HD_TEST_PFILES		= ut-uvotapercorr.par

HD_INSTALL_HELP		= uvotapercorr.html

include ${HD_STD_MAKEFILE}
