HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= uvotflux

HD_TEST_PERL_SCRIPTS	= ut-uvotflux

HD_INSTALL_PFILES	= uvotflux.par

HD_TEST_PFILES		= ut-uvotflux.par

HD_INSTALL_HELP		= uvotflux.html

include ${HD_STD_MAKEFILE}
