HD_COMPONENT_NAME	= heatools

HD_COMPONENT_VERS	=

HD_INSTALL_HELP         = heatools.html binfilter.html colfilter.html \
			  filenames.html imfilter.html rowfilter.html \
			  calc_express.html tilecompression.html \
			  pixfilter.html

include ${HD_STD_MAKEFILE}
