#!/usr/bin/perl
#
#  ut_nubackscale_fpma
#
#
#
# Changes:
#      0.1.0 : NS 06/06/2013 - First Release
#      0.1.1 - NS 10/07/2013 - Added new input parameters
#      0.1.2 - NS 28/03/2014 - Added new input parameters
#
#

use strict;
use ut_nustar;



# main
{
# Object Istances
    my $ut = ut_nustar->new(
			    name    => "nubackscale",
			    utname  => "ut_nubackscale_fpma",
			    version => "0.1.2",
			    );
    
# Set Parameter
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
    
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_nubackscale";  
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/nu00015011001A01_bk.pha",
		   "$input/$ArchDir/nu00015011001A01_sr.pha",
		   "$input/$ArchDir/nu00015011001A01_cl.evt",
		   "$input/$ArchDir/nu00015011001_mast.fits",
		   "$input/$ArchDir/nu00015011001_att.fits",
		   "$input/$ArchDir/nu00015011001A_det1.fits",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = (
		    "$input/$ArchDir/ut_bkgphacorr_fpma.pha",
		    "$input/$ArchDir/ut_srcphacorr_fpma.pha",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("nubackscale","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;

# Task Files Check
    my %par_task = (
		    srcphafile     => "$input/$ArchDir/nu00015011001A01_sr.pha",
		    srcoutfile     => "$output/out_srcphacorr_fpma.pha",
		    bkgphafile     => "$input/$ArchDir/nu00015011001A01_bk.pha",
		    bkgoutfile     => "$output/out_bkgphacorr_fpma.pha",
		    evtfile        => "$input/$ArchDir/nu00015011001A01_cl.evt",
		    pixposfile     => "CALDB",
		    alignfile      => "CALDB",
		    mastaspectfile => "$input/$ArchDir/nu00015011001_mast.fits",
		    attfile        => "$input/$ArchDir/nu00015011001_att.fits",
		    teldef         => "CALDB",
		    instrprobmapfile => "CALDB",
		    #usrgtifile     => "NONE",
		    inexpomapfile  => "NONE",
		    aberration     => "no",
		    det1reffile    => "$input/$ArchDir/nu00015011001A_det1.fits",
		    pixbin         => 100,
		    percent        => 0.02,
		    srccorrect     => "yes",
		    bkgcorrect     => "yes",
		    initseed       => "yes",
		    chatter        => $chat,
		    clobber        => "$clobber",
		    history        => "yes",
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/out_bkgphacorr_fpma.pha");
	$ut->fverify("$output/out_srcphacorr_fpma.pha");
	
# ftdiff
	$ut->ftdiff("$output/out_bkgphacorr_fpma.pha",
		    "$input/$ArchDir/ut_bkgphacorr_fpma.pha");

	$ut->ftdiff("$output/out_srcphacorr_fpma.pha",
		    "$input/$ArchDir/ut_srcphacorr_fpma.pha");

    }
    
    $ut->delete();
}

