#!/usr/bin/perl
#
#  ut_nuflagbad_fpma
#
#
#
# Changes:
#      0.0.1 : NS 07/07/2011 - First Release
#
#

use strict;
use ut_nustar;



# main
{
# Object Istances
    my $ut = ut_nustar->new(
			    name    => "nuflagbad",
			    utname  => "ut_nuflagbad_fpma",
			    version => "0.1.0",
			    );
    
# Set Parameter
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
    
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_nuflagbad";  
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/NUSTAR_L1_CPT_threshold_2_EVENTS_FPMA.fits",
                   "$input/$ArchDir/NUSTAR_L1_CPT_threshold_2_DISPIX_FPMA.fits",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_nuflagbad_fpma.evt",
                    "$input/$ArchDir/ut_nuflagbad_fpmabp.fits",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("nuflagbad","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;

# Task Files Check
    my %par_task = (

		    infile      =>  "$input/$ArchDir/NUSTAR_L1_CPT_threshold_2_EVENTS_FPMA.fits",
		    dispixfile  =>  "$input/$ArchDir/NUSTAR_L1_CPT_threshold_2_DISPIX_FPMA.fits",
		    outfile     =>  "$output/out_nuflagbad_fpma.evt",
		    bpfile      =>  "CALDB",
		    userbpfile  =>  "NONE",
		    outbpfile   =>  "$output/out_nuflagbad_fpmabp.fits",
		    chatter     =>  $chat,
		    clobber     =>  "$clobber",
		    history     =>  "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/out_nuflagbad_fpma.evt");
	$ut->fverify("$output/out_nuflagbad_fpmabp.fits");

	
	
# ftdiff
	$ut->ftdiff("$output/out_nuflagbad_fpma.evt",
		    "$input/$ArchDir/ut_nuflagbad_fpma.evt");
	$ut->ftdiff("$output/out_nuflagbad_fpmabp.fits",
		    "$input/$ArchDir/ut_nuflagbad_fpmabp.fits");

    }    
    
    $ut->delete();
}

