#ifndef MAP_H
#define MAP_H

/*
 *  Routines that retrieve map info
 */

PROTOCCALLSFFUN1(INT,ISLOADED,isloaded,STRING)
#define ISLOADED(MAPID) CCALLSFFUN1(ISLOADED, isloaded, STRING, MAPID)

#define GHEADTYPE(A,B,C) CCALLSFSUB3(GHEADTYPE,gheadtype,STRING,PSTRING,PINT, A,B,C)
#define PRHEAD(A,B,C) CCALLSFSUB3(PRHEAD,prhead,STRING,STRING,PINT, A,B,C)
#define GHEADI(A,B,C,D,E) CCALLSFSUB5(GHEADI,gheadi,STRING,STRING,PINT,INT,PINT, A,B,C,D,E)
#define GHEADD(A,B,C,D,E) CCALLSFSUB5(GHEADD,gheadd,STRING,STRING,PDOUBLE,INT,PINT, A,B,C,D,E)
#define GHEADS(A,B,C,D,E) CCALLSFSUB5(GHEADS,gheads,STRING,STRING,PSTRING,INT,PINT, A,B,C,D,E)
#define LSMAPID() CCALLSFSUB0(LSMAPID,lsmapid)
#define GETTMPMAP(A,B) CCALLSFSUB2(GETTMPMAP,gettmpmap,PSTRING,PINT, A,B)
#define FREETMPMAP(A,B) CCALLSFSUB2(FREETMPMAP,freetmpmap,STRING,PINT, A,B)

#endif
