#ifndef PGUTIL_H
#define PGUTIL_H

/*
 *  Routines that perform some PGPLOT-related ops
 */

PROTOCCALLSFFUN0(INT,ISTK,istk)
#define ISTK() CCALLSFFUN0(ISTK, istk)

PROTOCCALLSFFUN0(INT,ISDISPLAY,isdisplay)
#define ISDISPLAY() CCALLSFFUN0(ISDISPLAY, isdisplay)

PROTOCCALLSFFUN0(INT,ISMOUSE,ismouse)
#define ISMOUSE() CCALLSFFUN0(ISMOUSE, ismouse)

#define GET_COLOR(COLOR) CCALLSFSUB1(GET_COLOR,get_color,PINT, COLOR)
#define LINE_PGSTATE(COLOR,LWIDTH,LSTYLE) CCALLSFSUB3(LINE_PGSTATE,line_pgstate,INT,INT,INT, COLOR,LWIDTH,LSTYLE)
#define DRWCIR(X,Y,R) CCALLSFSUB3(DRWCIR,drwcir,FLOAT,FLOAT,FLOAT, X,Y,R)
#define DRWELP(A,B,C,D,E,F) CCALLSFSUB6(DRWELP,drwelp,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT, A,B,C,D,E,F)

#endif
