HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

HD_INSTALL_PERL_LIBS	= AspcorrTable.pm \
			  BadPixels.pm Calibration.pm Convert.pm Filter.pm \
			  PrettyPicture.pm Rebin.pm Snapshot.pm Source.pm \
			  Subtask.pm Time.pm

HD_PERL_SUBDIR		= UVOT

include ${HD_STD_MAKEFILE}
