# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded xsl_help 1.0 [list tclPkgSetup $dir xsl_help 1.0 {{xsel_help.tcl source {help_manual xhelp}}}]
package ifneeded xsl_menu 1.0 [list tclPkgSetup $dir xsl_menu 1.0 {{xsel_menu.tk source {CasMenu ComMenu RunButton RunCommand RunEntry cancel_par_request query_parm xsltermout}} {xsel_help.tk source {append_list delete_list get_content get_index help_list select_cmd set_select tklparm}} {xsel_file.tk source {cancel_file file_select filter_file multi_scroll ok_file read_file reset_dir reset_file reset_filter select_dir select_file set_dir set_file}} {xsel_ctrl.tk source {DefLockXslLockwin LockXslWin UnLockEntry UnLockXslWin UpdateXslMenu clear_log refresh update_cmd update_entry xslquit}} {xsel_learn.tk source {RegisCommand learn_edit learn_new learn_off learn_on learn_read learn_run learn_write update_learn}}}]
package ifneeded xsl_miss 1.0 [list tclPkgSetup $dir xsl_miss 1.0 {{xsel_miss.tcl source mset}}]
package ifneeded xsl_plot 1.0 [list tclPkgSetup $dir xsl_plot 1.0 {{xsel_plot.tk source {FilterTime PlotImage PlotMulti PlotTwoColumns PlotXHK PlotXImage PlotXLCurve PlotXMKF PlotXSpec XselPlotInit comptime destroyline drawhline endline ok_list reset_list select_all select_one startline xsl_nlist}}}]
