#!/usr/bin/perl
#
#  ut_numkrmf_fpma
#
#
#
# Changes:
#      0.1.0 : NS 05/03/2012 - First Release
#      0.1.1 : NS 14/12/2012 - Added 'cmprmf' input parameter
#      0.1.2 : NS 14/06/2013 - Added 'usrgtifile' input parameter
#      0.1.3 : NS 23/07/2013 - Changed dataset
#
#

use strict;
use ut_nustar;



# main
{
# Object Istances
    my $ut = ut_nustar->new(
			    name    => "numkrmf",
			    utname  => "ut_numkrmf_fpma",
			    version => "0.1.3",
			    );
    
# Set Parameter
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
    
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_numkrmf";  
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/nu60002023014A01_cl.evt",
		   "$input/$ArchDir/nu60002023014A01_src.reg",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_numkrmf_fpma.rmf",
		    );

    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("numkrmf","ftdiff","fverify", "pquery2");

    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;

# Task Files Check
    my %par_task = (

		    infile        =>  "$input/$ArchDir/nu60002023014A01_cl.evt",
		    usrgtifile    =>  "NONE",
		    srcregionfile =>  "$input/$ArchDir/nu60002023014A01_src.reg",
		    outfile       =>  "$output/out_numkrmf_fpma.rmf",
		    grprmffile    =>  "CALDB",
		    rmfdir        =>  "CALDB",
		    cmprmf        =>  "yes",
		    chatter       =>  $chat,
		    clobber       =>  "$clobber",
		    history       =>  "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/out_numkrmf_fpma.rmf");
	
	
# ftdiff
	$ut->ftdiff("$output/out_numkrmf_fpma.rmf",
		    "$input/$ArchDir/ut_numkrmf_fpma.rmf");
    }    
    
    $ut->delete();
}

