HD_COMPONENT_NAME	= hitomi

HD_COMPONENT_VERS	= 

HD_LIBRARY_ROOT		= imagetranslib

HD_LIBRARY_SRC_c	= area_transform.c center_transform.c events_transform.c flag_transform.c flat_transform.c image.c interalpha_transform.c interpolate_transform.c methods.c overlap.c red_black_tree.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_SHLIB_LIBS		= ${HD_LFLAGS} ${AH_STD_LIBS} -lcoord -lcoordfits -lrandom -lparam_wrappers ${HD_STD_LIBS}

HD_INSTALL_LIBRARIES	= ${HD_LIBRARY_ROOT}

include ${HD_STD_MAKEFILE}
