#!/usr/local/bin/perl
#
# convert Imakefile.def -> Includes.make
#
#  2004/02/07 Y.ISHISAKI
#

$end_count = -1;

print <<EOF
#
# ** DO NOT EDIT ***
# This file is automatically generated by Includes.make.pl
EOF
;

while (<>) {
	chop;
	if ( / End of Includes.make / ) {
		$end_count = 2;
	}
	if ( /^\/\*/ ) {
		s/^\/\*/#/;
		s/[ \t]*\*\/$//;
		print $_ . "\n";
	} elsif ( /^\/\// ) {
		s/^\/\//#/;
		print $_ . "\n";
	} elsif ( /^\*\/$/ ) {
		print "#\n";
	} else {
		print $_ . "\n";
	}
	if ( 0 < $end_count ) {
		$end_count--;
		last if ( 0 == $end_count );
	}
}
