# makefile template for ANL programs
#
# program
#
#ALL = anl-prog
#OBJ = anlinit.o anl-prog.o
#
#start:
#	$(MAKE) `uname`
#
#anl-prog: $(OBJ)
#	$(CC) -o $@ $(OBJ) $(LINK_LIB) 
#

include adsoft.versions
include Includes.make

# system library

LIBSYS	= $(DEFAULT_F77_LNK)

LINK_LIB = \
$(USR_LNK) $(ANL_LNK) $(COM_CLI_LNK) \
$(ASTETOOL_LNK) $(ASCATOOL_LNK) $(ATFUNCTIONS_LNK) \
$(CERN_LNK) $(CWFITSIO_LNK) $(HEADAS_LNK) $(CFITSIO_LNK) $(LIBSYS) -lm

ANLCFLAGS = \
$(USR_INCLUDE) -I$(ANL_INC) -I$(COM_CLI_INC) \
-I$(ASTETOOL_INC) -I$(ASCATOOL_INC) -I$(ATFUNCTIONS_INC) \
-I$(CFORTRAN_INC) -I$(CERN_INC) -I$(CWFITSIO_INC) -I$(CFITSIO_INC) \
$(HEADAS_INCLUDE)

ANLFFLAGS = -I$(ANL_INC)

MKANLINIT = $(ANL_BIN)/mkanlinit

# dependencies

DECOPT = FC="f77 -extend_source" LIBSYS="-lUfor -lfor -lutil -li -lots"
OSFOPT = FC="f77 -extend_source" LIBSYS="-lUfor -lfor -lFutil -lots"
SUNOPT = CC=gcc FC="f77 -e" LIBSYS="-L`echo /usr/lang/SC?.0` -lF77"
LNXOPT = CC="gcc -fwritable-strings -Dg77Fortran" FC="g77 -w -fno-second-underscore -fno-f2c" LIBSYS="-lg2c -lnsl"
MACOPT = CC="gcc -fwritable-strings -Dg77Fortran" FC="g77 -w -fno-second-underscore -fno-f2c" LIBSYS="-L/sw/lib -lg2c"

.SUFFIXES: .def

.def.o:
	( cat $<; echo ""; echo $*.c; echo yes ) | $(MKANLINIT); \
	$(CC) $(CFLAGS) -c -o $@ $*.c;

.f.o:
	$(FC) $(FFLAGS) $(ANLFFLAGS) -c -o $@ $<

.c.o:
	$(CC) $(CFLAGS) $(ANLCFLAGS) -c -o $@ $<

all: $(ALL)

ULTRIX:
	$(MAKE) $(DECOPT) all

OSF1:
	$(MAKE) $(OSFOPT) all

SunOS:
	$(MAKE) $(SUNOPT) all

Linux:
	$(MAKE) $(LNXOPT) all

Darwin:
	$(MAKE) $(MACOPT) all

Default:
	$(MAKE) $(LNXOPT) all

Includes.inc: $(ANL_INC)/Includes.inc
	cp $? $@

clean::
	-$(RM) Includes.inc $(ALL) *.o
	-$(RM) `ls -1 *.def | sed 's/\.def$$/.c/g'`

cleandir::
