HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= uvotevtlc

HD_TEST_PERL_SCRIPTS	= 

HD_INSTALL_PFILES	= uvotevtlc.par

HD_TEST_PERL_SCRIPTS	= ut-uvotevtlc

HD_TEST_PFILES		= ut-uvotevtlc.par

HD_INSTALL_HELP		= uvotevtlc.html

include ${HD_STD_MAKEFILE}
