HD_COMPONENT_NAME	= suzaku

HD_COMPONENT_VERS	=

HD_LIBRARY_ROOT         = aste_hxd

HD_LIB_STYLE		= ${HD_LIB_STYLE_F77}

HD_CFLAGS		= \
-I../../aste_anl/include -I../../com_cli/include \
-I../../hxd/include \
-I../../com/src/function/aste_gethk \
-I../../com/src/function/aste_ti2time \
-I../../com/src/function/aeFitsHeaderUtil \
-I../../com/src/function/aste_caldb \
-I../../com/src/function/aste_orbit \
-I../../com/src/function/aste_aspect \
-Ifunction/hxdFitsCommentUtil \
-Ifunction/hxdFitsHeaderUtil \
-Ifunction/hxdFitsHeaderUtil_old \
-Ifunction/hxdGetHKUtil \
-Ifunction/hxdTimeUtil \
-Ifunction/hxdarfUtil \
-Ifunction/hxdbstFitsToBnkUtil \
-Ifunction/hxdbstFitsUtil \
-Ifunction/hxdBstJudgeUtil \
-Ifunction/hxdeventFitsToBnkUtil \
-Ifunction/hxdeventFitsUtil \
-Ifunction/hxdcaldbUtil \
-Ifunction/hxdrspUtil \
-Ifunction/hxdgradeUtil \
-Ifunction/hxdgtiFitsUtil \
-Ifunction/hxdhkFitsUtil \
-Ifunction/hxdpiUtil \
-Ifunction/hxdpiUtil_old \
-Ifunction/hxdphaUtil \
-Ifunction/hxdtableFitsUtil \
-Ifunction/hxdtrnFitsToBnkUtil \
-Ifunction/hxdtrnFitsUtil \
-Ifunction/hxdtrnpiUtil \
-Ifunction/hxdtrngradeUtil \
-Ifunction/hxdarfUtil \
-Imodule/HXD2ndbstFitsWrite \
-Imodule/HXD2ndeventFitsWrite \
-Imodule/HXD2ndeventFitsWrite_old \
-Imodule/HXD2ndsclFitsWrite \
-Imodule/HXD2ndtrnFitsWrite \
-Imodule/HXDHKFitsRead \
-Imodule/HXDHKFitsWrite \
-Imodule/HXDarf \
-Imodule/HXDbstFitsRead \
-Imodule/HXDeventFitsRead \
-Imodule/HXDfbstTime \
-Imodule/HXDfsclTime \
-Imodule/HXDftrnTime \
-Imodule/HXDfwelTime \
-Imodule/HXDgethkInit \
-Imodule/HXDgrade \
-Imodule/HXDleapsecInit \
-Imodule/HXDmkgainhist \
-Imodule/HXDmktrngainhist \
-Imodule/HXDpi \
-Imodule/HXDpi_old \
-Imodule/HXDpi/linearity_table_def \
-Imodule/HXDrndInit \
-Imodule/HXDsclFitsRead \
-Imodule/HXDtableFitsInit \
-Imodule/HXDtableFitsWrite \
-Imodule/HXDtransRPTtoeventFITS \
-Imodule/HXDtrnFitsRead \
-Imodule/HXDtrngrade \
-Imodule/HXDtrnpi \
-Imodule/HXDmktrnlc \
-Imodule/HXDmktrnspec \
-Imodule/HXDmkbstlc \
-Imodule/HXDmkbstspec \
-Imodule/HXDwambstid \
-Imodule/HXDbstJudge \
${HD_STD_CFLAGS}

HD_INSTALL_LIBRARIES	= ${HD_LIBRARY_ROOT}

HD_LIBRARY_SRC_c	= \
function/hxdFitsCommentUtil/hxdFitsCommentUtil.c \
function/hxdFitsHeaderUtil/hxdFitsHeaderUtil.c \
function/hxdFitsHeaderUtil_old/hxdFitsHeaderUtil_old.c \
function/hxdGetHKUtil/hxdGetHKUtil.c \
function/hxdTimeUtil/hxdBstTimeUtil.c \
function/hxdTimeUtil/hxdSclTimeUtil.c \
function/hxdTimeUtil/hxdTimeUtil.c \
function/hxdTimeUtil/hxdTrnTimeUtil.c \
function/hxdTimeUtil/hxdWelTimeUtil.c \
function/hxdarfUtil/hxdarfUtil.c \
function/hxdbstFitsToBnkUtil/hxdbstFitsToBnkUtil.c \
function/hxdbstFitsUtil/hxdbstFitsUtil.c \
function/hxdBstJudgeUtil/hxdBstJudgeUtil.c \
function/hxdeventFitsToBnkUtil/hxdeventFitsToBnkUtil.c \
function/hxdeventFitsUtil/hxdeventFitsUtil.c \
function/hxdcaldbUtil/hxdcaldbUtil.c \
function/hxdcaldbUtil/hxdcaldbUtil_bstidt.c \
function/hxdcaldbUtil/hxdcaldbUtil_gsoghf.c \
function/hxdcaldbUtil/hxdcaldbUtil_gsoght.c \
function/hxdcaldbUtil/hxdcaldbUtil_gsogpt.c \
function/hxdcaldbUtil/hxdcaldbUtil_gsolin.c \
function/hxdcaldbUtil/hxdcaldbUtil_pinghf.c \
function/hxdcaldbUtil/hxdcaldbUtil_pinlin.c \
function/hxdcaldbUtil/hxdcaldbUtil_pinthr.c \
function/hxdcaldbUtil/hxdcaldbUtil_gsopsd.c \
function/hxdcaldbUtil/hxdcaldbUtil_teldef.c \
function/hxdcaldbUtil/hxdcaldbUtil_wampht.c \
function/hxdcaldbUtil/hxdcaldbUtil_wamghf.c \
function/hxdcaldbUtil/hxdcaldbUtil_xxxart.c \
function/hxdrspUtil/hxdrspUtil_arf.c \
function/hxdrspUtil/hxdrspUtil_rsp.c \
function/hxdrspUtil/hxdrspUtil_rmf.c \
function/hxdgradeUtil/hxdgradeUtil.c \
function/hxdtrngradeUtil/hxdtrngradeUtil.c \
function/hxdgtiFitsUtil/hxdgtiFitsUtil.c \
function/hxdhkFitsUtil/hxdhkFitsUtil.c \
function/hxdpiUtil/hxdpiUtil.c \
function/hxdpiUtil/hxdpiUtil_gso.c \
function/hxdpiUtil/hxdpiUtil_pin.c \
function/hxdpiUtil_old/hxdpiUtil_old.c \
function/hxdpiUtil_old/hxdpiUtil_old_gso.c \
function/hxdpiUtil_old/hxdpiUtil_old_pin.c \
function/hxdphaUtil/hxdphaUtil.c \
function/hxdtableFitsUtil/hxdtableFitsUtil.c \
function/hxdtrnFitsToBnkUtil/hxdtrnFitsToBnkUtil.c \
function/hxdtrnFitsUtil/hxdtrnFitsUtil.c \
function/hxdtrnpiUtil/hxdtrnpiDEUtil.c \
function/hxdtrnpiUtil/hxdtrnpiGainUtil.c \
function/hxdtrnpiUtil/hxdtrnpiUtil.c \
module/HXD2ndbstFitsWrite/HXD2ndbstFitsWrite.c \
module/HXD2ndeventFitsWrite/HXD2ndeventFitsWrite.c \
module/HXD2ndeventFitsWrite_old/HXD2ndeventFitsWrite_old.c \
module/HXD2ndsclFitsWrite/HXD2ndsclFitsWrite.c \
module/HXD2ndtrnFitsWrite/HXD2ndtrnFitsWrite.c \
module/HXDHKFitsRead/HXDHKFitsRead.c \
module/HXDHKFitsRead/HXDHKFitsReadACU.c \
module/HXDHKFitsRead/HXDHKFitsReadAET_HC.c \
module/HXDHKFitsRead/HXDHKFitsReadAET_SC.c \
module/HXDHKFitsRead/HXDHKFitsReadDLT.c \
module/HXDHKFitsRead/HXDHKFitsReadECC_DMP.c \
module/HXDHKFitsRead/HXDHKFitsReadHK.c \
module/HXDHKFitsRead/HXDHKFitsReadIO_DMP.c \
module/HXDHKFitsRead/HXDHKFitsReadMEM_DMP.c \
module/HXDHKFitsRead/HXDHKFitsReadPPR.c \
module/HXDHKFitsRead/HXDHKFitsReadPST.c \
module/HXDHKFitsRead/HXDHKFitsReadRECC_DMP.c \
module/HXDHKFitsRead/HXDHKFitsReadRHK.c \
module/HXDHKFitsRead/HXDHKFitsReadRIO_DMP.c \
module/HXDHKFitsRead/HXDHKFitsReadSCL.c \
module/HXDHKFitsRead/HXDHKFitsReadSFC.c \
module/HXDHKFitsRead/HXDHKFitsReadSFF1.c \
module/HXDHKFitsRead/HXDHKFitsReadSFF2.c \
module/HXDHKFitsRead/HXDHKFitsReadSP_PIN.c \
module/HXDHKFitsRead/HXDHKFitsReadSP_PMT.c \
module/HXDHKFitsRead/HXDHKFitsReadSTM.c \
module/HXDHKFitsRead/HXDHKFitsReadSYS.c \
module/HXDHKFitsWrite/HXDHKFitsWrite.c \
module/HXDarf/HXDarfInit.c \
module/HXDarf/HXDarf.c \
module/HXDarf/HXDarfMerge.c \
module/HXDarf/HXDarfout.c \
module/HXDbstFitsRead/HXDbstFitsRead.c \
module/HXDeventFitsRead/HXDeventFitsRead.c \
module/HXDfbstTime/HXDfbstTime.c \
module/HXDfbstTime/HXDfbstTimeFITS.c \
module/HXDfsclTime/HXDfsclTime.c \
module/HXDfsclTime/HXDfsclTimeFITS.c \
module/HXDftrnTime/HXDftrnTime.c \
module/HXDftrnTime/HXDftrnTimeFITS.c \
module/HXDfwelTime/HXDfwelTime.c \
module/HXDfwelTime/HXDfwelTimeFITS.c \
module/HXDgethkInit/HXDgethkInit.c \
module/HXDgrade/HXDgrade.c \
module/HXDgrade/HXDgradeFITS.c \
module/HXDleapsecInit/HXDleapsecInit.c \
module/HXDmkgainhist/HXDmkgainhistWriteGHF.c \
module/HXDmkgainhist/HXDmkgainhistWritePHA.c \
module/HXDmktrngainhist/HXDmktrngainhist.c \
module/HXDpi/HXDpi.c \
module/HXDpi/HXDpiFITS.c \
module/HXDpi_old/HXDpi_old.c \
module/HXDpi_old/HXDpiFITS_old.c \
module/HXDrndInit/HXDrndInit.c \
module/HXDsclFitsRead/HXDsclFitsRead.c \
module/HXDtableFitsInit/HXDtableFitsInit.c \
module/HXDtransRPTtoeventFITS/HXDtransRPTtoeventFITS.c \
module/HXDtrnFitsRead/HXDtrnFitsRead.c \
module/HXDtrngrade/HXDtrngrade.c \
module/HXDtrngrade/HXDtrngradeFITS.c \
module/HXDtrnpi/HXDtrnpi.c \
module/HXDtrnpi/HXDtrnpiFITS.c \
module/HXDmktrnlc/HXDmktrnlc.c \
module/HXDmktrnspec/HXDmktrnspec.c \
module/HXDmkbstlc/HXDmkbstlc.c \
module/HXDwambstid/HXDwambstid.c \
module/HXDmkbstspec/HXDmkbstspec.c \
module/HXDbstJudge/HXDbstJudge.c

HD_SHLIB_LIBS		= \
${HD_LFLAGS} -lcernlib-dummy -lastetool -laste_com \
-lCLI -lBNK -l${CFITSIO} -l${PIL}

HD_CLEAN		= ${HD_LIBRARY_SRC_c:.c=.o}

include ${HD_STD_MAKEFILE}
