C*******************************************************************************
C
C Filename:    io.inc
C
C Author/Date: James Peachey, GSFC/HSTX, October 1996
C
C Description: Contains declarations for the following LOCAL variables:
C
C     errm     - standard error message string
C     subname  - string containing the name of the current subroutine
C
C Notes:       All variables must be locally initialized prior to use. No
C     initializaion may occur in this file.
C
C*******************************************************************************

      character(255) errm
      character*(*) subname
