HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= batdetmask

HD_TEST_PERL_SCRIPTS	= ut_batdetmask

HD_INSTALL_PFILES	= batdetmask.par

HD_TEST_PFILES		= ut_batdetmask.par

HD_INSTALL_HELP		= batdetmask.html

include ${HD_STD_MAKEFILE}
