HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

HD_LIBRARY_ROOT		= batmaskutils_op

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_INSTALL_LIBRARIES	= ${HD_LIBRARY_ROOT}

HD_INSTALL_HEADERS	= batdet_op.h batmask_op.h
 
HD_LIBRARY_SRC_c	= detbresimg_op.c dettop_shad.c forwmask_op.c forwdettop.c maskinit_op.c maskutils_op.c \
			  maskwtimg_op.c maskcoords_op.c \
			  maskwtcorrs_op.c detmask_op.c

include ${HD_STD_MAKEFILE}
