HD_COMPONENT_NAME	= heacore

HD_COMPONENT_VERS	=

HD_CTASK		= add_var_cols_to_types

HD_CTASK_SRC_c		= add_var_cols_to_types.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= 

HD_INSTALL_HELP		= 

include ${HD_STD_MAKEFILE}
