# Component (mission) name. Developers need not change/delete this.
HD_COMPONENT_NAME	= nustar

# Software release version number. Developers need not change/delete this.
HD_COMPONENT_VERS	=

# Perl script(s) to install.
HD_INSTALL_PERL_SCRIPTS	= nupipeline

# Help file(s) to install.
HD_INSTALL_HELP		= nupipeline.html

# Parameter file(s) to install.
HD_INSTALL_PFILES	= nupipeline.par

HD_TEST_PERL_SCRIPTS	= ut_${HD_INSTALL_PERL_SCRIPTS}_fpma ut_${HD_INSTALL_PERL_SCRIPTS}_fpmb

include ${HD_STD_MAKEFILE}
