C************************************************************
CH
CH1	SUBROUTINE CROSS(U,V,W)
CH
CH      [300,147]EOCC.FTN............10-AUG-1986
CH               VERSION 1.00         4-SEPT-1987
CH
CH2	DESCRIPTION:
CH2	THIS ROUTINE CALCULATES THE VECTOR CROSS PRODUCT OF
CH2	THE TWO INPUT VECTORS, AND RETURNS THIS VECTOR.
CH
CH3	CROSS IS CALLED AS A UTILITY ROUTINE
CH
CH4	VARIABLES USED:
CH4	A(3)	I	R*4	FIRST INPUT VECTOR
CH4	B(3)	I	R*4	SECOND INPUT VECTOR
CH4	C(3)	O	R*4	OUTPUT CROSS PRODUCT VECTOR
CH
CH5	METHOD NOTE: THIS ROUTINE ALLOWS IDENTITY BETWEEN C
CH5	AND EITHER A OR B.
CH
CH6	PROGRAMMER:	ZBARS	12DECEMBER 1977
CH
CH9*********************************************************
	SUBROUTINE CROSS(A,B,C)
	DIMENSION A(3),B(3),C(3)
C
C	PUT CROSS PRODUCT INTO TEMP LOCATION
C
	X=A(2)*B(3)-A(3)*B(2)
	Y=A(3)*B(1)-A(1)*B(3)
	Z=A(1)*B(2)-A(2)*B(1)
C
C	NOW LOAD CROSS PODUCT FOR OUTPUT
C
	C(1)=X
	C(2)=Y
	C(3)=Z
	RETURN
	END
