C**************************************************************
C
CH1   SUBROUTINE CVXYZ(RA,DEC,V)
CH
CH    [300,147]EOCC.FTN..........10-AUG-1986
CH             VERSION 1.00      04-SEPT-1987
CH
CH2   DESCRIPTION:
CH2   THIS ROUTINE CONVERTS THE DIRECTION DEFINED BY THE
CH2   INPUT RIGHT ASCENSION AND DECLINATION INTO A UNIT
CH2   VECTOR WITH COMPONENTS TAKEN ALONG X,Y,Z RESP.
CH
CH3   CVXYZ IS CALLED AS A UTILITY ROUTINE
CH
CH4   VARIABLES USED:
CH4	RA	RIGHT ASCENSION IN RADIANS
CH4	DEC	DECLINATION IN RADIANS
CH4	V(3)	OUTPUT UNIT VECTOR (X,Y,Z)
CH
CH6	PROGRAMMER:	ZBARS	12 DECEMBER 1977
CH
CH9**********************************************************
	SUBROUTINE CVXYZ(RA,DEC,V)
	DIMENSION V(3)
	V(1)=COS(RA)*COS(DEC)
	V(2)=SIN(RA)*COS(DEC)
	V(3)=SIN(DEC)
	RETURN
	END
