C***********************************************************
CH
CH1	SUBROUTINE DOT(A,B,X)
CH
CH      [300,147]EOCC.FTN..........10-AUG-1986
CH               VERSION 1.00       4-SEPT-1987
CH
CH2	DESCRIPTION: SUBROUTINE DOT CALCULATES THE VECTOR DOT
CH2	PRODUCT BETWEEN TWO INPUT VECTORS AND RETURNS THE
CH2	SCALAR.
CH
CH3	DOT IS CALLED AS A UTILITY ROUTINE
CH
CH4	VARIABLES USED:
CH4	A(3)	I	R*4	FIRST INPUT VECTOR
CH4	B(3)	I	R*4	SECOND INPUT VECTOR
CH4	X   	I	R*4	DOT PRODUCT X=A.B
CH
CH5	PROGRAMMER:	ZBARS	12DECEMBER 1977
C
CH9*********************************************************
	SUBROUTINE DOT(A,B,X)
	DIMENSION A(3),B(3)
C
	X=A(1)*B(1)+A(2)*B(2)+A(3)*B(3)
	RETURN
	END
