C       SUBROUTINE ROTAT,   ROTATE
C
C       [300,102]EFFSUB.FTN..........14-MAY-86
C                VERSION 1.00         4-SEPT-1987
C
CCCC    TYPED IN 1/22/86 BY J SWANK FROM IBM VERSION TO REPLACE 
CCCC    MISSING FORTRAN
CC
CC
      SUBROUTINE ROTAT(A,ANG,B)
C
C     ROTATES VECTOR COUNTER CLOCKWISE ABOUT Z-AXIS
C
      DIMENSION A(3),B(3)
      B(1)=A(1)*COS(ANG)-A(2)*SIN(ANG)
      B(2)=A(1)*SIN(ANG)+A(2)*COS(ANG)
      B(3)=A(3)
      RETURN
      END
