C       SUBROUTINE ROTATX,  ROTATE VECTOR ABOUT X AXIS
C
C       [300,102]EFFSUB.FTN...........14-MAY-86
C                VERSION 1.00          4-SEPT-1987
CCCC    TYPED IN 1/22/86 BY J SWANK FROM IBM VERSION TO REPLACE 
CCCC    MISSING FORTRAN
C
C
      SUBROUTINE ROTATX(A,ANG,B)
      DIMENSION A(3),B(3)
      B(2)=A(2)*COS(ANG)-A(3)*SIN(ANG)
      B(3)=A(2)*SIN(ANG)+A(3)*COS(ANG)
      B(1)=A(1)
      RETURN
      END
