HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	=

HD_SUBDIRS		= chimgtyp f2dhisto fadapt farith fboxcar fcarith \
			  fexpoadapt fgauss fim2lst fimconcat fimg2tab fimgbin \
			  fimgdmp fimgextract fimgmerge fimgpar fimgstat \
			  fimgtrim fimhisto florentz flst2im fmaskfilt \
			  fmedian fmrgmsk fparimg fregcon fsaoi fvec2img

include ${HD_STD_MAKEFILE}
