HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	=

HD_SUBDIRS		= src perl.scripts

HD_TEST_SUBDIRS		= src

HD_INSTALL_HELP		= help/heasarc.txt

HD_INSTALL_PFILES	= heasarc.par

include ${HD_STD_MAKEFILE}
