HD_COMPONENT_NAME       = hitomi

HD_COMPONENT_VERS       =

HD_INSTALL_PERL_SCRIPTS = sxspixgti.pl

HD_INSTALL_PFILES       = sxspixgti.par

HD_INSTALL_HELP         = sxspixgti.html

include ${HD_STD_MAKEFILE}

