int opFilenameGet(char *key1, char *key2, char *key3, char *filnam);
double mjd2asca(double mjd);
double asca2mjd(double asca);
double attime2asca(AtTime attime);
void asca2attime(double ascatime, AtTime *attime);
AtRotMat* ascaGetXRTrev(void);
float ea_(float *E, float *theta, float *phi);
float eef_(float *E, float *r, float *off, float *azi);
float trns_(float *E, int *idev);
float xrtea_(float *e, float *theta, float *phi, int *id);
float xrt_eff_area_(float *e_min, float *e_max, float *theta, float *phi);
float xrtpsf_(float *E, float *x1, float *y1, float *x2, float *y2);
float xrt_ea(float E, float theta, float phi);
float xrt_eff_area(float e_min, float e_max, float theta, float phi);
float xrt_eef(float E, float diameter, float theta, float phi);
float xrt_trns(float E, int idev);
float xrt_psf(float E, float x1, float y1, float x2, float y2);
void atDegToRA(double deg, AtRightAscension *ra);
void atDegToDec(double deg, AtDeclination *dec);
int atEarthElev(AtVect vSat,AtVect nvTgt,AtVect vSun,int *occlt,double elv[3]);
int ascaSatPos(double mjd, AtVect vSat);
float ascaRigidity(double mjd);
