HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

HD_CTASK		= batdph2pha

HD_CTASK_SRC_c		= batdph2pha.c 

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -lbatutils ${HD_STD_LIBS} \
			  ${SYSLIBS}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= batdph2pha.par

HD_INSTALL_HELP		= batdph2pha.html

HD_TEST_PERL_SCRIPTS    = ut_batdph2pha

HD_TEST_PFILES          = ut_batdph2pha.par

include ${HD_STD_MAKEFILE}
