HD_COMPONENT_NAME	= attitude

HD_COMPONENT_VERS	= 

HD_CTASK		= attconvert

HD_CTASK_SRC_c		= attconvert.c attconvertlib.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -lcoordfits -lcoord -lparam_wrappers ${HD_STD_LIBS} ${SYSLIBS}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= attconvert.par

HD_INSTALL_HEADERS	= 

HD_INSTALL_HELP		= attconvert.html

include ${HD_STD_MAKEFILE}
