HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

HD_INSTALL_PERL_SCRIPTS = uvotexpcorr

HD_TEST_PERL_SCRIPTS    = ut-uvotexpcorr

HD_INSTALL_PFILES	= uvotexpcorr.par

HD_TEST_PFILES          = ut-uvotexpcorr.par

HD_INSTALL_HELP		= uvotexpcorr.html

include ${HD_STD_MAKEFILE}


