HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= fappend

HD_CTASK_SRC_c		= hfappend.c

HD_CTASK_SRC_f		= fappend.f

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= fappend.par

HD_INSTALL_HELP		= fappend.hlp fappend.txt

include ${HD_STD_MAKEFILE}
