HD_COMPONENT_NAME		= heacore

HD_COMPONENT_VERS		= 

HD_INC_SUBDIR			= ape

HD_INSTALL_HEADERS		= ape_binary.h ape_error.h ape_io.h ape_list.h ape_msg.h ape_par.h ape_test.h ape_trad.h ape_util.h

include ${HD_STD_MAKEFILE}
