HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= uvotsource

HD_TEST_PERL_SCRIPTS	= ut-uvotsource

HD_INSTALL_PFILES	= uvotsource.par

HD_TEST_PFILES		= ut-uvotsource.par

HD_INSTALL_HELP		= uvotsource.html

include ${HD_STD_MAKEFILE}
