HD_COMPONENT_NAME	= heacore

HD_COMPONENT_VERS	=

HD_INSTALL_HELP         = developers_guide.dvi developers_guide.ps \
			  developers_guide fpack.txt funpack.txt \
			  ftools.txt

include ${HD_STD_MAKEFILE}
