HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= fimgbin

HD_CTASK_SRC_c		= hfimgbin.c

HD_CTASK_SRC_f		= fimgbin.f

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -lfimage${FT_VERS} \
			  ${HD_STD_LIBS} ${SYSLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= fimgbin.par

HD_INSTALL_HELP		= fimgbin.hlp fimgbin.txt

include ${HD_STD_MAKEFILE}
