HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

HD_INSTALL_PERL_SCRIPTS	= uvotscreen

HD_TEST_PERL_SCRIPTS	= ut-uvotscreen

HD_TEST_PFILES		= ut-uvotscreen.par

HD_INSTALL_PFILES	= uvotscreen.par

HD_INSTALL_HELP		= uvotscreen.html

include ${HD_STD_MAKEFILE}
