HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= chkrmf

HD_CTASK_SRC_c		= hchkrmf.c chkrmf.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= chkrmf.par

HD_INSTALL_HELP		= chkrmf.hlp chkrmf.txt

include ${HD_STD_MAKEFILE}
