HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= ascii2pha

HD_CTASK_SRC_c		= hascii2pha.c

HD_CTASK_SRC_f		= ascii2pha.f

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= ascii2pha.par

HD_INSTALL_HELP		= ascii2pha.hlp ascii2pha.txt

include ${HD_STD_MAKEFILE}
