HD_COMPONENT_NAME	= heagen

HD_COMPONENT_VERS	=

HD_CTASK		= rebingausslc

HD_CTASK_SRC_c		= rebingausslc.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_LFLAGS} ${HD_STD_LIBS} ${SYSLIBS}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= rebingausslc.par

HD_INSTALL_HELP		= rebingausslc.html

HD_TEST_PERL_SCRIPTS    = ut_rebingausslc

HD_TEST_PFILES          = ut_rebingausslc.par

include ${HD_STD_MAKEFILE}

