HD_COMPONENT_NAME	= Xspec

HD_COMPONENT_VERS	= 

HD_LIBRARY_ROOT		= XSFunctions

HD_LIBRARY_SRC_cxx	= agauss.cxx apec.cxx Aped.cxx bapec.cxx brokenPowerLaw.cxx \
			  broken2PowerLaw.cxx btapec.cxx bvapec.cxx bvtapec.cxx \
			  bvvapec.cxx bvvtapec.cxx calc_xscat.cxx \
			  calcLines.cxx calcMultiTempPlasma.cxx carbatm.cxx \
			  cplinear.cxx \
			  cutoffPowerLaw.cxx functionMap.cxx PartialCovering.cxx \
			  powerLaw.cxx simpl.cxx trns.cxx funcWrappers.cxx \
			  r1mach.cxx cemVMekal.cxx cflux.cxx clumin.cxx \
			  clcmek.cxx continua.cxx cpflux.cxx equil.cxx \
			  gaussianLine.cxx gaussianAbsorptionLine.cxx \
			  gaussDem.cxx hatm.cxx gnei.cxx IonizedOpacity.cxx ireflct.cxx \
			  kdblur.cxx kdblur2.cxx kerrbb.cxx \
			  kerrdisk.cxx laor2.cxx IonBalNei.cxx \
			  lorentzianLine.cxx KBcalcNEISpectrum.cxx meka.cxx mekal.cxx \
			  MZCompRefl.cxx nei.cxx NeutralOpacity.cxx \
			  nlapec.cxx npshock.cxx nthcomp.cxx pflbol.cxx pfltmp.cxx \
			  pileup.cxx pshock.cxx raysmith.cxx rdblur.cxx rnei.cxx \
			  reflct.cxx rfxconv.cxx sedov.cxx sirf.cxx snapec.cxx \
		          spinconv.cxx sumdem.cxx \
			  superExpCutoff.cxx tapec.cxx tbabs.cxx tbfeo.cxx tbgas.cxx \
			  tbgrain.cxx tbpcf.cxx tbrel.cxx \
			  tbvabs.cxx vapec.cxx vashift.cxx vgaussDem.cxx vequil.cxx \
			  vmeka.cxx vmekal.cxx vgnei.cxx vmshift.cxx vnei.cxx \
			  vnpshock.cxx voigtLine.cxx vraysmith.cxx vpshock.cxx \
			  vrnei.cxx vsedov.cxx vtapec.cxx vvapec.cxx vvgnei.cxx \
			  vvnei.cxx vvnpshock.cxx vvpshock.cxx vvrnei.cxx \
			  vvsedov.cxx vvtapec.cxx \
			  WarmAbsorber.cxx xilconv.cxx xsbexrav.cxx \
			  xsbexriv.cxx xscat_init.cxx xscatmodel.cxx xscflw.cxx \
			  xscompps.cxx xscompth.cxx \
			  xseqpair.cxx xseqth.cxx xsgsmt.cxx xslaor.cxx xslsmt.cxx \
			  xsmaug.cxx xsmkcf.cxx \
			  xsnteea.cxx xspexrav.cxx xspexriv.cxx xspwab.cxx \
			  xsvmcf.cxx xszgau.cxx zagauss.cxx zashift.cxx \
			  zmshift.cxx ztbabs.cxx

HD_LIBRARY_SRC_c	= exsource.c ismatten.c rgsxsrc.c tbnew.c xscompmag.c \
			  xscomptb.c numeric.c xslimbb.c xszbabs.c

HD_LIBRARY_SRC_f	= acisabs.f atdata.f bb.f bbm.f \
			  c6mekl.f c6pmekl.f c6pvmkl.f c6vmekl.f cemekl.f \
			  clnfln.f compbb.f compls.f compps.f \
			  compst.f cont.f disk.f diskir.f diskm.f disko.f diskpbb.f \
			  dogsmt.f dokdblur.f dokdisk.f dolsmt.f donthcomp.f \
			  dopwab.f dordblur.f \
			  dospinconv.f dotbvabs.f eplogpar.f eqpairsubs.f erebin.f \
	 		  ezdiskbb.f fbg.f fespecs.f fmekal.f gaunt.f \
			  gphoto.f grad.f inibin.f kdblur2i.f kummr.f \
			  laorsb.f ldpfil.f laorsb2.f logpar.f meksub.f msldst.f mszdst.f \
			  nei1tspec.f nsa.f nsagrav.f nsatmos.f \
			  nsmax.f nsmaxg.f nsx.f optxagn.f optxagnf.f pexmon.f \
			  phfit2.f photo.f runkbb.f \
			  spin.f srcut.f sresc.f \
			  swind1.f tamma.f taufunc.f therm.f \
			  xredge.f xsabsc.f xsabsp.f \
			  xsabsv.f xsabsw.f xsaped.f \
			  xsbape.f xsbbrd.f xsblbd.f xsbmc.f \
			  xsbrms.f xsbrmv.f xsbvpe.f xsbvvp.f xscabs.f \
			  xscnst.f xscred.f xscycl.f xsdili.f \
			  xsdiskpn.f xsdskb.f xsdust.f xsedge.f \
			  xsexp.f xsftop.f xsgaul.f xsgrbm.f \
			  xshecu.f xshrfl.f xslorz.f xslyman.f xsmeka.f xsmekl.f \
			  xsntch.f xsnteeasb.f xsp1tr.f xspegp.f xsphab.f xsphei.f \
			  xsplab.f xsposm.f xsrays.f xsred.f \
			  xsrefsch.f xssmdg.f xsspln.f xssssi.f xsstep.f \
			  xstitg.f xsvape.f xsvcfl.f xsvmek.f \
			  xsvmkl.f xsvphb.f xsvrys.f xsvvap.f xswnab.f xsxirf.f \
			  xsxpdec.f xszabp.f xszabs.f xszbod.f xszbrm.f \
			  xszcrd.f xszedg.f xszhcu.f xszphb.f xszvab.f \
			  xszvfe.f xszvph.f xszwnb.f zigm.f zxipcf.f

HD_LIBRARY_SRC_f90	= ismabs.f90

HD_CXXFLAGS		= -I${HD_SRC}/src \
			  -I${HD_SRC}/src/main -I${HD_SRC}/src/include \
			  -I${HD_SRC}/src/XSFit \
			  -I${HD_SRC}/src/XSFit/FitMethod \
			  -I${HD_SRC}/src/XSFunctions \
			  -I${HD_SRC}/src/xslib -I${HD_SRC}/src/XSModel \
			  -I${HD_SRC}/src/XSModel/Model \
			  -I${HD_SRC}/src/XSPlot -I${HD_SRC}/src/XSUser \
			  -I${HD_SRC}/src/XSUtil ${HD_STD_CXXFLAGS} \
			  -DINXSPEC

HD_CFLAGS               = -I${HD_SRC}/src \
			  -I${HD_SRC}/src/main -I${HD_SRC}/src/include \
			  -I${HD_SRC}/src/XSUtil ${HD_STD_CFLAGS}

HD_FFLAGS		= -I${HD_SRC}/src \
			  -I${HD_SRC}/src/main -I${HD_SRC}/src/include \
			  -I${HD_SRC}/src/XSFit -I${HD_SRC}/src/XSFunctions \
			  -I${HD_SRC}/src/xslib -I${HD_SRC}/src/XSModel \
			  -I${HD_SRC}/src/XSPlot -I${HD_SRC}/src/XSUser \
			  -I${HD_SRC}/src/XSUtil ${HD_STD_FFLAGS}

HD_INSTALL_LIBRARIES	= ${HD_LIBRARY_ROOT}

HD_INSTALL_HEADERS	= Aped.h IonBalNei.h IonizedOpacity.h MZCompRefl.h \
			  NeutralOpacity.h \
			  exsource.h fephoto.h functionMap.h nephoto.h numeric.h \
			  ophoto.h trns.h funcWrappers.h stlToCArrays.h \
			  xscat.h xslimbb.h

HD_CLEAN		= ${HD_LIBRARY_SRC_cxx:.cxx=.o} \
			  ${HD_LIBRARY_SRC_c:.c=.o} \
			  ${HD_LIBRARY_SRC_f:.f=.o}

HD_SHLIB_LIBS		= ${HD_LFLAGS} -lXSModel -lXSUtil -lXS -l${WCSLIB} \
			  -l${CCFITS} -l${CFITSIO} ${SYSLIBS} ${F77LIBS4C}

include ${HD_STD_MAKEFILE}
