HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= fbbft2pha

HD_CTASK_SRC_c		= hfbbft2pha.c

HD_CTASK_SRC_f		= fbbft2pha.f

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -lgro${FT_VERS} \
			  ${HD_STD_LIBS} ${SYSLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= fbbft2pha.par

HD_INSTALL_HELP		= fbbft2pha.hlp fbbft2pha.txt

include ${HD_STD_MAKEFILE}
