HD_COMPONENT_NAME	= heatools

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= ftcoco

HD_TEST_PERL_SCRIPTS	= ut_ftcoco

HD_INSTALL_PFILES	= ftcoco.par

HD_TEST_PFILES		= ut_ftcoco.par

HD_INSTALL_HELP		= ftcoco.html

include ${HD_STD_MAKEFILE}
