HD_COMPONENT_NAME	= heacore

HD_COMPONENT_VERS	= 

HD_CTASK		= pcheck

HD_CTASK_SRC_c		= pcheck.c

HD_CFLAGS		= -I. -I.. -I../../include ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -l${PIL} -l${READLINE} ${SYSLIBS}

HD_INSTALL_TASKS	= ${HD_CTASK}

include ${HD_STD_MAKEFILE}
