# SimASTE_XRTOUTtoDET.make

SimASTE_XRTOUTtoDET_DIR = $(ASTE_MODULE_DIR)/SimASTE_XRTOUTtoDET/2.2
SimASTE_XRTOUTtoDET = SimASTE_XRTOUTtoDET.o

SimASTE_XRTOUTtoDET.o: $(SimASTE_XRTOUTtoDET_DIR)/SimASTE_XRTOUTtoDET.c
	$(CC) $(CFLAGS) $(ANLCFLAGS) -c $(SimASTE_XRTOUTtoDET_DIR)/SimASTE_XRTOUTtoDET.c
