HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	=

HD_SUBDIRS		= barytime bcmppha bcont bod2pha bod2rmf bodfluxhis \
			  bodgetvp bpulsarspec eaddmap econvpha econvrmf \
			  emapgen fbbft2pha fbdrm2rmf fesdb2rdf fevpbtoa \
			  groview intmap like specmat

include ${HD_STD_MAKEFILE}
