# SimASTE_ECStoXRTIN.make

SimASTE_ECStoXRTIN_DIR = $(ASTE_MODULE_DIR)/SimASTE_ECStoXRTIN/2.3
SimASTE_ECStoXRTIN = SimASTE_ECStoXRTIN.o

SimASTE_ECStoXRTIN.o: $(SimASTE_ECStoXRTIN_DIR)/SimASTE_ECStoXRTIN.c
	$(CC) -I$(SimASTE_Root_DIR) $(CFLAGS) $(ANLCFLAGS) -c $(SimASTE_ECStoXRTIN_DIR)/SimASTE_ECStoXRTIN.c
