HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= fbdrm2rmf

HD_CTASK_SRC_c		= hfbdrm2rmf.c

HD_CTASK_SRC_f		= fbdrm2rmf.f

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -lgro${FT_VERS} \
			  ${HD_STD_LIBS} ${SYSLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= fbdrm2rmf.par

HD_INSTALL_HELP		= fbdrm2rmf.hlp fbdrm2rmf.txt

include ${HD_STD_MAKEFILE}
