HD_COMPONENT_NAME	= attitude

HD_COMPONENT_VERS	= 

HD_CTASK		= minnow

HD_CTASK_SRC_c		= minnow.c split.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -lrew -lcoordfits -lcoord ${HD_STD_LIBS} ${SYSLIBS}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= minnow.par

HD_INSTALL_HELP		= minnow.html

include ${HD_STD_MAKEFILE}
