HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_CTASK		= uvotconvreg

HD_CTASK_SRC_c		= uvotconvreg.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

TASK_LIBS		= -lrew -l${HEAUTILS}

HD_CLIBS		= ${HD_LFLAGS} ${TASK_LIBS} ${HD_STD_LIBS} ${SYSLIBS}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= uvotconvreg.par

HD_INSTALL_HELP		= uvotconvreg.html

HD_TEST_PERL_SCRIPTS	= ut-uvotconvreg

HD_TEST_PFILES		= ut-uvotconvreg.par

include ${HD_STD_MAKEFILE}
