

FFLAGS= $(FCOPTS)
OFILES= cubspl4.o difsys4.o draw.o galac.o gdraw.o gridx.o \
	grid.o gridmp.o gridrnd.o gridlab.o meridien.o parallele.o \
	plcurv.o lever_x.o rad2det.o relocate.o \
	curvil.o curfun.o arcsin.o arccos.o \
	abs_to_rel.o rel_to_abs.o setrem.o setpro.o \
	gal_equ.o equ_gal.o

compile: ${OFILES}

LIB: $(OFILES)
	liball $(XANBIN)/lib/libximage.a

.f.o :
	xfor $*


.SUFFIXES : .f
