HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= uvotshiftpha

HD_TEST_PERL_SCRIPTS	= ut-uvotshiftpha

HD_INSTALL_PFILES	= uvotshiftpha.par

HD_TEST_PFILES		= ut-uvotshiftpha.par

HD_INSTALL_HELP		= uvotshiftpha.html

include ${HD_STD_MAKEFILE}
