#!/bin/sh
echo "The FV GUI is not currently supported under Cygwin."
echo "Please visit http://heasarc.gsfc.nasa.gov/docs/software/lheasoft/ftools/fv/"
echo "to download the latest version of FV for use on Windows platforms."
