#makefile for lib.xhelp
#oday - 2 Sept 92
FCOMPL =
FCOPTS =
FLOPTS =
XANLIB = 
PGPLOT =
SYSLIB =
XANAME = xanhigh

#use xhelpsub.vms for machines that default for fortran carriage control
OFILES= chtobl.o fndtop.o gtxhlp.o ichbeg.o opnche.o rdche.o rdpag.o \
	shfdoc.o shxhlp.o smatch.o tyxhlp.o wrtpag.o wrttop.o \
	xhelpsub.o

LIB: $(OFILES)
	liball $(XANBIN)/lib/$(XANAME).a

compile: $(OFILES)

clean :
	rm -f *.o *.s *~


.f.o:
	xfor $*
