#!/usr/bin/perl
#
#  ut_nucalcpos_fpma
#
#
#
# Changes:
#      0.1.0 : NS 07/07/2011 - First Release
#      0.1.1 : NS 02/08/2011 - Added 'inpsdfilecorr' input parameter
#      0.1.2 : NS 06/10/2011 - Added 'alignfile' and 'mastaspectfile' input parameters
#      0.1.3 : NS 30/11/2011 - Removed input parameters for metrology processing
#
#

use strict;
use ut_nustar;



# main
{
# Object Istances
    my $ut = ut_nustar->new(
			    name    => "nucalcpos",
			    utname  => "ut_nucalcpos_fpma",
			    version => "0.1.3",
			    );
    
# Set Parameter
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
    
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_nucalcpos";  
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/NUSTAR_L1_CPT_threshold_2_EVENTS_FPMA.fits",
		   "$input/$ArchDir/mastaspect_fpma.fits",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_nucalcpos_fpma.evt",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("nucalcpos","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;

# Task Files Check
    my %par_task = (

		    infile         => "$input/$ArchDir/NUSTAR_L1_CPT_threshold_2_EVENTS_FPMA.fits",
		    outfile        => "$output/out_nucalcpos_fpma.evt",
		    pixposfile     => "CALDB",
		    saveraw2coord  => "no",
		    initseed       => "yes",
		    mastaspectfile => "$input/$ArchDir/mastaspect_fpma.fits",
		    chatter        => $chat,
		    clobber        => "$clobber",
		    history        => "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/out_nucalcpos_fpma.evt");
	
# ftdiff
	$ut->ftdiff("$output/out_nucalcpos_fpma.evt",
		    "$input/$ArchDir/ut_nucalcpos_fpma.evt");

    }
    
    $ut->delete();
}

