*
* $Id: d506dp.inc,v 1.1.1.1 2003/11/25 22:45:44 dorman Exp $
*
* $Log: d506dp.inc,v $
* Revision 1.1.1.1  2003/11/25 22:45:44  dorman
* Xspec12.0 Export Version 11-25-2003
*
* Revision 7.0  2002/07/12 16:03:09  dorman
*
* version number change
*
* Revision 1.1  2002/06/26 14:52:05  dorman
*
*
* minuit library
*
* Revision 1.1  2001/12/28 02:53:58  kaa
* Added MINUIT source code.
*
* Revision 1.1.1.1  1996/03/07 14:31:32  mclareni
* Minuit
*
*
*
* d506dp.inc
*
C ************ DOUBLE PRECISION VERSION *************
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)

