HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

HD_CTASK		= uvottfc1

HD_CTASK_SRC_c		= uvottfc1.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

TASK_LIBS			= -luvotcal -lswuvot -lrew
HD_CLIBS		= ${HD_LFLAGS} ${TASK_LIBS} ${HD_STD_LIBS} ${SYSLIBS}

HD_INSTALL_TASKS		= ${HD_CTASK}

HD_TEST_PERL_SCRIPTS    = ut-uvottfc

HD_TEST_PFILES		= ut-uvottfc.par

HD_INSTALL_PERL_SCRIPTS	= uvottfc

HD_INSTALL_PFILES	= uvottfc.par uvottfc1.par

HD_INSTALL_HELP		= uvottfc.html

include ${HD_STD_MAKEFILE}

