#!/usr/bin/perl
#
#  ut_nucalcsaa_fpma
#
#
#
# Changes:
#      0.1.0 : NS 02/10/2012 - First Release

#
#

use strict;
use ut_nustar;



# main
{
# Object Istances
    my $ut = ut_nustar->new(
			    name    => "nucalcsaa",
			    utname  => "ut_nucalcsaa_fpma",
			    version => "0.1.0",
			    );
    
# Set Parameter
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
    
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_nucalcsaa";  
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/nu10002014001A_uf.evt.gz",
		   "$input/$ArchDir/nu10002014001A_fpm.hk.gz",
		   "$input/$ArchDir/nu10002014001_orb.fits.gz",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = (
		    "$input/$ArchDir/ut_nucalcsaa_fpma.hk",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("nucalcsaa","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;

# Task Files Check
    my %par_task = (
		    evtfile        => "$input/$ArchDir/nu10002014001A_uf.evt.gz",
		    hkfile         => "$input/$ArchDir/nu10002014001A_fpm.hk.gz",
		    orbitfile      => "$input/$ArchDir/nu10002014001_orb.fits.gz",
		    outfile        => "$output/out_nucalcsaa_fpma.hk",
		    chatter        => $chat,
		    clobber        => "$clobber",
		    history        => "yes", 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/out_nucalcsaa_fpma.hk");
	
	
# ftdiff
	$ut->ftdiff("$output/out_nucalcsaa_fpma.hk",
		    "$input/$ArchDir/ut_nucalcsaa_fpma.hk");

    }
    
    $ut->delete();
}

