#!/usr/bin/perl
#
#  ut_nufilter_fpma
#
#
#
# Changes:
#      0.1.0 : NS 24/10/2011 - First Release
#      0.1.1 - NS 17/04/2012 - Added 'psdcorfile' input parameter
#      0.1.2 - NS 27/07/2012 - Dataset changed
#      0.1.3 - NS 19/10/2012 - Added new input parameters needed by 'prefilter'
#      0.1.4 - NS 06/11/2012 - Replaced 'ftdiff' call with 'ftdiff2'
#
#

use strict;
use ut_nustar;


# main
{
# Object Istances
    my $ut = ut_nustar->new(
			    name    => "nufilter",
			    utname  => "ut_nufilter_fpma",
			    version => "0.1.4",
			    );
    
# Set Parameter
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
    
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $headas =$ENV{'HEADAS'};
    my $ArchDir="ut_nufilter";
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/nu00015011001A_fpm.hk",
		   "$input/$ArchDir/nu00015011001_ceb.hk",
                   "$input/$ArchDir/nu00015011001_att.fits",
                   "$input/$ArchDir/nu00015011001_orb.fits",
                   "$input/$ArchDir/nu00015011001_psdcorr.fits",
		   "$headas/refdata/leapsec.fits",
		   "$headas/refdata/rigidity.data",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_nufilter_fpma.mkf",
		    "$input/$ArchDir/ut_nufilter_fpma.attorb",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("nufilter","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;

# Task Files Check
    my %par_task = (
		    hkfile         =>  "$input/$ArchDir/nu00015011001A_fpm.hk",
		    cebhkfile      =>  "$input/$ArchDir/nu00015011001_ceb.hk",
		    attfile        =>  "$input/$ArchDir/nu00015011001_att.fits",
		    orbitfile      =>  "$input/$ArchDir/nu00015011001_orb.fits",
		    psdcorfile     =>  "$input/$ArchDir/nu00015011001_psdcorr.fits",
		    outdir         =>  $output,
		    teldef         =>  "CALDB",
		    attorbfile     =>  "DEFAULT",
		    preconfigfile  =>  "CALDB",
		    tlemode        =>  "TLE_TEXT2",
		    tlefile        =>  "$input/$ArchDir/NuSTAR_TLE_ARCHIVE.txt",
		    leapfile       =>  "$headas/refdata/leapsec.fits",
		    rigfile        =>  "$headas/refdata/rigidity.data",
		    origin         =>  "NASA/GSFC",
		    interval       =>  1,
		    pntra          =>  188.266,
		    pntdec         =>  1.879,
		    mkfconfigfile  =>  "CALDB",
		    mkffile        =>  "DEFAULT",
		    nonulls        => "no",
		    gtiexpr        => "NONE",
		    chatter     =>  $chat,
		    clobber     =>  "$clobber",
		    history     =>  "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/nu00015011001A.mkf");
	$ut->fverify("$output/nu00015011001A.attorb");	
	
# ftdiff
	$ut->ftdiff2("$output/nu00015011001A.mkf",
		    "$input/$ArchDir/ut_nufilter_fpma.mkf", 0.05);

	$ut->ftdiff2("$output/nu00015011001A.attorb",
		    "$input/$ArchDir/ut_nufilter_fpma.attorb", 0.05);

    }    
    
    $ut->delete();
}

