HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= c_caldbinfo

HD_CTASK_SRC_c		= hc_caldbinfo.c c_caldbinfo.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= c_caldbinfo.par

HD_INSTALL_HELP		= c_caldbinfo.hlp c_caldbinfo.txt

include ${HD_STD_MAKEFILE}
