HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= batupdatephakw

HD_TEST_PERL_SCRIPTS	= ut_batupdatephakw ut_batupdatephakw1

HD_INSTALL_PFILES	= batupdatephakw.par

HD_TEST_PFILES		= ut_batupdatephakw.par

HD_INSTALL_HELP		= batupdatephakw.html

include ${HD_STD_MAKEFILE}
