#!/usr/bin/perl
#
#  ut_nuflagevt_fpma
#
#
#
# Changes:
#      0.1.0 : NS 12/07/2012 - First Release
#
#

use strict;
use ut_nustar;



# main
{
# Object Istances
    my $ut = ut_nustar->new(
			    name    => "nuflagevt",
			    utname  => "ut_nuflagevt_fpma",
			    version => "0.1.0",
			    );
    
# Set Parameter
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
    
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_nuflagevt";  
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/nu10010001001A_uf.evt",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_nuflagevt_fpma.evt",
		    );

    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("nuflagevt","ftdiff","fverify", "pquery2");

    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;

# Task Files Check
    my %par_task = (

		    infile        =>  "$input/$ArchDir/nu10010001001A_uf.evt",
		    outfile       =>  "$output/out_nuflagevt_fpma.evt",
		    depthcutfile  =>  "CALDB",
		    evtcutfile    =>  "CALDB",
		    chatter       =>  $chat,
		    clobber       =>  "$clobber",
		    history       =>  "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/out_nuflagevt_fpma.evt");
	
	
# ftdiff
	$ut->ftdiff("$output/out_nuflagevt_fpma.evt",
		    "$input/$ArchDir/ut_nuflagevt_fpma.evt");
    }    
    
    $ut->delete();
}

