#!/usr/bin/perl
#
#  ut_nulccorr_fpmb
#
#
#
# Changes:
#      0.1.0 : NS 18/10/2012 - First Release
#      0.1.1 : NS 06/06/2013 - Handle PSF and EXPOSURE correction
#      0.1.2 - NS 10/07/2013 - Added new input parameters
#      0.1.3 - NS 31/03/2014 - Added new input parameters
#
#

use strict;
use ut_nustar;



# main
{
# Object Istances
    my $ut = ut_nustar->new(
			    name    => "nulccorr",
			    utname  => "ut_nulccorr_fpmb",
			    version => "0.1.3",
			    );
    
# Set Parameter
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
    
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_nulccorr";  
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/nu00015011001B01_sr.lc.gz",
		   "$input/$ArchDir/nu00015011001B_fpm.hk.gz",
		   "$input/$ArchDir/nu00015011001B01_cl.evt.gz",
		   "$input/$ArchDir/nu00015011001B_det1.fits",
		   "$input/$ArchDir/nu00015011001B_oa.fits",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_nulccorr_fpmb.lc",
		    "$input/$ArchDir/ut_skyinstr_fpmb.fits",
		    "$input/$ArchDir/ut_corrpsf_fpmb.fits",
		    );

    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("nulccorr","ftdiff","fverify", "pquery2");

    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;

# Task Files Check
    my %par_task = (
		    lcfile         =>  "$input/$ArchDir/nu00015011001B01_sr.lc.gz",
		    hkfile         =>  "$input/$ArchDir/nu00015011001B_fpm.hk.gz",
		    outlcfile      =>  "$output/out_nulccorr_fpmb.lc",
		    infile         =>  "$input/$ArchDir/nu00015011001B01_cl.evt.gz",
		    inskyinstrfile    => "NONE",
		    inaspecthistofile => "NONE",
		    pixposfile     => "CALDB",
		    alignfile      => "CALDB",
		    mastaspectfile => "$input/$ArchDir/nu00015011001_mast.fits",
		    attfile        => "$input/$ArchDir/nu00015011001_att.fits",
		    teldef         => "CALDB",
		    instrprobmapfile => "CALDB",
		    psffile        => "CALDB",
		    vignfile       => "CALDB",
		    aberration     => "no",
		    vignflag       => "no",
		    energy         =>  10,
		    det1reffile    => "$input/$ArchDir/nu00015011001B_det1.fits",
		    optaxisfile    => "$input/$ArchDir/nu00015011001B_oa.fits",
		    pixbin         =>  100,
		    cutmaps        => "yes",
		    boxsize        => 10,
		    percent        => 0.02,
		    skyinstrfile   => "$output/out_skyinstr_fpmb.fits",
		    initseed       => "yes",
		    extended       => "no",
		    corrfile       => "$output/out_corrpsf_fpmb.fits",
		    psfflag        => "yes",
		    chatter        =>  $chat,
		    clobber        =>  "$clobber",
		    history        =>  "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/out_nulccorr_fpmb.lc");
	$ut->fverify("$output/out_skyinstr_fpmb.fits");
	$ut->fverify("$output/out_corrpsf_fpmb.fits");	
	
# ftdiff
	$ut->ftdiff("$output/out_nulccorr_fpmb.lc",
		    "$input/$ArchDir/ut_nulccorr_fpmb.lc");

	$ut->ftdiff("$output/out_skyinstr_fpmb.fits",
		    "$input/$ArchDir/ut_skyinstr_fpmb.fits");

	$ut->ftdiff("$output/out_corrpsf_fpmb.fits",
		    "$input/$ArchDir/ut_corrpsf_fpmb.fits");

    }    
    
    $ut->delete();
}

