HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= gisxspec makeregion make2region pspcxspec \
			  selectxrange wgaxspec acisxspec \
			  binFactorSelect displayOnPow pileest

HD_INSTALL_PFILES	= gisxspec.par makeregion.par make2region.par \
			  pspcxspec.par selectxrange.par wgaxspec.par \
                          acisxspec.par binFactorSelect.par displayOnPow.par \
			  pileest.par

HD_INSTALL_HELP		= gisxspec.html gisxspec_1.html \
			  gti_faq.html makeregion.html \
			  make2region.html make2region_1.html \
			  make2region_2.html make2region_3.html \
			  pspcxspec.html pspcxspec_1.html \
			  selectxrange.html selectxrange_1.html \
			  timeselect.html wgaxspec_1.html \
                          acisxspec.html acisxspec_1.html \
			  longrunningtime_warning.html \
			  pileest.html

#			  gisxspec.txt makeregion.txt make2region.txt \
			  pspcxspec.txt selectxrange.txt

include ${HD_STD_MAKEFILE}
