HD_COMPONENT_NAME		= hitomi

HD_COMPONENT_VERS		= 


HD_SUBDIRS			= sxssamcnt sxsflagpix mxstime mxsgti sxssecid sxsgain sxspha2pi sxspixgti sxsregext sxsrmf sxsanticopi sxsanticolc sxsbranch sxsmkrmf sxsseccor sxsperseus sxsextend

HD_TEST_SUBDIRS			=

include ${HD_STD_MAKEFILE}
