HD_COMPONENT_NAME	= attitude

HD_COMPONENT_VERS	= 

HD_CTASK		= combinexform

HD_CTASK_SRC_c		= combinexform.c commands.c param.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -lcoordfits -lcoord -lparam_wrappers ${HD_STD_LIBS} ${SYSLIBS}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= combinexform.par

HD_INSTALL_HELP		= combinexform.html


include ${HD_STD_MAKEFILE}
