HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	=

HD_SUBDIRS		= common include perl.scripts xselflib src/xselect \
			  xseltlib src/xseltcl src/xseltk

HD_INSTALL_HELP		= xselect.txt

include ${HD_STD_MAKEFILE}
