HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= xsel_f2c.pl xsl_asca_gis_makeresp \
			  xsl_asca_sis_makeresp xsl_chandra_acis_makeresp \
			  xsl_einstein_ipc_makeresp xsl_filter_intensity \
			  xsl_mkf_or_hk_bin xsl_rosat_hri_makeresp \
			  xsl_rosat_pspc_makeresp xsl_suzaku_xis_makeresp \
			  xsl_suzaku_xis_rebinspec xsl_xmm_add_badpix_exposu \
			  xsl_xmm_epic_makeresp

include ${HD_STD_MAKEFILE}
