#! /usr/bin/perl 
$version ="1.10";
$date  ="2002-11-28";
$author = "kaa";

# This script makes the ASCA SIS rmf and arf. It is run by the xselect
# routine xsl_rspsav.

# Check that we were given an input filename

if(@ARGV < 1 || @ARGV > 2)
{
    print "\n usage : xsl_asca_sis_makeresp infile extended?\n";
    exit(0);
}

$infile  = $ARGV[0];
$extended = "no";
if(@ARGV == 2 && $ARGV[1] eq "yes") {
   $extended = "yes";
}

$dot = index($infile,".");
$rootname = substr($infile, 0, $dot);

$rmffile = $rootname . ".rmf";
$arffile = $rootname . ".arf";

# run sisrmg to make the rmf

$command = "sisrmg infile=$infile rmfile=$rmffile arfile=NONE";
print "\n",$command,"\n\n";
system($command);


# run ascaarf to make the arf

if ($extended eq "yes") {
   $command = "ascaarf phafile=$infile rmffile=$rmffile outfile=$arffile point=no";
} else {
   $command = "ascaarf phafile=$infile rmffile=$rmffile outfile=$arffile point=yes simple=yes";
}
print "\n",$command,"\n\n";
system($command);


# set the RESPFILE and ANCRFILE keywords in the spectrum to point to the
# files that have been created

$command = "fparkey value=$rmffile fitsfile=$infile\[SPECTRUM\] keyword=RESPFILE";
system($command);
$command = "fparkey value=$arffile fitsfile=$infile\[SPECTRUM\] keyword=ANCRFILE";
system($command);



