HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= batsurvey-gti batsurvey-detmask \
			  batsurvey-aspect batsurvey-erebin \
			  batsurvey-catmux \
			  batsurvey

HD_TEST_PERL_SCRIPTS	= ut_batsurvey ut_batsurvey-catmux

HD_INSTALL_PFILES	= batsurvey-gti.par batsurvey-detmask.par \
			  batsurvey-aspect.par batsurvey-erebin.par \
			  batsurvey-catmux.par \
			  batsurvey.par

HD_TEST_PFILES		= ut_batsurvey.par ut_batsurvey-catmux.par

HD_INSTALL_HELP		= batsurvey.html batsurvey-aspect.html \
			  batsurvey-detmask.html batsurvey-erebin.html \
			  batsurvey-catmux.html \
			  batsurvey-gti.html

include ${HD_STD_MAKEFILE}
