HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= c_crtcif

HD_CTASK_SRC_c		= hc_crtcif.c c_crtcif.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= c_crtcif.par

HD_INSTALL_HELP		= c_crtcif.hlp c_crtcif.txt

include ${HD_STD_MAKEFILE}
