HD_COMPONENT_NAME	= attitude

HD_COMPONENT_VERS	=

HD_INSTALL_PERL_LIBS	= CatalogLoader.pm Catalog.pm HierTriMesh.pm \
			  Partition.pm SearchCat.pm Source.pm SourceTable.pm \
			  SquareRADec.pm UserCat.pm

HD_PERL_SUBDIR		= StarID

HD_INSTALL_HEADERS	=

include ${HD_STD_MAKEFILE}
