HD_COMPONENT_NAME       = hitomi

HD_COMPONENT_VERS       =

HD_INSTALL_PERL_SCRIPTS = sxsanticolc.pl

HD_INSTALL_PFILES       = sxsanticolc.par

HD_INSTALL_HELP         = sxsanticolc.html

include ${HD_STD_MAKEFILE}

