C   include file : IGENL.INC
C
CC  defines common constants
C
C************************ IFORM VERSION 1.1 ****************************
C
CA  author : KOD               date: 2-APR-1990 13:40
C
C   general description:
CG  trigonometric constants in double precision (real*8)
C
C   include_var.               description
CP  DPI                        pi
CP  D2PI                       2.0 * pi
CP  DPID2                      pi / 2.0
CP  DPI180                     pi / 180.0
CP  D180PI                     180.0 / pi
C
C***********************************************************************
C
      REAL*8        DPI, D2PI, DPID2, DPI180, D180PI
C
      PARAMETER ( DPI    =  3.14159265358979D0 )
      PARAMETER ( D2PI   =  6.28318530717959D0 )
      PARAMETER ( DPID2  =  1.57079632679490D0 )
      PARAMETER ( DPI180 =  0.0174532925199433D0 )
      PARAMETER ( D180PI =  57.2957795130823D0 )
C

