HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= batoccultgti

HD_TEST_PERL_SCRIPTS	= ut_batoccultgti

HD_INSTALL_PFILES	= batoccultgti.par

HD_TEST_PFILES		= ut_batoccultgti.par

HD_INSTALL_HELP		= batoccultgti.html

include ${HD_STD_MAKEFILE}
