HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_LIBRARY_ROOT		= ${CFTOOLSLIB}

HD_LIB_STYLE		= ${HD_LIB_STYLE_F77}

HD_LIBRARY_SRC_c	= c_fcecho.c c_fcerr.c c_fcpars.c c_gtaskn.c \
			  c_ptaskn.c c_timestamp.c c_trimstr.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_INSTALL_LIBRARIES	= ${HD_LIBRARY_ROOT}

HD_INSTALL_HEADERS	= cftools.h
# cftools_internal.h

include ${HD_STD_MAKEFILE}
