HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

HD_TEST_PERL_SCRIPTS    = ut-uvotunicorr

HD_TEST_PFILES		= ut-uvotunicorr.par

HD_INSTALL_PERL_SCRIPTS	= uvotunicorr

HD_INSTALL_PFILES	= uvotunicorr.par

HD_INSTALL_HELP		= uvotunicorr.html

include ${HD_STD_MAKEFILE}

