/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /headas/headas/ftools/xanlib/xpi/xanadul.c,v 3.6 1996/11/11 20:19:28 miket Exp $
 */

#define FLEX_SCANNER
#define ZA_FLEX_MAJOR_VERSION 2
#define ZA_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define ZA_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define ZA_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define ZA_USE_PROTOS
#define ZA_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define ZA_USE_CONST
#define ZA_USE_PROTOS
#endif

#ifdef ZA_USE_CONST
#define zaconst const
#else
#define zaconst
#endif


#ifdef ZA_USE_PROTOS
#define ZA_PROTO(proto) proto
#else
#define ZA_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define ZA_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define ZA_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN za_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The ZASTATE alias is for lex
 * compatibility.
 */
#define ZA_START ((za_start - 1) / 2)
#define ZASTATE ZA_START

/* Action number for EOF rule of a given start state. */
#define ZA_STATE_EOF(state) (ZA_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define ZA_NEW_FILE zarestart( zain )

#define ZA_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define ZA_BUF_SIZE 16384

typedef struct za_buffer_state *ZA_BUFFER_STATE;

extern int zaleng;
extern FILE *zain, *zaout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		zaless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the zaless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define zaless(n) \
	do \
		{ \
		/* Undo effects of setting up zatext. */ \
		*za_cp = za_hold_char; \
		za_c_buf_p = za_cp = za_bp + n - ZA_MORE_ADJ; \
		ZA_DO_BEFORE_ACTION; /* set up zatext again */ \
		} \
	while ( 0 )

#define unput(c) zaunput( c, zatext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int za_size_t;


struct za_buffer_state
	{
	FILE *za_input_file;

	char *za_ch_buf;		/* input buffer */
	char *za_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	za_size_t za_buf_size;

	/* Number of characters read into za_ch_buf, not including EOB
	 * characters.
	 */
	int za_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int za_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int za_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int za_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int za_fill_buffer;

	int za_buffer_status;
#define ZA_BUFFER_NEW 0
#define ZA_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as ZA_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via zarestart()), so that the user can continue scanning by
	 * just pointing zain at a new input file.
	 */
#define ZA_BUFFER_EOF_PENDING 2
	};

static ZA_BUFFER_STATE za_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define ZA_CURRENT_BUFFER za_current_buffer


/* za_hold_char holds the character lost when zatext is formed. */
static char za_hold_char;

static int za_n_chars;		/* number of characters read into za_ch_buf */


int zaleng;

/* Points to current character in buffer. */
static char *za_c_buf_p = (char *) 0;
static int za_init = 1;		/* whether we need to initialize */
static int za_start = 0;	/* start state number */

/* Flag which is used to allow zawrap()'s to do buffer switches
 * instead of setting up a fresh zain.  A bit of a hack ...
 */
static int za_did_buffer_switch_on_eof;

void zarestart ZA_PROTO(( FILE *input_file ));

void za_switch_to_buffer ZA_PROTO(( ZA_BUFFER_STATE new_buffer ));
void za_load_buffer_state ZA_PROTO(( void ));
ZA_BUFFER_STATE za_create_buffer ZA_PROTO(( FILE *file, int size ));
void za_delete_buffer ZA_PROTO(( ZA_BUFFER_STATE b ));
void za_init_buffer ZA_PROTO(( ZA_BUFFER_STATE b, FILE *file ));
void za_flush_buffer ZA_PROTO(( ZA_BUFFER_STATE b ));
#define ZA_FLUSH_BUFFER za_flush_buffer( za_current_buffer )

ZA_BUFFER_STATE za_scan_buffer ZA_PROTO(( char *base, za_size_t size ));
ZA_BUFFER_STATE za_scan_string ZA_PROTO(( zaconst char *str ));
ZA_BUFFER_STATE za_scan_bytes ZA_PROTO(( zaconst char *bytes, int len ));

static void *za_flex_alloc ZA_PROTO(( za_size_t ));
static void *za_flex_realloc ZA_PROTO(( void *, za_size_t ));
static void za_flex_free ZA_PROTO(( void * ));

#define za_new_buffer za_create_buffer

#define za_set_interactive(is_interactive) \
	{ \
	if ( ! za_current_buffer ) \
		za_current_buffer = za_create_buffer( zain, ZA_BUF_SIZE ); \
	za_current_buffer->za_is_interactive = is_interactive; \
	}

#define za_set_bol(at_bol) \
	{ \
	if ( ! za_current_buffer ) \
		za_current_buffer = za_create_buffer( zain, ZA_BUF_SIZE ); \
	za_current_buffer->za_at_bol = at_bol; \
	}

#define ZA_AT_BOL() (za_current_buffer->za_at_bol)

typedef unsigned char ZA_CHAR;
FILE *zain = (FILE *) 0, *zaout = (FILE *) 0;
typedef int za_state_type;
extern char *zatext;
#define zatext_ptr zatext

static za_state_type za_get_previous_state ZA_PROTO(( void ));
static za_state_type za_try_NUL_trans ZA_PROTO(( za_state_type current_state ));
static int za_get_next_buffer ZA_PROTO(( void ));
static void za_fatal_error ZA_PROTO(( zaconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up zatext.
 */
#define ZA_DO_BEFORE_ACTION \
	zatext_ptr = za_bp; \
	zaleng = (int) (za_cp - za_bp); \
	za_hold_char = *za_cp; \
	*za_cp = '\0'; \
	za_c_buf_p = za_cp;

#define ZA_NUM_RULES 16
#define ZA_END_OF_BUFFER 17
static zaconst short int za_accept[41] =
    {   0,
        0,    0,   17,   16,   10,   14,   16,   16,    3,    3,
       15,    3,    3,    3,   12,    4,    3,    3,    0,   11,
        0,    9,    3,    3,    3,    3,    3,    3,    3,    1,
        2,    3,    3,    2,    3,    3,    3,    3,    3,    0
    } ;

static zaconst int za_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    6,    6,    1,    1,    1,
        1,    7,    8,    9,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    7,   14,    1,
       15,    1,   16,   17,   18,   18,   18,   18,   19,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
        6,    7,    7,    1,    7,    1,   18,   18,   18,   18,

       19,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static zaconst int za_meta[20] =
    {   0,
        1,    1,    1,    1,    1,    2,    2,    2,    1,    2,
        2,    2,    2,    2,    1,    2,    3,    2,    2
    } ;

static zaconst short int za_base[45] =
    {   0,
        0,    0,   40,   97,   97,   97,   31,   18,   17,   28,
       97,   35,   14,   47,   97,   97,   15,   57,   28,   97,
       27,   97,   25,    0,   36,    0,   12,    0,   63,   24,
       75,    0,    0,   31,    0,   39,   40,   43,   50,   97,
       88,   91,   93,   19
    } ;

static zaconst short int za_def[45] =
    {   0,
       40,    1,   40,   40,   40,   40,   41,   42,   43,   43,
       40,   10,   10,   10,   40,   40,   10,   14,   41,   40,
       42,   40,   10,   44,   10,   12,   10,   12,   12,   12,
       29,   14,   18,   12,   31,   12,   12,   12,   12,    0,
       40,   40,   40,   40
    } ;

static zaconst short int za_nxt[117] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,   10,   11,   10,
       12,   13,   14,   15,   16,   17,    9,   18,   18,   22,
       24,   35,   22,   24,   23,   23,   23,   23,   22,   20,
       24,   22,   20,   25,   24,   23,   23,   23,   26,   40,
       27,   24,   23,   23,   25,   23,   23,   28,   23,   23,
       40,   37,   37,   29,   30,   39,   31,   23,   23,   32,
       40,   23,   39,   40,   33,   33,   34,   23,   23,   33,
       36,   40,   36,   40,   40,   37,   40,   40,   40,   40,
       40,   23,   38,   40,   38,   40,   40,   39,   19,   19,
       19,   21,   21,   21,   23,   23,    3,   40,   40,   40,

       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40
    } ;

static zaconst short int za_chk[117] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    8,
       44,   27,    8,    9,   13,   17,   13,   17,   21,   19,
        9,   21,    7,    9,   10,   23,   30,   23,   10,    3,
       10,   10,   30,   34,   10,   12,   25,   12,   25,   34,
        0,   36,   37,   12,   14,   38,   14,   36,   37,   14,
        0,   38,   39,    0,   14,   14,   18,   18,   39,   18,
       29,    0,   29,    0,    0,   29,    0,    0,    0,    0,
        0,   29,   31,    0,   31,    0,    0,   31,   41,   41,
       41,   42,   42,   42,   43,   43,   40,   40,   40,   40,

       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40
    } ;

static za_state_type za_last_accepting_state;
static char *za_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define zamore() zamore_used_but_not_detected
#define ZA_MORE_ADJ 0
char *zatext;
#line 1 "xanadul.l"
#define INITIAL 0
#line 2 "xanadul.l"

/* 
   08Nov96 MJT
   Brought in soc_read from old flex.skel (which is
   incompatible with present versions of flex)
*/

#include "cfortran.h"

PROTOCCALLSFFUN2 (INT,GTBUFC,gtbufc,PSTRING,INT)
#define GTBUFC(buffer,nbytes) CCALLSFFUN2(GTBUFC,gtbufc,PSTRING,INT,buffer,nbytes);
#define PROMPTC(buffer) CCALLSFSUB1(PROMPTC,promptc,PSTRING,buffer);
#define YCAPLINE(buffer) CCALLSFSUB1(YCAPLINE,ycapline,PSTRING,buffer);

static sock_chan = 0;
soc_read (fd, buf, nbyte)
     int fd;
     char *buf;
     int nbyte;
{
  int n;
  int n1;

/* See if we have stacked commands */

  if (0 != (n = stackcmd(buf,nbyte)))
    {
      YCAPLINE(buf);
      return (n);
    }
  
#ifdef vms
  if (!sock_chan) sock_chan = sockchan();
#else
  sock_chan = 0;
#endif

  /* Do we have a saved string to read? */
  if (0 != (n = xpistr(buf)))
    {
      /* We got a string and are done */
    } 
  else
    {
      if (sock_chan)
	{
#ifdef vms
	  PROMPTC("This is ignored");
#ifdef MULTINET
	  n = socket_read(sock_chan,buf,nbyte);
#else
	  puts ("You built this without multinet support");
	  puts ("Please rebuild with multinet support");
	  puts ("Something like cc/define=multinet xanadul");
	  puts ("should work");
#endif
#else
	  puts("Opps, this shouldn't happen!  It think's it's VMS");
#endif
	} 
      else 
	{
	  n = GTBUFC(buf,nbyte);
	  /*		n = read(fd,buf,nbyte);
	   */
	}
    }

  stackcmdcap(buf);
  n1 = stackcmd(buf,nbyte);
  
  YCAPLINE(buf);
  if (n != -1) n = n1;
  
  return (n);
}

/* gets input and stuffs it into "buf".  number of characters read, or ZA_NULL,
 * is returned in "result".
 */
#include "y_tab.h"
#define ZA_INPUT(buf,result,max_size) \
        if ( (result = soc_read( fileno(zain), (char *) buf, max_size )) < 0 ) \
            ZA_FATAL_ERROR( " "/*"read() in flex scanner failed" */);
#define ZA_NULL 0

/* cont      "-\n" */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef ZA_SKIP_ZAWRAP
#ifdef __cplusplus
extern "C" int zawrap ZA_PROTO(( void ));
#else
extern int zawrap ZA_PROTO(( void ));
#endif
#endif

#ifndef ZA_NO_UNPUT
static void zaunput ZA_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef zatext_ptr
static void za_flex_strncpy ZA_PROTO(( char *, zaconst char *, int ));
#endif

#ifndef ZA_NO_INPUT
#ifdef __cplusplus
static int zainput ZA_PROTO(( void ));
#else
static int input ZA_PROTO(( void ));
#endif
#endif

#if ZA_STACK_USED
static int za_start_stack_ptr = 0;
static int za_start_stack_depth = 0;
static int *za_start_stack = 0;
#ifndef ZA_NO_PUSH_STATE
static void za_push_state ZA_PROTO(( int new_state ));
#endif
#ifndef ZA_NO_POP_STATE
static void za_pop_state ZA_PROTO(( void ));
#endif
#ifndef ZA_NO_TOP_STATE
static int za_top_state ZA_PROTO(( void ));
#endif

#else
#define ZA_NO_PUSH_STATE 1
#define ZA_NO_POP_STATE 1
#define ZA_NO_TOP_STATE 1
#endif

#ifdef ZA_MALLOC_DECL
ZA_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef ZA_READ_BUF_SIZE
#define ZA_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( zatext, zaleng, 1, zaout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or ZA_NULL,
 * is returned in "result".
 */
#ifndef ZA_INPUT
#define ZA_INPUT(buf,result,max_size) \
	if ( za_current_buffer->za_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( zain )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( zain ) ) \
			ZA_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, zain )) == 0) \
		  && ferror( zain ) ) \
		ZA_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "zaterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef zaterminate
#define zaterminate() return ZA_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef ZA_START_STACK_INCR
#define ZA_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef ZA_FATAL_ERROR
#define ZA_FATAL_ERROR(msg) za_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef ZA_DECL
#define ZA_DECL int zalex ZA_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after zatext and zaleng
 * have been set up.
 */
#ifndef ZA_USER_ACTION
#define ZA_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef ZA_BREAK
#define ZA_BREAK break;
#endif

#define ZA_RULE_SETUP \
	ZA_USER_ACTION

ZA_DECL
	{
	register za_state_type za_current_state;
	register char *za_cp, *za_bp;
	register int za_act;

#line 105 "xanadul.l"


	if ( za_init )
		{
		za_init = 0;

#ifdef ZA_USER_INIT
		ZA_USER_INIT;
#endif

		if ( ! za_start )
			za_start = 1;	/* first start state */

		if ( ! zain )
			zain = stdin;

		if ( ! zaout )
			zaout = stdout;

		if ( ! za_current_buffer )
			za_current_buffer =
				za_create_buffer( zain, ZA_BUF_SIZE );

		za_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		za_cp = za_c_buf_p;

		/* Support of zatext. */
		*za_cp = za_hold_char;

		/* za_bp points to the position in za_ch_buf of the start of
		 * the current run.
		 */
		za_bp = za_cp;

		za_current_state = za_start;
za_match:
		do
			{
			register ZA_CHAR za_c = za_ec[ZA_SC_TO_UI(*za_cp)];
			if ( za_accept[za_current_state] )
				{
				za_last_accepting_state = za_current_state;
				za_last_accepting_cpos = za_cp;
				}
			while ( za_chk[za_base[za_current_state] + za_c] != za_current_state )
				{
				za_current_state = (int) za_def[za_current_state];
				if ( za_current_state >= 41 )
					za_c = za_meta[(unsigned int) za_c];
				}
			za_current_state = za_nxt[za_base[za_current_state] + (unsigned int) za_c];
			++za_cp;
			}
		while ( za_base[za_current_state] != 97 );

za_find_action:
		za_act = za_accept[za_current_state];
		if ( za_act == 0 )
			{ /* have to back up */
			za_cp = za_last_accepting_cpos;
			za_current_state = za_last_accepting_state;
			za_act = za_accept[za_current_state];
			}

		ZA_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( za_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of ZA_DO_BEFORE_ACTION */
			*za_cp = za_hold_char;
			za_cp = za_last_accepting_cpos;
			za_current_state = za_last_accepting_state;
			goto za_find_action;

case 1:
ZA_RULE_SETUP
#line 106 "xanadul.l"
{
                                     /* printf("Lex xantokon %s. ",zatext);*/
                                     zalval.value = zatext;
                                     return (PARAMON);
                                   }
	ZA_BREAK
case 2:
ZA_RULE_SETUP
#line 111 "xanadul.l"
{
                                     /* printf("Lex xantokoff %s. ",zatext);*/
                                     zalval.value = zatext;
                                     return (PARAMOFF);
                                   }
	ZA_BREAK
case 3:
ZA_RULE_SETUP
#line 116 "xanadul.l"
{
                                     /* printf("Lex ParPart %s. ",zatext); */
                                     zalval.value = zatext;
                                     return (PARAM);
                                   }
	ZA_BREAK
case 4:
ZA_RULE_SETUP
#line 121 "xanadul.l"
{
                                     /* printf("Lex Equals %s. ",zatext); */
                                     zalval.value = zatext;
                                     return (EQUALS);
                                   }
	ZA_BREAK
case 5:
ZA_RULE_SETUP
#line 126 "xanadul.l"
{
                                     /* printf("Lex question %s. ",zatext);  */
                                     zalval.value = zatext;
                                     return (QUESTION);
                                   }
	ZA_BREAK
case 6:
ZA_RULE_SETUP
#line 131 "xanadul.l"
{
                                     /* printf("Lex Integer %s. ",zatext); */
                                     zalval.value = zatext;
                                     return INTEGER;
                                   }
	ZA_BREAK
case 7:
ZA_RULE_SETUP
#line 136 "xanadul.l"
{
                                     /* printf("Lex Integer %s. ",zatext); */
                                     zalval.value = zatext;
                                     return IRANGE; 
                                   }
	ZA_BREAK
case 8:
ZA_RULE_SETUP
#line 141 "xanadul.l"
{
                                     /* printf("Lex Real %s. ",zatext); */
                                     zalval.value = zatext;
                                     return REAL;
                                   }
	ZA_BREAK
case 9:
ZA_RULE_SETUP
#line 146 "xanadul.l"
{
                                     /* printf("Lex String %s. ",zatext); */
                                     zalval.value = zatext;
                                     return STRING;
                                   }
	ZA_BREAK
case 10:
ZA_RULE_SETUP
#line 151 "xanadul.l"
{
                                     extern int lineno;
                                     lineno++; 
				     zalval.value = "\n";
				     return NL;
				   }
	ZA_BREAK
case 11:
ZA_RULE_SETUP
#line 157 "xanadul.l"
{
                                     extern int lineno;
                                     lineno++; 
				     zalval.value = "\n";
				     return NL;
				   }
	ZA_BREAK
case 12:
ZA_RULE_SETUP
#line 163 "xanadul.l"
{
                                     zalval.value = ";";
                                     return SEMICOLON;
                                   }
	ZA_BREAK
case 13:
ZA_RULE_SETUP
#line 167 "xanadul.l"
{
                                     zalval.value = "/";
                                     return SLASH;
                                   }
	ZA_BREAK
case 14:
ZA_RULE_SETUP
#line 171 "xanadul.l"
{
/*                                     zalval.value = " ";
                                     return SPACE;
*/
                                   }
	ZA_BREAK
case 15:
ZA_RULE_SETUP
#line 176 "xanadul.l"
{
                                     zalval.value = ",";
                                     return COMMA;
                                   }
	ZA_BREAK
case ZA_STATE_EOF(INITIAL):
#line 180 "xanadul.l"
{
                                     printf ("Lex EOF");
                                     zalval.value = "\004";
				     return ENDOFFILE;
				   }
	ZA_BREAK
case 16:
ZA_RULE_SETUP
#line 185 "xanadul.l"
ECHO;
	ZA_BREAK

	case ZA_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int za_amount_of_matched_text = (int) (za_cp - zatext_ptr) - 1;

		/* Undo the effects of ZA_DO_BEFORE_ACTION. */
		*za_cp = za_hold_char;

		if ( za_current_buffer->za_buffer_status == ZA_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed zain at a new source and called
			 * zalex().  If so, then we have to assure
			 * consistency between za_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			za_n_chars = za_current_buffer->za_n_chars;
			za_current_buffer->za_input_file = zain;
			za_current_buffer->za_buffer_status = ZA_BUFFER_NORMAL;
			}

		/* Note that here we test for za_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since za_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( za_c_buf_p <= &za_current_buffer->za_ch_buf[za_n_chars] )
			{ /* This was really a NUL. */
			za_state_type za_next_state;

			za_c_buf_p = zatext_ptr + za_amount_of_matched_text;

			za_current_state = za_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * za_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			za_next_state = za_try_NUL_trans( za_current_state );

			za_bp = zatext_ptr + ZA_MORE_ADJ;

			if ( za_next_state )
				{
				/* Consume the NUL. */
				za_cp = ++za_c_buf_p;
				za_current_state = za_next_state;
				goto za_match;
				}

			else
				{
				za_cp = za_c_buf_p;
				goto za_find_action;
				}
			}

		else switch ( za_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				za_did_buffer_switch_on_eof = 0;

				if ( zawrap() )
					{
					/* Note: because we've taken care in
					 * za_get_next_buffer() to have set up
					 * zatext, we can now set up
					 * za_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * ZA_NULL, it'll still work - another
					 * ZA_NULL will get returned.
					 */
					za_c_buf_p = zatext_ptr + ZA_MORE_ADJ;

					za_act = ZA_STATE_EOF(ZA_START);
					goto do_action;
					}

				else
					{
					if ( ! za_did_buffer_switch_on_eof )
						ZA_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				za_c_buf_p =
					zatext_ptr + za_amount_of_matched_text;

				za_current_state = za_get_previous_state();

				za_cp = za_c_buf_p;
				za_bp = zatext_ptr + ZA_MORE_ADJ;
				goto za_match;

			case EOB_ACT_LAST_MATCH:
				za_c_buf_p =
				&za_current_buffer->za_ch_buf[za_n_chars];

				za_current_state = za_get_previous_state();

				za_cp = za_c_buf_p;
				za_bp = zatext_ptr + ZA_MORE_ADJ;
				goto za_find_action;
			}
		break;
		}

	default:
		ZA_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of zalex */


/* za_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int za_get_next_buffer()
	{
	register char *dest = za_current_buffer->za_ch_buf;
	register char *source = zatext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( za_c_buf_p > &za_current_buffer->za_ch_buf[za_n_chars + 1] )
		ZA_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( za_current_buffer->za_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( za_c_buf_p - zatext_ptr - ZA_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (za_c_buf_p - zatext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( za_current_buffer->za_buffer_status == ZA_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		za_n_chars = 0;

	else
		{
		int num_to_read =
			za_current_buffer->za_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef ZA_USES_REJECT
			ZA_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			ZA_BUFFER_STATE b = za_current_buffer;

			int za_c_buf_p_offset =
				(int) (za_c_buf_p - b->za_ch_buf);

			if ( b->za_is_our_buffer )
				{
				int new_size = b->za_buf_size * 2;

				if ( new_size <= 0 )
					b->za_buf_size += b->za_buf_size / 8;
				else
					b->za_buf_size *= 2;

				b->za_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					za_flex_realloc( (void *) b->za_ch_buf,
							 b->za_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->za_ch_buf = 0;

			if ( ! b->za_ch_buf )
				ZA_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			za_c_buf_p = &b->za_ch_buf[za_c_buf_p_offset];

			num_to_read = za_current_buffer->za_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > ZA_READ_BUF_SIZE )
			num_to_read = ZA_READ_BUF_SIZE;

		/* Read in more data. */
		ZA_INPUT( (&za_current_buffer->za_ch_buf[number_to_move]),
			za_n_chars, num_to_read );
		}

	if ( za_n_chars == 0 )
		{
		if ( number_to_move == ZA_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			zarestart( zain );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			za_current_buffer->za_buffer_status =
				ZA_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	za_n_chars += number_to_move;
	za_current_buffer->za_ch_buf[za_n_chars] = ZA_END_OF_BUFFER_CHAR;
	za_current_buffer->za_ch_buf[za_n_chars + 1] = ZA_END_OF_BUFFER_CHAR;

	zatext_ptr = &za_current_buffer->za_ch_buf[0];

	return ret_val;
	}


/* za_get_previous_state - get the state just before the EOB char was reached */

static za_state_type za_get_previous_state()
	{
	register za_state_type za_current_state;
	register char *za_cp;

	za_current_state = za_start;

	for ( za_cp = zatext_ptr + ZA_MORE_ADJ; za_cp < za_c_buf_p; ++za_cp )
		{
		register ZA_CHAR za_c = (*za_cp ? za_ec[ZA_SC_TO_UI(*za_cp)] : 1);
		if ( za_accept[za_current_state] )
			{
			za_last_accepting_state = za_current_state;
			za_last_accepting_cpos = za_cp;
			}
		while ( za_chk[za_base[za_current_state] + za_c] != za_current_state )
			{
			za_current_state = (int) za_def[za_current_state];
			if ( za_current_state >= 41 )
				za_c = za_meta[(unsigned int) za_c];
			}
		za_current_state = za_nxt[za_base[za_current_state] + (unsigned int) za_c];
		}

	return za_current_state;
	}


/* za_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = za_try_NUL_trans( current_state );
 */

#ifdef ZA_USE_PROTOS
static za_state_type za_try_NUL_trans( za_state_type za_current_state )
#else
static za_state_type za_try_NUL_trans( za_current_state )
za_state_type za_current_state;
#endif
	{
	register int za_is_jam;
	register char *za_cp = za_c_buf_p;

	register ZA_CHAR za_c = 1;
	if ( za_accept[za_current_state] )
		{
		za_last_accepting_state = za_current_state;
		za_last_accepting_cpos = za_cp;
		}
	while ( za_chk[za_base[za_current_state] + za_c] != za_current_state )
		{
		za_current_state = (int) za_def[za_current_state];
		if ( za_current_state >= 41 )
			za_c = za_meta[(unsigned int) za_c];
		}
	za_current_state = za_nxt[za_base[za_current_state] + (unsigned int) za_c];
	za_is_jam = (za_current_state == 40);

	return za_is_jam ? 0 : za_current_state;
	}


#ifndef ZA_NO_UNPUT
#ifdef ZA_USE_PROTOS
static void zaunput( int c, register char *za_bp )
#else
static void zaunput( c, za_bp )
int c;
register char *za_bp;
#endif
	{
	register char *za_cp = za_c_buf_p;

	/* undo effects of setting up zatext */
	*za_cp = za_hold_char;

	if ( za_cp < za_current_buffer->za_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = za_n_chars + 2;
		register char *dest = &za_current_buffer->za_ch_buf[
					za_current_buffer->za_buf_size + 2];
		register char *source =
				&za_current_buffer->za_ch_buf[number_to_move];

		while ( source > za_current_buffer->za_ch_buf )
			*--dest = *--source;

		za_cp += (int) (dest - source);
		za_bp += (int) (dest - source);
		za_n_chars = za_current_buffer->za_buf_size;

		if ( za_cp < za_current_buffer->za_ch_buf + 2 )
			ZA_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--za_cp = (char) c;


	zatext_ptr = za_bp;
	za_hold_char = *za_cp;
	za_c_buf_p = za_cp;
	}
#endif	/* ifndef ZA_NO_UNPUT */


#ifdef __cplusplus
static int zainput()
#else
static int input()
#endif
	{
	int c;

	*za_c_buf_p = za_hold_char;

	if ( *za_c_buf_p == ZA_END_OF_BUFFER_CHAR )
		{
		/* za_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( za_c_buf_p < &za_current_buffer->za_ch_buf[za_n_chars] )
			/* This was really a NUL. */
			*za_c_buf_p = '\0';

		else
			{ /* need more input */
			zatext_ptr = za_c_buf_p;
			++za_c_buf_p;

			switch ( za_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( zawrap() )
						{
						za_c_buf_p =
						zatext_ptr + ZA_MORE_ADJ;
						return EOF;
						}

					if ( ! za_did_buffer_switch_on_eof )
						ZA_NEW_FILE;
#ifdef __cplusplus
					return zainput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					za_c_buf_p = zatext_ptr + ZA_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					ZA_FATAL_ERROR(
					"unexpected last match in zainput()" );
#else
					ZA_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) za_c_buf_p;	/* cast for 8-bit char's */
	*za_c_buf_p = '\0';	/* preserve zatext */
	za_hold_char = *++za_c_buf_p;


	return c;
	}


#ifdef ZA_USE_PROTOS
void zarestart( FILE *input_file )
#else
void zarestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! za_current_buffer )
		za_current_buffer = za_create_buffer( zain, ZA_BUF_SIZE );

	za_init_buffer( za_current_buffer, input_file );
	za_load_buffer_state();
	}


#ifdef ZA_USE_PROTOS
void za_switch_to_buffer( ZA_BUFFER_STATE new_buffer )
#else
void za_switch_to_buffer( new_buffer )
ZA_BUFFER_STATE new_buffer;
#endif
	{
	if ( za_current_buffer == new_buffer )
		return;

	if ( za_current_buffer )
		{
		/* Flush out information for old buffer. */
		*za_c_buf_p = za_hold_char;
		za_current_buffer->za_buf_pos = za_c_buf_p;
		za_current_buffer->za_n_chars = za_n_chars;
		}

	za_current_buffer = new_buffer;
	za_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (zawrap()) processing, but the only time this flag
	 * is looked at is after zawrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	za_did_buffer_switch_on_eof = 1;
	}


#ifdef ZA_USE_PROTOS
void za_load_buffer_state( void )
#else
void za_load_buffer_state()
#endif
	{
	za_n_chars = za_current_buffer->za_n_chars;
	zatext_ptr = za_c_buf_p = za_current_buffer->za_buf_pos;
	zain = za_current_buffer->za_input_file;
	za_hold_char = *za_c_buf_p;
	}


#ifdef ZA_USE_PROTOS
ZA_BUFFER_STATE za_create_buffer( FILE *file, int size )
#else
ZA_BUFFER_STATE za_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	ZA_BUFFER_STATE b;

	b = (ZA_BUFFER_STATE) za_flex_alloc( sizeof( struct za_buffer_state ) );
	if ( ! b )
		ZA_FATAL_ERROR( "out of dynamic memory in za_create_buffer()" );

	b->za_buf_size = size;

	/* za_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->za_ch_buf = (char *) za_flex_alloc( b->za_buf_size + 2 );
	if ( ! b->za_ch_buf )
		ZA_FATAL_ERROR( "out of dynamic memory in za_create_buffer()" );

	b->za_is_our_buffer = 1;

	za_init_buffer( b, file );

	return b;
	}


#ifdef ZA_USE_PROTOS
void za_delete_buffer( ZA_BUFFER_STATE b )
#else
void za_delete_buffer( b )
ZA_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == za_current_buffer )
		za_current_buffer = (ZA_BUFFER_STATE) 0;

	if ( b->za_is_our_buffer )
		za_flex_free( (void *) b->za_ch_buf );

	za_flex_free( (void *) b );
	}


#ifndef ZA_ALWAYS_INTERACTIVE
#ifndef ZA_NEVER_INTERACTIVE
extern int isatty ZA_PROTO(( int ));
#endif
#endif

#ifdef ZA_USE_PROTOS
void za_init_buffer( ZA_BUFFER_STATE b, FILE *file )
#else
void za_init_buffer( b, file )
ZA_BUFFER_STATE b;
FILE *file;
#endif


	{
	za_flush_buffer( b );

	b->za_input_file = file;
	b->za_fill_buffer = 1;

#if ZA_ALWAYS_INTERACTIVE
	b->za_is_interactive = 1;
#else
#if ZA_NEVER_INTERACTIVE
	b->za_is_interactive = 0;
#else
	b->za_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef ZA_USE_PROTOS
void za_flush_buffer( ZA_BUFFER_STATE b )
#else
void za_flush_buffer( b )
ZA_BUFFER_STATE b;
#endif

	{
	b->za_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->za_ch_buf[0] = ZA_END_OF_BUFFER_CHAR;
	b->za_ch_buf[1] = ZA_END_OF_BUFFER_CHAR;

	b->za_buf_pos = &b->za_ch_buf[0];

	b->za_at_bol = 1;
	b->za_buffer_status = ZA_BUFFER_NEW;

	if ( b == za_current_buffer )
		za_load_buffer_state();
	}


#ifndef ZA_NO_SCAN_BUFFER
#ifdef ZA_USE_PROTOS
ZA_BUFFER_STATE za_scan_buffer( char *base, za_size_t size )
#else
ZA_BUFFER_STATE za_scan_buffer( base, size )
char *base;
za_size_t size;
#endif
	{
	ZA_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != ZA_END_OF_BUFFER_CHAR ||
	     base[size-1] != ZA_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (ZA_BUFFER_STATE) za_flex_alloc( sizeof( struct za_buffer_state ) );
	if ( ! b )
		ZA_FATAL_ERROR( "out of dynamic memory in za_scan_buffer()" );

	b->za_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->za_buf_pos = b->za_ch_buf = base;
	b->za_is_our_buffer = 0;
	b->za_input_file = 0;
	b->za_n_chars = b->za_buf_size;
	b->za_is_interactive = 0;
	b->za_at_bol = 1;
	b->za_fill_buffer = 0;
	b->za_buffer_status = ZA_BUFFER_NEW;

	za_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef ZA_NO_SCAN_STRING
#ifdef ZA_USE_PROTOS
ZA_BUFFER_STATE za_scan_string( zaconst char *str )
#else
ZA_BUFFER_STATE za_scan_string( str )
zaconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return za_scan_bytes( str, len );
	}
#endif


#ifndef ZA_NO_SCAN_BYTES
#ifdef ZA_USE_PROTOS
ZA_BUFFER_STATE za_scan_bytes( zaconst char *bytes, int len )
#else
ZA_BUFFER_STATE za_scan_bytes( bytes, len )
zaconst char *bytes;
int len;
#endif
	{
	ZA_BUFFER_STATE b;
	char *buf;
	za_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) za_flex_alloc( n );
	if ( ! buf )
		ZA_FATAL_ERROR( "out of dynamic memory in za_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = ZA_END_OF_BUFFER_CHAR;

	b = za_scan_buffer( buf, n );
	if ( ! b )
		ZA_FATAL_ERROR( "bad buffer in za_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->za_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef ZA_NO_PUSH_STATE
#ifdef ZA_USE_PROTOS
static void za_push_state( int new_state )
#else
static void za_push_state( new_state )
int new_state;
#endif
	{
	if ( za_start_stack_ptr >= za_start_stack_depth )
		{
		za_size_t new_size;

		za_start_stack_depth += ZA_START_STACK_INCR;
		new_size = za_start_stack_depth * sizeof( int );

		if ( ! za_start_stack )
			za_start_stack = (int *) za_flex_alloc( new_size );

		else
			za_start_stack = (int *) za_flex_realloc(
					(void *) za_start_stack, new_size );

		if ( ! za_start_stack )
			ZA_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	za_start_stack[za_start_stack_ptr++] = ZA_START;

	BEGIN(new_state);
	}
#endif


#ifndef ZA_NO_POP_STATE
static void za_pop_state()
	{
	if ( --za_start_stack_ptr < 0 )
		ZA_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(za_start_stack[za_start_stack_ptr]);
	}
#endif


#ifndef ZA_NO_TOP_STATE
static int za_top_state()
	{
	return za_start_stack[za_start_stack_ptr - 1];
	}
#endif

#ifndef ZA_EXIT_FAILURE
#define ZA_EXIT_FAILURE 2
#endif

#ifdef ZA_USE_PROTOS
static void za_fatal_error( zaconst char msg[] )
#else
static void za_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( ZA_EXIT_FAILURE );
	}



/* Redefine zaless() so it works in section 3 code. */

#undef zaless
#define zaless(n) \
	do \
		{ \
		/* Undo effects of setting up zatext. */ \
		zatext[zaleng] = za_hold_char; \
		za_c_buf_p = zatext + n - ZA_MORE_ADJ; \
		za_hold_char = *za_c_buf_p; \
		*za_c_buf_p = '\0'; \
		zaleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef zatext_ptr
#ifdef ZA_USE_PROTOS
static void za_flex_strncpy( char *s1, zaconst char *s2, int n )
#else
static void za_flex_strncpy( s1, s2, n )
char *s1;
zaconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef ZA_USE_PROTOS
static void *za_flex_alloc( za_size_t size )
#else
static void *za_flex_alloc( size )
za_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef ZA_USE_PROTOS
static void *za_flex_realloc( void *ptr, za_size_t size )
#else
static void *za_flex_realloc( ptr, size )
void *ptr;
za_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef ZA_USE_PROTOS
static void za_flex_free( void *ptr )
#else
static void za_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if ZA_MAIN
int main()
	{
	zalex();
	return 0;
	}
#endif
#line 185 "xanadul.l"


int zawrap()
{
  /* MJT -- 08 Nov 1996
     Supplied for compatibility with
     pre-2.5.1 versions of flex which
     do not recognize %option nozawrap 
  */
  return(1);
}
