HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= fimhisto

HD_CTASK_SRC_c		= hfimhisto.c fimhisto.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -lfimage${FT_VERS} \
			  ${HD_STD_LIBS} ${SYSLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= fimhisto.par

HD_INSTALL_HELP		= fimhisto.hlp fimhisto.txt

include ${HD_STD_MAKEFILE}
