HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

HD_TEST_PERL_SCRIPTS	= ut-uvotimggen

HD_INSTALL_PERL_SCRIPTS	= uvotimggen

HD_INSTALL_HELP		= uvotimggen.html

HD_INSTALL_PFILES	= uvotimggen.par

include ${HD_STD_MAKEFILE}
