#! /usr/bin/perl
#
#     Filename: fscript
#  Description: write scripts to run XPI-based tasks and/or shell commands
#
#  Author/Date: James Peachey, HEASARC/GSFC/NASA, Hughes STX, May 1997
#

# global scalar initializations
$this_script   = $0;        # get name of this file
$this_script   =~ s:.*/::;  # remove path from file name
$This_script   = "\u$this_script"; # capitalized filename will be needed in help
$g_version     = "0.0";     # version

print<<EOTXT;
$this_script is a Perl script

$This_script Version $g_version;

SUMMARY:
$This_script is a new tool for developing scripts to run sequences of
XPI-based commands (such as Ftools) and/or shell commands. Its design
is being re-assessed, and it may or may not be released at a later date.
For more information, please contact ftoolshelp\@athena.gsfc.nasa.gov.

EOTXT
exit;
