HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= uvotproduct

HD_TEST_PERL_SCRIPTS	= ut-uvotproduct

HD_INSTALL_PFILES	= uvotproduct.par

HD_INSTALL_REFDATA	= uvotproduct_big.grd uvotproduct_small.grd uvotproduct_ds9v6.grd

HD_TEST_PFILES		= ut-uvotproduct.par

HD_INSTALL_HELP		= uvotproduct.html

include ${HD_STD_MAKEFILE}

