HD_COMPONENT_NAME	= heatools

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= ftjoin ftselfjoin

HD_TEST_PERL_SCRIPTS	= ut_ftjoin

HD_INSTALL_PFILES	= ftjoin.par ftselfjoin.par

HD_TEST_PFILES		= ut_ftjoin.par

HD_INSTALL_HELP		= ftjoin.html ftselfjoin.html

include ${HD_STD_MAKEFILE}
