#define yy_create_buffer cb_create_buffer
#define yy_delete_buffer cb_delete_buffer
#define yy_scan_buffer cb_scan_buffer
#define yy_scan_string cb_scan_string
#define yy_scan_bytes cb_scan_bytes
#define yy_flex_debug cb_flex_debug
#define yy_init_buffer cb_init_buffer
#define yy_flush_buffer cb_flush_buffer
#define yy_load_buffer_state cb_load_buffer_state
#define yy_switch_to_buffer cb_switch_to_buffer
#define yyin cbin
#define yyleng cbleng
#define yylex cblex
#define yyout cbout
#define yyrestart cbrestart
#define yytext cbtext
#define yywrap cbwrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /headas/headas/ftools/caltools/src/brcaldb/lex_cb.c,v 3.6 1996/11/11 20:16:14 miket Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 41
#define YY_END_OF_BUFFER 42
static yyconst short int yy_accept[409] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   42,   39,
        1,    2,   39,   39,   39,   39,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   39,   39,   39,   39,   39,   39,   39,   39,   39,
        2,   39,   30,   27,   29,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   33,   39,   38,   33,
       33,    1,    0,    0,    0,    0,    0,    0,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,

       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   26,    0,    0,    0,    0,    0,    0,
       25,    0,    0,   28,    0,    0,    0,    0,    0,    0,
        0,    0,   32,   27,   31,   29,   30,    0,   35,    0,
       34,    0,    0,    0,   33,    0,    0,   33,   33,   33,
        0,   37,   33,   33,    0,   38,   33,   33,   33,    0,
        0,   40,    0,    0,   24,   24,   23,   21,   24,   24,
       24,   24,    6,    7,   12,   24,    4,   24,    2,   24,
       24,   22,   24,   24,   24,   14,   16,   24,   24,   24,

       24,   24,   24,   12,   24,    4,   24,   24,   24,   24,
       24,   24,    0,    0,    0,    0,    2,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   35,
       34,   34,    0,    0,   36,   33,    0,    0,   33,   33,
        0,   33,   33,    2,   22,    0,    0,   24,   24,   24,
       24,   24,   24,   13,   20,   24,    8,    5,    4,   24,
       18,   24,   24,   24,   15,   10,   24,   24,   24,   24,
       24,   24,   24,    8,    5,    4,   24,   18,   24,   24,
       24,    0,    0,    0,    0,   33,   33,   33,   33,   37,
       24,   24,   24,   24,   24,   24,   24,   24,    9,   24,

       24,   12,    8,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,    0,   33,    2,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,    5,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   19,   24,   24,   24,   24,   24,
       24,   24,   11,   11,   24,    3,   18,   17,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   11,   24,

       24,   24,    4,    4,   24,   24,    4,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    7,    8,    1,
        1,    9,   10,    1,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   13,    1,   15,
       16,   17,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   25,   25,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   25,
        1,    1,    1,    1,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   25,   49,   25,   25,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   25,    1,   64,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[66] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    2,    3,    1,
        4,    4,    4,    5,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    1
    } ;

static yyconst short int yy_base[417] =
    {   0,
        0,    0,   64,  127,  190,    0,  242,  307,  946, 1294,
      939, 1294,   34,  875,   40,  924,   56,   59,   61,   81,
       69,   60,   82,   95,   84,   91,  119,  124,  106,   71,
      134,  112,  101,  129,  130,  148,  158,  145,  167,  214,
      152,  925,  243,  899,  887,  843,  798,  792,  783,  772,
      819,  240,  797,  206,  784,  766,  133,  166,  173,  738,
       72,  127,   31,  784,  159,  221,  218,  275,  320,  267,
      225,  781,  752,  684,  717,  678,  647,  676,  227,  252,
      260,  304,  306,  261,  312,  332,  316,  317,  340,  315,
      329,  335,  341,  346,  349,  365,  355,  347,  372,  375,

      377,  379,  353,  354,  378,  383,  384,  387,  388,  393,
      395,  396,  397,  401,  403,  407,  421,  408,  425,  426,
      427,  429,  443, 1294,  659,  608,  587,  578,  610,  592,
     1294,  580,  529, 1294,  518,  196,  316,  269,  488,  207,
      387,  252, 1294, 1294, 1294, 1294, 1294,  529,  521,  513,
      510,  510,  500,  481,  447,  467,  482, 1294,  468,  483,
      494,  502,  503,  517,  527,  532,  546,  550,  554,  447,
      413, 1294,  438,  413,  484,  479,  495,  497,  508,  547,
      553,  531,  538,  551,  560,  562,  567,  559,  566,  568,
      569,  572,  576,  577,  592,  582,  591,  597,  601,  602,

      606,  612,  607,  614,  615,  616,  621,  622,  623,  630,
      636,  646,  448,  452,  407,  419, 1294,  415,  393,  332,
      327,  291,  288,  272,  258,  213,  204,  188,  184, 1294,
     1294,  181,  681,  689, 1294,  695,  707,  708,  610,  656,
      160,  671,  718,  724, 1294,  140,  139,  703,  661,  725,
      709,  655,  717,  626,  677,  726,  727,  733,  740,  745,
      746,  749,  735,  751,  685,  728,  763,  765,  774,  764,
      766,  781,  770,  783,  785,  787,  788,  800,  789,  803,
      805,  125,  107,  843,   99,  782,  844,  854,  858,   90,
      857,  819,  855,  859,  864,  865,  869,  866,  818,  879,

      820,  872,  873,  878,  885,  888,  890,  894,  898,  895,
      902,  913,  909,  919,  916,  920,  928,  923,  931,  933,
      935,  948,  952,  956,  957,  968,  969,  201, 1294,  976,
      970,  980,  987,  981,  982,  990,  998, 1001, 1003, 1006,
     1012, 1015, 1010, 1013, 1023, 1004, 1024, 1032, 1034, 1035,
     1041, 1048, 1045, 1046, 1052, 1054, 1049, 1056, 1058, 1057,
     1065, 1063, 1067, 1069, 1078, 1070, 1086, 1088, 1089, 1095,
     1104, 1118, 1109, 1112, 1119, 1120, 1128, 1124, 1129, 1126,
     1149, 1152, 1154, 1133, 1158, 1134, 1137, 1159, 1163, 1167,
     1168, 1169, 1170, 1172, 1173, 1174, 1178, 1175, 1188, 1189,

     1191, 1182, 1198, 1192, 1206, 1208, 1224, 1294, 1266, 1271,
       76,   73, 1276, 1281, 1285, 1288
    } ;

static yyconst short int yy_def[417] =
    {   0,
      408,    1,  409,  409,  409,    5,  410,  410,  408,  408,
      408,  408,  408,  408,  408,  411,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  413,  414,  415,  416,  415,  415,  416,
      416,  408,  408,  408,  408,  408,  408,  411,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  413,  408,  414,
      408,  414,  413,  414,  416,  415,  415,  408,  416,  416,
      415,  415,  416,  416,  415,  415,  416,  416,  416,  408,
      408,  408,  408,  408,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  415,  415,  408,  416,  415,  415,  416,  416,
      408,  416,  416,  416,  408,  408,  408,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  408,  408,  415,  408,  416,  416,  416,  416,  408,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  408,  408,  416,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,    0,  408,  408,
      408,  408,  408,  408,  408,  408
    } ;

static yyconst short int yy_nxt[1360] =
    {   0,
       10,   11,   10,   12,   10,   13,   10,   14,   10,   10,
       10,   15,   10,   16,   10,   10,   10,   17,   18,   19,
       20,   21,   22,   17,   17,   23,   17,   24,   25,   17,
       17,   26,   27,   17,   28,   17,   29,   17,   17,   17,
       17,   17,   30,   31,   32,   33,   34,   17,   35,   17,
       36,   37,   17,   17,   38,   39,   17,   40,   17,   41,
       17,   17,   17,   10,   10,   11,   73,   12,   76,   80,
       42,   14,   80,   80,   80,   43,  134,   81,   83,   84,
       79,   44,   80,  133,   80,   92,   85,   86,   82,   74,
       87,   77,   45,   46,   80,   80,   79,   80,   88,   79,

       79,   79,   89,  290,   80,   47,   90,   91,   80,   79,
       93,   79,  328,   95,   80,   48,   49,  145,  124,   80,
       94,   79,   79,  103,   79,   80,   96,   50,   11,  146,
       12,   79,   80,   42,   14,   79,  124,   80,   43,  102,
       97,   79,   80,   80,   44,   99,   79,   80,   98,  100,
      217,  217,   79,  109,  145,   45,   46,  110,   80,   79,
      111,   80,  112,  101,   79,   80,  151,  146,   47,   79,
       79,   80,  143,  290,   79,  104,  105,  113,   48,   49,
       80,  114,  106,  107,  147,   79,  108,  143,   79,  231,
       50,   11,   79,   51,  134,  134,  115,   14,   79,  147,

      147,   52,  130,  117,   53,   54,   55,   79,  123,  235,
      116,   56,  118,   57,  328,  143,   58,  219,   59,  119,
      143,  144,  145,  152,  146,  153,  158,   80,  154,  160,
      220,  160,  156,  158,  157,   60,  160,   61,  160,   62,
       80,   63,   10,   11,   10,   12,   64,   10,   10,   65,
       66,   10,  225,   68,   79,   69,   10,   10,   10,  120,
      125,  135,  121,  136,  226,   80,  137,   79,  138,  145,
       70,   76,  126,   80,   80,  158,  122,  169,  160,  408,
      160,  177,  408,  144,  127,  139,  161,  140,  162,  141,
      223,  142,   79,   71,   77,  128,  168,  229,  173,  134,

       79,   79,  147,  163,  174,   10,   10,   10,   11,   10,
       12,   64,   10,   10,   65,   66,   10,   80,   68,   80,
       69,   10,   10,   10,  408,   80,  164,  408,   80,   80,
       80,  165,  176,  166,  178,   70,  180,  221,  143,  175,
      167,  167,   80,  146,   79,   80,   79,  184,   80,  179,
      222,  181,   79,   80,   80,   79,   79,   79,   71,   80,
       80,  186,   80,  185,  167,  167,   80,   80,   80,   79,
       10,   10,   79,  182,  187,   79,  183,  191,   80,  188,
       79,   79,  190,  189,  192,   80,   79,   79,   80,   79,
       80,   80,   80,   79,   79,   79,   80,   80,  193,  196,

       80,   80,  194,  199,  145,   79,   80,  195,   80,   80,
       80,  198,   79,  197,   80,   79,   80,   79,   79,   79,
       80,   80,  177,   79,   79,  200,  144,   79,   79,  178,
      131,  201,  227,   79,   80,   79,   79,   79,   80,   80,
       80,   79,   80,   79,  228,  202,  205,   79,   79,  203,
      184,  283,  183,  204,  209,  158,   80,  206,  160,  207,
      160,   79,  208,  131,  189,   79,   79,   79,  282,   79,
      247,  408,  246,  245,  408,  210,  158,  211,  233,  160,
      234,  160,  212,   79,  245,  192,  408,  196,  151,  408,
      235,  158,   80,  156,  160,  157,  160,   80,  408,  249,

      197,  408,  236,  236,  149,  161,  408,  237,   80,  408,
       80,  158,  248,  238,  160,  162,  160,  232,  231,  250,
      151,   80,  167,  167,   79,  158,  236,  236,  160,  230,
      160,  408,  239,  149,  408,   79,  408,   79,  161,  408,
      162,  251,  224,  165,   80,  166,  167,  167,   79,  218,
      255,   80,  167,  167,  158,  241,  242,  160,  158,  243,
       80,  160,  158,  160,   80,  160,   80,  160,  252,  240,
      253,   79,   80,   80,  254,   80,  167,  167,   79,   80,
       80,   80,   80,  257,  244,   80,  217,   79,  256,   80,
       80,   79,  260,   79,  261,   80,  258,  264,  265,   79,

       79,  259,   79,  262,   80,   80,   79,   79,   79,  263,
       80,  244,   79,  266,   80,   80,   79,   79,  158,   80,
       80,  160,   79,  160,  124,   80,  217,   80,   80,   80,
      124,   79,   79,  216,   80,   80,   80,   79,  215,   80,
      214,  268,   79,   80,  288,  269,   79,   79,  267,   80,
      255,  271,   79,  272,   79,   79,   79,  254,  270,   80,
      274,   79,   79,  279,  158,  273,   79,  160,   80,  160,
       79,  278,  275,  276,   80,  281,   79,  277,  292,  158,
      280,  265,  160,  300,  243,  408,   79,  213,  408,   78,
       80,  266,  233,  408,  284,   79,  408,  235,   80,  174,

      238,   79,  234,  158,  285,  286,  160,  173,  287,  236,
      236,  408,  408,  289,  408,  408,   80,   79,  238,  238,
      237,  238,   80,  291,  172,   79,  158,  167,  167,  160,
       80,  243,  158,  236,  236,  160,  171,  160,   80,   80,
       80,   80,  299,   79,  293,  294,   80,  295,   80,   79,
      301,  167,  167,   80,  304,  302,  296,   79,   80,   80,
      303,  297,   80,  298,   80,   79,   79,   79,   79,  309,
      306,  307,  305,   79,  308,   79,   80,   80,   80,   80,
       79,  170,   72,   80,  310,   79,   79,   80,  149,   79,
      158,   79,  144,  160,   80,  287,   80,  144,   80,  145,

       80,   80,   80,   79,   79,   79,   79,  311,  312,  313,
       79,  314,  143,   80,   79,  318,   80,  319,   80,  315,
      299,   79,  302,   79,  316,   79,  317,   79,   79,   79,
      321,   80,   80,   80,  134,  131,  323,  320,  131,  303,
       79,  345,  322,   79,  133,   79,  325,  408,  324,  132,
      408,  326,  329,  332,  238,  160,  284,  287,   79,   79,
       79,  327,  158,  236,  236,  330,  158,  160,   80,  330,
       80,  160,   80,  333,  331,  131,  336,   80,   80,   80,
      337,  334,   80,  335,  338,   80,   80,  236,  236,  340,
      177,   80,   80,  339,  343,   79,  344,   79,   80,   79,

      341,   80,  342,   80,   79,   79,   79,   80,   80,   79,
      346,   80,   79,   79,  352,   80,  130,  348,   79,   79,
      347,  350,   80,  351,  349,   79,   80,  129,   79,   80,
       79,  124,   80,   80,   79,   79,   80,   78,   79,   75,
       72,   80,   79,  353,   80,  408,   80,  408,   80,   79,
      357,  408,  408,   79,  358,  354,   79,  359,  177,   79,
       79,   80,  355,   79,  356,   80,  360,  361,   79,   80,
       80,   79,  366,   79,  362,   79,  363,  408,  367,  364,
      365,   80,   80,   80,  158,  408,  408,  160,   79,  160,
      346,  408,   79,   80,   80,   80,   79,   79,  376,  377,

       80,  375,  374,   80,  369,  371,  368,  177,   79,   79,
       79,   80,  373,  370,   80,  408,   80,   80,  372,   80,
       79,   79,   79,   80,  378,   80,   80,   79,   80,  382,
       79,  379,  381,  184,  183,  196,   80,   80,   79,  302,
      383,   79,  380,   79,   79,   80,   79,   80,   80,  197,
       79,  385,   79,   79,   80,   79,  388,  384,   80,   80,
      386,   80,   80,   79,   79,   80,  408,   80,  389,   80,
       80,   80,   79,  387,   79,   79,   80,  390,   80,  408,
       80,   79,   80,   80,  408,   79,   79,  408,   79,   79,
      177,   80,   79,  392,   79,  393,   79,   79,   79,   80,

      391,   80,   80,   79,  398,   79,  394,   79,   80,   79,
       79,  196,  395,  184,  397,  183,  408,   80,   79,  396,
      399,  302,   80,  375,  197,   80,   79,  408,   79,   79,
      408,   80,   80,   80,  408,   79,  408,   80,  400,   80,
      386,   80,   80,  384,   79,  375,   80,   80,  255,   79,
       80,  177,   79,  299,  401,  384,  266,  387,   79,   79,
       79,  402,   80,  388,   79,   80,   79,   80,   79,   79,
      303,   80,   80,   79,   79,  384,   80,   79,  387,  403,
       80,   80,   80,   80,  388,   80,   80,   80,   80,   79,
      408,   80,   79,  408,   79,   80,  408,  386,   79,   79,

      408,   80,   80,   79,   80,   80,  408,   79,   79,   79,
       79,   80,   79,   79,   79,   79,  255,  375,   79,   80,
      384,   80,   79,  303,  387,  299,  405,  266,   79,   79,
      177,   79,   79,  384,  404,  386,  388,   80,   79,  408,
      407,  408,  408,  406,  408,  408,   79,  408,   79,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,   79,  407,   10,   10,   10,   10,
       10,   67,   67,   67,   67,   67,  148,  148,  148,  148,
      148,  150,  150,  150,  150,  150,  155,  408,  155,  155,
      159,  159,  159,    9,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408
    } ;

static yyconst short int yy_chk[1360] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,   13,    3,   15,   17,
        3,    3,   18,   22,   19,    3,   63,  412,   19,   19,
      411,    3,   21,   63,   30,   22,   19,   19,   18,   13,
       19,   15,    3,    3,   20,   23,   17,   25,   20,   18,

       22,   19,   20,  290,   26,    3,   20,   21,   24,   21,
       23,   30,  285,   25,   33,    3,    3,   61,  283,   29,
       24,   20,   23,   30,   25,   32,   26,    3,    4,   61,
        4,   26,   27,    4,    4,   24,  282,   28,    4,   29,
       27,   33,   34,   35,    4,   28,   29,   31,   27,   28,
      247,  246,   32,   32,   57,    4,    4,   32,   38,   27,
       32,   36,   33,   28,   28,   41,   65,   57,    4,   34,
       35,   37,   62,  241,   31,   31,   31,   34,    4,    4,
       39,   35,   31,   31,   62,   38,   31,   58,   36,  232,
        4,    5,   41,    5,   59,  229,   36,    5,   37,  228,

       58,    5,   59,   38,    5,    5,    5,   39,   41,  328,
       37,    5,   39,    5,  328,  227,    5,  136,    5,   39,
       54,   54,   54,   65,  226,   66,   67,   40,   66,   67,
      136,   67,   66,   71,   66,    5,   71,    5,   71,    5,
       79,    5,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,  140,    7,   40,    7,    7,    7,    7,   40,
       43,   52,   40,   52,  140,   80,   52,   79,   52,  225,
        7,   43,   43,   81,   84,   70,   40,   71,   70,   68,
       70,   84,   68,  224,   43,   52,   68,   52,   68,   52,
      138,   52,   80,    7,   43,   43,   70,  142,  138,  223,

       81,   84,  222,   68,  142,    7,    7,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,   82,    8,   83,
        8,    8,    8,    8,   69,   85,   68,   69,   90,   87,
       88,   69,   83,   69,   85,    8,   87,  137,  221,   82,
       69,   69,   91,  220,   82,   86,   83,   90,   92,   86,
      137,   88,   85,   89,   93,   90,   87,   88,    8,   94,
       98,   92,   95,   91,   69,   69,  103,  104,   97,   91,
        8,    8,   86,   89,   93,   92,   89,   97,   96,   94,
       89,   93,   96,   95,   98,   99,   94,   98,  100,   95,
      101,  105,  102,  103,  104,   97,  106,  107,   99,  102,

      108,  109,  100,  104,  219,   96,  110,  101,  111,  112,
      113,  103,   99,  102,  114,  100,  115,  101,  105,  102,
      116,  118,  105,  106,  107,  107,  218,  108,  109,  106,
      216,  108,  141,  110,  117,  111,  112,  113,  119,  120,
      121,  114,  122,  115,  141,  109,  113,  116,  118,  110,
      111,  215,  110,  112,  118,  155,  123,  114,  155,  115,
      155,  117,  117,  214,  116,  119,  120,  121,  213,  122,
      174,  156,  173,  171,  156,  120,  159,  121,  156,  159,
      156,  159,  122,  123,  170,  119,  157,  123,  154,  157,
      157,  160,  176,  157,  160,  157,  160,  175,  161,  176,

      123,  161,  157,  157,  153,  161,  162,  161,  177,  162,
      178,  163,  175,  162,  163,  162,  163,  152,  151,  176,
      150,  179,  162,  162,  175,  164,  157,  157,  164,  149,
      164,  165,  163,  148,  165,  177,  166,  178,  165,  166,
      165,  179,  139,  166,  182,  166,  162,  162,  179,  135,
      182,  183,  166,  166,  167,  167,  167,  167,  168,  167,
      180,  168,  169,  168,  184,  169,  181,  169,  180,  164,
      181,  182,  188,  185,  181,  186,  166,  166,  183,  189,
      187,  190,  191,  186,  168,  192,  133,  180,  185,  193,
      194,  184,  188,  181,  190,  196,  186,  193,  194,  188,

      185,  187,  186,  191,  197,  195,  189,  187,  190,  191,
      198,  169,  192,  195,  199,  200,  193,  194,  239,  201,
      203,  239,  196,  239,  132,  202,  130,  204,  205,  206,
      129,  197,  195,  128,  207,  208,  209,  198,  127,  254,
      126,  199,  200,  210,  239,  199,  201,  203,  198,  211,
      203,  201,  202,  202,  204,  205,  206,  202,  200,  212,
      205,  207,  208,  209,  240,  204,  254,  240,  252,  240,
      210,  208,  205,  206,  249,  210,  211,  207,  249,  242,
      209,  211,  242,  252,  242,  233,  212,  125,  233,   78,
      255,  212,  233,  234,  233,  252,  234,  234,  265,   77,

      234,  249,  234,  236,  236,  236,  236,   76,  236,  234,
      234,  237,  238,  240,  237,  238,  248,  255,  237,  238,
      237,  238,  251,  248,   75,  265,  243,  237,  237,  243,
      253,  243,  244,  234,  234,  244,   74,  244,  250,  256,
      257,  266,  251,  248,  250,  250,  258,  250,  263,  251,
      253,  237,  237,  259,  258,  256,  250,  253,  260,  261,
      257,  250,  262,  250,  264,  250,  256,  257,  266,  263,
      260,  261,  259,  258,  262,  263,  267,  270,  268,  271,
      259,   73,   72,  273,  264,  260,  261,  269,   64,  262,
      286,  264,   60,  286,  272,  286,  274,   56,  275,   55,

      276,  277,  279,  267,  270,  268,  271,  267,  268,  268,
      273,  268,   53,  278,  269,  269,  280,  271,  281,  268,
      270,  272,  273,  274,  268,  275,  268,  276,  277,  279,
      275,  299,  292,  301,   51,   50,  277,  272,   49,  274,
      278,  301,  276,  280,   48,  281,  279,  284,  278,   47,
      284,  280,  287,  292,  284,  287,  284,  287,  299,  292,
      301,  281,  288,  284,  284,  288,  289,  288,  293,  289,
      291,  289,  294,  293,  291,   46,  294,  295,  296,  298,
      294,  293,  297,  293,  294,  302,  303,  284,  284,  295,
      291,  304,  300,  294,  298,  293,  300,  291,  305,  294,

      296,  306,  297,  307,  295,  296,  298,  308,  310,  297,
      304,  309,  302,  303,  310,  311,   45,  306,  304,  300,
      305,  308,  313,  309,  307,  305,  312,   44,  306,  315,
      307,   42,  314,  316,  308,  310,  318,   16,  309,   14,
       11,  317,  311,  311,  319,    9,  320,    0,  321,  313,
      313,    0,    0,  312,  313,  312,  315,  313,  311,  314,
      316,  322,  312,  318,  312,  323,  313,  314,  317,  324,
      325,  319,  319,  320,  315,  321,  316,    0,  320,  317,
      318,  326,  327,  331,  330,    0,    0,  330,  322,  330,
      321,    0,  323,  332,  334,  335,  324,  325,  334,  335,

      333,  332,  331,  336,  323,  325,  322,  333,  326,  327,
      331,  337,  327,  324,  338,    0,  339,  346,  326,  340,
      332,  334,  335,  343,  336,  341,  344,  333,  342,  341,
      336,  337,  340,  338,  337,  342,  345,  347,  337,  343,
      344,  338,  339,  339,  346,  348,  340,  349,  350,  342,
      343,  347,  341,  344,  351,  342,  350,  345,  353,  354,
      348,  352,  357,  345,  347,  355,    0,  356,  351,  358,
      360,  359,  348,  349,  349,  350,  362,  352,  361,    0,
      363,  351,  364,  366,    0,  353,  354,    0,  352,  357,
      354,  365,  355,  355,  356,  356,  358,  360,  359,  367,

      353,  368,  369,  362,  362,  361,  357,  363,  370,  364,
      366,  363,  358,  359,  361,  358,    0,  371,  365,  360,
      366,  364,  373,  365,  363,  374,  367,    0,  368,  369,
        0,  372,  375,  376,    0,  370,    0,  378,  368,  380,
      369,  377,  379,  367,  371,  378,  384,  386,  379,  373,
      387,  374,  374,  376,  371,  377,  380,  370,  372,  375,
      376,  373,  381,  372,  378,  382,  380,  383,  377,  379,
      381,  385,  388,  384,  386,  383,  389,  387,  382,  385,
      390,  391,  392,  393,  389,  394,  395,  396,  398,  381,
        0,  397,  382,    0,  383,  402,    0,  390,  385,  388,

        0,  399,  400,  389,  401,  404,    0,  390,  391,  392,
      393,  403,  394,  395,  396,  398,  395,  394,  397,  405,
      393,  406,  402,  397,  398,  392,  403,  396,  399,  400,
      391,  401,  404,  399,  400,  402,  401,  407,  403,    0,
      405,    0,    0,  404,    0,    0,  405,    0,  406,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  407,  406,  409,  409,  409,  409,
      409,  410,  410,  410,  410,  410,  413,  413,  413,  413,
      413,  414,  414,  414,  414,  414,  415,    0,  415,  415,
      416,  416,  416,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "brcaldb.l"
#define INITIAL 0
#line 2 "brcaldb.l"
#include <string.h>
#include <math.h>

#include "optr.h"
#include "y_tab.h"

/* Redefine YY_INPUT so that lex input will come from internal memory */
#undef YY_INPUT
#define YY_INPUT(b,r,ms) (r=rdmemstr(b,ms))

#define min(X, Y)  ((X) < (Y) ? (X) : (Y))
#ifdef vms
#define isatty(fd) 0
#endif

int len;
int exprlen;

#define BOPMODE 1

#define AOPMODE 2

#define VALMODE 3

#line 840 "lex.cb.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 63 "brcaldb.l"


#line 990 "lex.cb.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 409 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1294 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 65 "brcaldb.l"
{exprlen += 1;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 67 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  exprlen += cbleng;
		  return NOT;
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 73 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return MISSION;
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 80 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return INSTRUM;
		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 87 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return FILTER;
		}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 94 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return DEVICE;
		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 101 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return DIR;
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 108 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return CFILE;
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 115 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return CLASS;
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 122 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return DATATYP;
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 129 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return CODENAM;
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 136 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return EXTNO;
		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 143 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return DATE;
		}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 150 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return VSD;
		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 157 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return TIME;
		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 164 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return VST;
		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 171 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return REFTIME;
		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 178 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return QUALITY;
		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 185 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return CALDATE;
		}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 192 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return DESCRIP;
		}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 199 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return CIF;
			}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 206 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return ROW;
		}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 213 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return CBD;
		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 220 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN AOPMODE;
		  exprlen += cbleng;
		  return PARAM;
		}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 227 "brcaldb.l"
{
		  strcpy(cblval.boolop.opstr,cbtext);
		  cblval.boolop.optyp = OPOR;
		  BEGIN INITIAL;
		  exprlen += cbleng;
		  return BOOLOP;
		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 235 "brcaldb.l"
{
		  strcpy(cblval.boolop.opstr,cbtext);
		  cblval.boolop.optyp = OPAND;
		  BEGIN INITIAL;
		  exprlen += cbleng;
		  return BOOLOP;
		}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 243 "brcaldb.l"
{
		  strcpy(cblval.arthop.opstr,cbtext);
		  cblval.arthop.optyp = OPEQ;
		  BEGIN VALMODE;
		  exprlen += cbleng;
		  return ARTHOP;
		}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 251 "brcaldb.l"
{
		  strcpy(cblval.arthop.opstr,cbtext);
		  cblval.arthop.optyp = OPNE;
		  BEGIN VALMODE;
		  exprlen += cbleng;
		  return ARTHOP;
		}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 259 "brcaldb.l"
{
		  strcpy(cblval.arthop.opstr,cbtext);
		  cblval.arthop.optyp = OPGT;
		  BEGIN VALMODE;
		  exprlen += cbleng;
		  return ARTHOP;
		}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 267 "brcaldb.l"
{
		  strcpy(cblval.arthop.opstr,cbtext);
		  cblval.arthop.optyp = OPLT;
		  BEGIN VALMODE;
		  exprlen += cbleng;
		  return ARTHOP;
		}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 275 "brcaldb.l"
{
		  strcpy(cblval.arthop.opstr,cbtext);
		  cblval.arthop.optyp = OPGE;
		  BEGIN VALMODE;
		  exprlen += cbleng;
		  return ARTHOP;
		}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 283 "brcaldb.l"
{
		  strcpy(cblval.arthop.opstr,cbtext);
		  cblval.arthop.optyp = OPLE;
		  BEGIN VALMODE;
		  exprlen += cbleng;
		  return ARTHOP;
		}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 291 "brcaldb.l"
{
		  strcpy(cblval.string,cbtext);
		  BEGIN BOPMODE;
		  exprlen += cbleng;
		  return STRNG;
		}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 298 "brcaldb.l"
{
		  stripq();
		  BEGIN BOPMODE;
		  exprlen += cbleng;
		  return STRNG;
		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 305 "brcaldb.l"
{
		  stripq();
		  BEGIN BOPMODE;
		  exprlen += cbleng;
		  return STRNG;
		}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 312 "brcaldb.l"
{
                  strcpy(cblval.string,cbtext);
		  BEGIN BOPMODE;
		  exprlen += cbleng;
		  return STRNG;
		}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 319 "brcaldb.l"
{
		  len = 0; 
                  while (cbtext[len] != '\0')
                       {
                        if (cbtext[len] == 'd') cbtext[len]='e';
                        if (cbtext[len] == 'D') cbtext[len]='e';
                        if (cbtext[len] == 'E') cbtext[len]='e';
                        len++;
                       }
		  strcpy(cblval.number,cbtext);
		  BEGIN BOPMODE;
		  exprlen += cbleng;
                  return NUMBER;
                }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 334 "brcaldb.l"
{
		  strcpy(cblval.number,cbtext);
		  BEGIN BOPMODE;
		  exprlen += cbleng;
		  return NUMBER;
		}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 341 "brcaldb.l"
{
		  exprlen += 1;
		  return cbtext[0];
		}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 346 "brcaldb.l"
{
		  return (0);
		}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 350 "brcaldb.l"
ECHO;
	YY_BREAK
#line 1483 "lex.cb.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BOPMODE):
case YY_STATE_EOF(AOPMODE):
case YY_STATE_EOF(VALMODE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 65);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 409 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 65;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 409 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 408);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 350 "brcaldb.l"


extern char expr[];
extern char *exprptr;
extern char *exprlim;

extern char *colmptr;
extern char *colmlim;

int rdmemstr(buf, max_size)
 char *buf;
 int max_size;
 {
     char *strbufptr, *strbuflim;
     extern int read_string;
     int n;

     switch (read_string) {
          case 1: strbufptr = exprptr; strbuflim = exprlim; break;
          case 2: strbufptr = colmptr; strbuflim = colmlim; break;
     }

     n = min(max_size,strbuflim - strbufptr);

     if(n>0) {
          memcpy(buf,strbufptr,n);
          strbufptr += n;
     }
     return n;
 }

int stripq()
{
   int n = 0, wrdlen = 0; 
   char c;
   char *q1, *q2;
 
   if (cbtext[0] == '\'') {
       c = '\'';   
       q1 = &cbtext[0];
   } 
   else if (cbtext[0] == '\"') {
       c = '\"';   
       q1 = &cbtext[0];
   } 
   else if (cbtext[1] == '\'') {
       c = '\'';   
       q1 = &cbtext[1];
   } 
   else if (cbtext[1] == '\"') {
       c = '\"';   
       q1 = &cbtext[1];
   } 
 
   q2 = strrchr(cbtext,c); 
   wrdlen = q2-q1-1; 

   if (cbtext[0] == '*') {
       cblval.string[n] = '*';
       n++;
   }

   strncpy(&cblval.string[n],&q1[1],wrdlen);
   if (q2[1] == '*') {
      cblval.string[n+wrdlen] = '*';
      cblval.string[n+wrdlen+1] = '\0';
   }
   else {
      cblval.string[n+wrdlen] = '\0';
   }

}

begin_initial()
{
    BEGIN INITIAL;
}

int cbwrap()
        {   
        return 1;
        }
