HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

HD_INSTALL_PERL_SCRIPTS	=

HD_INSTALL_PERL_LIBS	= *.pm

HD_INSTALL_PFILES	=

HD_INSTALL_HELP		=

include ${HD_STD_MAKEFILE}

install :: install-perl-libraries

install-perl-libraries:
	${MAKE} hd-std-install-perl-libraries HD_INSTALL_PERL_LIBS="*.pm"
