HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= onepar

HD_CTASK_SRC_c		= 

HD_CTASK_SRC_f		= onepar.f specread.f wftbmd.f

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -l${XANLIB} -l${PIL} -l${CFITSIO} \
			  -l${READLINE} ${SYSLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_CLEAN		= *.aux *.dvi *.log *.ps

include ${HD_STD_MAKEFILE}



