HD_COMPONENT_NAME	= suzaku

HD_COMPONENT_VERS	=

HD_SUBDIRS		= \
suzakuversion aeaspect aeattcor aeattcor2 aemkehk aemkreg aetimecalc \
aecoordcalc aebarycen aemkpinudhk aepipeline gtisynch mkphlist \
xiscontamicalc xisexpmapgen xisgtigen xissim xissimarfgen xisarfgen xisrmfgen \
xiscoord xispi xistime xisucode xisputpixelquality xis5x5to3x3 xisnxbgen \
xisllegtigen \
hxdarfgen hxdbsttime hxdgrade hxdmkwamgainhist \
hxdpi hxdpi_old hxdscltime hxdtime hxdwamgrade hxdwampi \
hxdwamtime hxdmkwamlc hxdmkwamspec hxdmkbstlc \
hxddtcor hxdgtigen hxdmkgainhist \
hxdwambstid hxdmkbstspec hxdxb hxdbstjudge hxdwampipeline

include ${HD_STD_MAKEFILE}
