HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= batglobalgti

HD_TEST_PERL_SCRIPTS	= ut_batglobalgti

HD_INSTALL_PFILES	= batglobalgti.par

HD_TEST_PFILES		= ut_batglobalgti.par

HD_INSTALL_HELP		= batglobalgti.html

include ${HD_STD_MAKEFILE}
