HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= hriaspcor

HD_CTASK_SRC_c		= hhriaspcor.c

HD_CTASK_SRC_f		= hriaspcor.f

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -lros${FT_VERS} \
			  ${HD_STD_LIBS} ${SYSLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= hriaspcor.par

HD_INSTALL_HELP		= hriaspcor.hlp hriaspcor.txt

include ${HD_STD_MAKEFILE}
