# Component (mission) name. Developers need not change/delete this.
HD_COMPONENT_NAME	= nustar

# Software release version number. Developers need not change/delete this.
HD_COMPONENT_VERS	=

# Subdirectories of the current directory (or from the top package-level)
# to be built.
HD_SUBDIRS		= nusplitsc nucalcpha nucalcpi nucalcpos nuflagbad nuhotpix nucoord nufilter nuscreen numetrology nuproducts nuskypos numkarf numkrmf nuexpomap nulivetime nuflagevt nucalcsaa nuskytodet nulccorr nuattcorr nubackscale nupipeline nuversion


# Subdirectories of the current directory (or from the top package-level)
# which contain one or more unit test targets.
HD_TEST_SUBDIRS         = nusplitsc  nucalcpha nucalcpi nucalcpos nuflagbad nuhotpix nucoord nufilter nuscreen numetrology nuproducts numkarf numkrmf nuexpomap nuflagevt nucalcsaa nuskytodet nulccorr nuattcorr nubackscale nupipeline

HD_TEST_PERL_SCRIPTS    = ut_nustarALL

include ${HD_STD_MAKEFILE}
