HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= uvot2pha

HD_TEST_PERL_SCRIPTS	= ut-uvot2pha

HD_INSTALL_PFILES	= uvot2pha.par

HD_TEST_PFILES		= ut-uvot2pha.par

HD_INSTALL_HELP		= uvot2pha.html

include ${HD_STD_MAKEFILE}
