HD_COMPONENT_NAME	= heagen

HD_COMPONENT_VERS	=

HD_CTASK		= hdaxbary

HD_CTASK_SRC_c		= axBary.c  bary.c  clock.c  ctatv.c  dpleph.c  scorbit.c  xCC.c sCC.c nCC.c haxBary.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PERL_SCRIPTS = barycorr

HD_INSTALL_PFILES	= barycorr.par

HD_INSTALL_HELP		= barycorr.html

HD_TEST_PERL_SCRIPTS	= ut-barycorr

HD_TEST_PFILES		= ut-barycorr.par

include ${HD_STD_MAKEFILE}
