HD_COMPONENT_NAME	= swift 

HD_COMPONENT_VERS	=

HD_CTASK		= batgse2dpi

HD_CTASK_SRC_c		= batgse2dpi.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_LFLAGS} -lbatutils ${HD_STD_LIBS} ${SYSLIBS}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= batgse2dpi.par

HD_INSTALL_HELP		= batgse2dpi.html

HD_TEST_PERL_SCRIPTS    = ut_batgse2dpi.pl

include ${HD_STD_MAKEFILE}
