#!/bin/csh
#
# Prepare MPFIT C library for distribution
#
# USAGE:
#   distrib VERSION
# EXAMPLE:
#   distrib 1.2b2
# SIDE EFFECTS:
#   the script creates a directory named cmpfit-VERSION
#   and release files named cmpfit-VERSION.{tar.gz,zip}
#


if ($# == 0) then
  echo "ERROR: you must give a version number"
  exit 1
endif

# Make sure the README file is up to date
make README

set ver=$1
set outdir="cmpfit-${ver}"
mkdir ${outdir}
foreach file (mpfit.c mpfit.h DISCLAIMER README Makefile.unx \
      testmpfit.c testmpfit.log)
  cp -p ${file} ${outdir}/${file}
end
mv ${outdir}/Makefile.unx ${outdir}/Makefile
tar cvfz ${outdir}.tar.gz ${outdir}
zip -r ${outdir}.zip      ${outdir}

exit 0
