HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	=

HD_INSTALL_PERL_SCRIPTS	= asmchannel asmsrcupdate chantrans faxbary \
			  grosstimefilt gti2xronwin hxtback hxtlcurv hxtrsp \
			  make_se pca_bs pcadeadcalc1 pcadeadcalc2 \
			  pcadeadspect2 pcaprepfile2 pcaextspect2 pcaextlc2 \
			  pcamergeobsids pcaprepobsid \
			  pcarsp proc2pcu rex runpcabackest \
			  sachip saplot sefilter seplot seselect sumpha \
			  timetrans xtefilt xteversion

HD_INSTALL_HELP		= asmchannel.txt asmsrcupdate.txt chantrans.txt \
			  faxbary.txt grosstimefilt.txt gti2xronwin.txt \
			  hxtback.txt hxtdeadlc.txt hxtdeadpha.txt \
			  hxtlcurv.txt hxtrsp.txt make_se.txt pca_bs.txt \
			  pcadeadcalc2.txt pcadeadspect2.txt pcaextlc2.txt \
			  pcaextspect2.txt pcamergeobsids.txt \
			  pcaprepfile2.txt pcaprepobsid.txt pcarsp.txt \
			  proc2pcu.txt rex.txt runpcabackest.txt sachip.txt \
			  saplot.txt sefilter.txt seplot.txt seselect.txt \
			  sumpha.txt timetrans.txt xtefilt.txt xteversion.txt

HD_INSTALL_PFILES	= faxbary.par pcadeadcalc2.par pcadeadspect2.par \
			  pcaprepfile2.par pcaextlc2.par pcaextspect2.par \
			  pcamergeobsids.par pcaprepobsid.par \
			  proc2pcu.par sumpha.par

include ${HD_STD_MAKEFILE}
