#!/usr/bin/perl
#
# Returns the XTE FTOOLS package version number read
#  from the xte.par file
# 
#  Mike Tripicco (HSTX/NASA/HEASARC) 17 May 1996
#

require "utils.pl";
use Getopt::Std;

getopt();

if ( defined $opt_h ) {
    print<<EOHELP;

                 ****** xteversion ******

Prints the XTE FTOOLS version number and release date

USAGE:

xteversion

FLAGS:

-h          print this help

EOHELP
exit 0;
}

open(PARFIL,"$ENV{'FTOOLS'}/syspfiles/xte.par");
while (<PARFIL>){
  if ($.==3){
   @fields=split(/\"/);
   print "$fields[1]\n";
  }
}
