HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

# ut-mod1.1 ut-sim1.1 ut-udetect-0.2 ut-umag-0.2 linked from build2 in repository
HD_TEST_PERL_SCRIPTS	= ut-mod1.1  ut-sim1.1  ut-starid-1.0  ut-tfc-1.0  ut-udetect-0.2  ut-umag-0.2

include ${HD_STD_MAKEFILE}
