HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= cphead

HD_CTASK_SRC_c		= hcphead.c c_copyhead.c c_copyheadn.c cphead.c \
			  fit_comment.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= cphead.par

HD_INSTALL_HELP		= cphead.hlp cphead.txt

include ${HD_STD_MAKEFILE}
