HD_COMPONENT_NAME       = hitomi

HD_COMPONENT_VERS       =

HD_INSTALL_PERL_SCRIPTS = cams2att.pl

HD_INSTALL_PFILES       = cams2att.par

HD_INSTALL_HELP         = cams2att.html

include ${HD_STD_MAKEFILE}

