HD_COMPONENT_NAME	= demo

HD_COMPONENT_VERS	=

HD_INSTALL_PERL_SCRIPTS	= perldemo

HD_INSTALL_PERL_LIBS	= perldemo_utils.pl

HD_INSTALL_PFILES	= perldemo.par

HD_INSTALL_HELP		= perldemo.html

include ${HD_STD_MAKEFILE}
