HD_COMPONENT_NAME       = hitomi

HD_COMPONENT_VERS       =

HD_INSTALL_PERL_SCRIPTS = ahbackscal.pl

HD_INSTALL_PFILES       = ahbackscal.par

HD_INSTALL_HELP         = ahbackscal.html

include ${HD_STD_MAKEFILE}

