#
# NOTE: The original script name is 'bat-burst-advocate' 
#   This makefile descends one level to the batgrbproduct
#   subdirectory, where the 'batgrbproduct' script is made.
#   It is made via a simple text transformation via sed.
#
# DO NOT!!! edit batgrbproduct.  Instead, edit bat-burst-advocate
#   and then re-run hmake.
#

HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	=

HD_SUBDIRS		= batgrbproduct BAT

HD_TEST_PERL_SCRIPTS	= ut_batgrbproduct

HD_TEST_PFILES		= ut_batgrbproduct.par

HD_INSTALL_PERL_SCRIPTS	= bat-burst-advocate

HD_INSTALL_PFILES	= bat-burst-advocate.par 

HD_INSTALL_HELP		= bat-burst-advocate.html 

include ${HD_STD_MAKEFILE}
