#!/usr/bin/perl
#
#  ut_nusplitsc_fpmb
#
#
#
# Changes:
#      0.1.0 : RF 07/04/2016 - First Release

#
#

use strict;
use ut_nustar;



# main
{
# Object Istances
    my $ut = ut_nustar->new(
			    name    => "nusplitsc",
			    utname  => "ut_nusplitsc_fpmb",
			    version => "0.1.0",
			    );
    
# Set Parameter
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
    
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_nusplitsc";  
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/nu80001012004B06_cl.evt.gz",
		   "$input/$ArchDir/nu80001012004B_fpm.hk.gz",
		   "$input/$ArchDir/nu80001012004_chu123.fits.gz",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = (
		    "$input/$ArchDir/nu80001012004B06_chu12_N_cl_fpmb.evt",
		    "$input/$ArchDir/nu80001012004B06_chu23_N_cl_fpmb.evt",
		    "$input/$ArchDir/nu80001012004B06_chu3_N_cl_fpmb.evt",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("nusplitsc","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;

# Task Files Check
    my %par_task = (
		    infile         => "$input/$ArchDir/nu80001012004B06_cl.evt.gz",
		    hkfile         => "$input/$ArchDir/nu80001012004B_fpm.hk.gz",
		    chu123hkfile   => "$input/$ArchDir/nu80001012004_chu123.fits.gz",
		    chu123rangefile=> "CALDB",
		    splitmode      => "NORMAL",
		    timecut        => "no",
		    outdir         =>  $output,
		    chatter        => $chat,
		    clobber        => "$clobber",
		    history        => "yes", 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/nu80001012004B06_chu12_N_cl.evt");
	$ut->fverify("$output/nu80001012004B06_chu23_N_cl.evt");
	$ut->fverify("$output/nu80001012004B06_chu3_N_cl.evt");
	
	
# ftdiff
	$ut->ftdiff("$output/nu80001012004B06_chu12_N_cl.evt","$input/$ArchDir/nu80001012004B06_chu12_N_cl_fpmb.evt");
	$ut->ftdiff("$output/nu80001012004B06_chu23_N_cl.evt","$input/$ArchDir/nu80001012004B06_chu23_N_cl_fpmb.evt");
	$ut->ftdiff("$output/nu80001012004B06_chu3_N_cl.evt","$input/$ArchDir/nu80001012004B06_chu3_N_cl_fpmb.evt");

    }
    
    $ut->delete();
}

