HD_COMPONENT_NAME	= swift

HD_COMPONENT_VERS	= 

HD_INSTALL_PERL_SCRIPTS	= uvotcoincidence

HD_TEST_PERL_SCRIPTS	= ut-uvotcoincidence

HD_INSTALL_PFILES	= uvotcoincidence.par

HD_TEST_PFILES		= ut-uvotcoincidence.par

HD_INSTALL_HELP		= uvotcoincidence.html

include ${HD_STD_MAKEFILE}
