CVSRCS_ID           := "$$Name: heasoft6_20_20170113 $$ $$Id: Makefile,v 1.21 2016/02/18 12:53:50 klrutkow Exp $$"

#$(info $$Name: heasoft6_20_20170113 $$ $$Id: Makefile,v 1.21 2016/02/18 12:53:50 klrutkow Exp $$)

HD_COMPONENT_NAME		= hitomi

HD_COMPONENT_VERS		= 

HD_SUBDIRS			= hxisgdsff hxisgdpha hxisgddtime hxievtid sgdevtid sgdarfgen hxisgdexpand hxisgdshield hxisgdmerge

HD_TEST_SUBDIRS			= ${HD_SUBDIRS}

include ${HD_STD_MAKEFILE}
