HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= grppha2

HD_CTASK_SRC_c		= hgrppha2.c grppha2.c readphaIIkeywd.c writephaI.c \
			  writephaIIkeywd.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= grppha2.par

HD_INSTALL_HELP		= grppha2.txt

include ${HD_STD_MAKEFILE}
