HD_COMPONENT_NAME	= suzaku

HD_COMPONENT_VERS	=

HD_INSTALL_HEADERS	= \
aste_att.h aste_coord.h aste_rand.h aste_teldef.h \
aste_time.h aste_hdouble.h attfile.h teldef.h aste_rpt.h

include ${HD_STD_MAKEFILE}
