HD_COMPONENT_NAME	= heatools

HD_COMPONENT_VERS	=

HD_CTASK		= ftinsert

HD_CTASK_SRC_c		= ftinsert.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= ftinsert.par

HD_INSTALL_HELP		= ftinsert.html

include ${HD_STD_MAKEFILE}
