#makefile for lib.press
#oday - 2 Sept 92
FCOMPL =
FCOPTS =
FLOPTS =
XANLIB = 
PGPLOT =
SYSLIB =
XANAME = xanhigh

OFILES= misc.o poidev.o ran1.o

LIB: $(OFILES)
	liball $(XANBIN)/lib/$(XANAME).a

compile: $(OFILES)

clean :
	rm -f *.o *.s *~

.f.o:
	xfor $*
