HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_LIBRARY_ROOT		= gro${FT_VERS}

HD_LIB_STYLE		= ${HD_LIB_STYLE_F77}

HD_LIBRARY_SRC_c	= bcopy.c fileexists.c file_size.c ftio.c gro_unlink.c \
			  kmvc.c nulls.c readscalefactors.c readtable.c

HD_LIBRARY_SRC_f	= aecon.f batse_ftools_routines.f cmpare.f convrt.f \
			  ctalog.f extrp.f fitazi.f fits2cal.f \
			  free_ftiounit.f ftio_close.f ftio_errmsg.f \
			  ftio_open.f ftio_read.f ftio_rewind.f ftio_write.f \
			  ftn_errmsg.f gidate.f grdtjd.f intrpl.f map.f \
			  newunit.f remove.f senstv1.f senstv2.f senstv3.f \
			  smooth.f sunlinux.f tjdgrd.f weight.f

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_INSTALL_LIBRARIES	= ${HD_LIBRARY_ROOT}

#HD_INSTALL_HEADERS	= ftio.h ftiosys.h ftnerr.h utility.h

include ${HD_STD_MAKEFILE}
