#!/usr/bin/perl
#
#  ut_nuskytodet_fpma
#
#
#
# Changes:
#      0.1.0 : NS 12/10/2012 - First Release
#
#

use strict;
use ut_nustar;



# main
{
# Object Istances
    my $ut = ut_nustar->new(
			    name    => "nuskytodet",
			    utname  => "ut_nuskytodet_fpma",
			    version => "0.1.0",
			    );
    
# Set Parameter
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
    
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_nuskytodet";  
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/nu00015011001_att.fits.gz",
		   "$input/$ArchDir/nu00015011001_mast.fits.gz",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_nuskytodet_fpma.fits",
		    );

    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("nuskytodet","ftdiff","fverify", "pquery2");

    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;

# Task Files Check
    my %par_task = (
		    pntra          =>  187.2779154,
		    pntdec         =>  2.0523883,
		    attfile        =>  "$input/$ArchDir/nu00015011001_att.fits.gz",
		    alignfile      =>  "CALDB",
		    teldef         =>  "CALDB",
		    instrument     =>  "FPMA",
		    aberration     =>  "no",
		    skydetfile     =>  "$output/out_nuskytodet_fpma.fits",
		    skyxref        =>  500.0,
		    skyyref        =>  500.0,
		    mastaspectfile =>  "$input/$ArchDir/nu00015011001_mast.fits.gz",
		    initseed       =>  "yes",
		    chatter        =>  $chat,
		    clobber        =>  "$clobber",
		    history        =>  "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/out_nuskytodet_fpma.fits");
	
	
# ftdiff
	$ut->ftdiff("$output/out_nuskytodet_fpma.fits",
		    "$input/$ArchDir/ut_nuskytodet_fpma.fits");
    }    
    
    $ut->delete();
}

