HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	=

HD_SUBDIRS		= addarf addrmf brcaldb calcrpsf caldbflag caldbinfo \
			  c_caldbflag c_caldbinfo c_crtcif chkcif cifcadd \
			  cmppha cmprmf col2img crcif dmprmf gcorpha gcorrmf \
			  genrsp lstgood marfrmf mkcaldb mkcaldir mkcalinit \
			  mudcif quzcif rbnrmf rbnrpsf rpsf2eef rpsfqdp \
			  rsp2rmf st2rpsf stcal udcif

include ${HD_STD_MAKEFILE}
