HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= fadmap

HD_CTASK_SRC_c		= hfadmap.c

HD_CTASK_SRC_f		= fadmap.f read_subs.f subs1.f subs2.f

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_FFLAGS		= ${HD_STD_FFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= fadmap.par

HD_INSTALL_HELP		= fadmap.hlp fadmap.txt

include ${HD_STD_MAKEFILE}
